- docs/api/nailgun.rst
- docs/api/tests.rst
- docs/conf.py
- nailgun/config.py
- setup.py
- tests/test_config.py
The module contains "tools for managing and presenting server connection
configurations." Most importantly, this module contains a class called
`ServerConfig`, and it does all the heavy lifting.
Include the new module in the documentation.
Add unit tests for the new module.
Fix #2.
> Add module `nailgun.config`

- docs/api/nailgun.rst
- docs/conf.py
- nailgun/config.py
- tests/test_config.py
Two commits are included in this pull request for the sake of expediency, not due to any particular technical constraint. Summary of changes:
* Create class `BaseServerConfig`, and make it the parent of class `ServerConfig`. The former contains re-usable functionality, and the latter contains NailGun-specific customizations.
* Make API documentation include documentation for members (functions, methods and attributes) and special members (e.g. `__init__`) by default.
Please see the individual commits for more detailed commit messages. This is likely to be the last pull request before releasing version 0.2.0.
> Add class `BaseServerConfig`, update API docs

- nailgun/entity_fields.py
- tests/test_entity_fields.py
Added code that generates ``DateField`` and ``DatTimeField`` entities.
This will be useful for synchronization plans and schedule tasks in
``Robottelo``.
> Generate ``DateField`` and ``DatTimeField``.

- nailgun/entities.py
Issue is similar to described in pull request [SatelliteQE/robottelo#1611](https://github.com/SatelliteQE/robottelo/pull/1611) (full description there)
Robottelo tests ```test_associate_product_1``` and ```test_associate_product_3``` were failing for me with following trace:
```
File "robottelo/tests/foreman/ui/test_activationkey.py", line 1244, in test_associate_product_3
rh_repo['releasever']
File "robottelo/robottelo/api/utils.py", line 117, in enable_rhrepo_and_fetchid
prd_id = entities.Product().fetch_rhproduct_id(name=product, org_id=org_id)
File "nailgun/nailgun/entities.py", line 2094, in fetch_rhproduct_id
"The length of the results is:", len(results))
APIResponseError: ('The length of the results is:', 0)
```
The root cause is ```entities.Product.fetch_rhproduct_id``` returning …
> Fix entities.Product.fetch_rhproduct_id returning no results

- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- setup.py
- tests/test_config.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
There are two commits in this branch, and I recommend looking at both commit messages for full details. Summary of changes in this branch:
* Give class `BaseServerConfig` (and `ServerConfig`) an instance attribute named   "version". This attribute can be used by entity classes when figuring out how to talk to a server. For example, method `Product.read` will perform a time-consuming work-around for a bug in the server's response, but only if the server is running version 6.0.
* Change entity fields from class attributes to instance attributes:
> Representing entity fields as instance attributes allows the exact set of
> fields on a given entity to be determined at run-time. Thus, you could have
> one Repository object that targets 6.0 and does not have a
> `docker_upstream_name` field and …
> Let NailGun target multiple server versions

- nailgun/entities.py
- tests/test_entities.py
You can now create, read and delete locations.
```python
In [1]: from nailgun.entities import Location
In [2]: foo = Location().create()
In [3]: foo.get_values()
Out[3]:
{'compute_resource': [],
'config_template': [<nailgun.entities.ConfigTemplate at 0x107c0be90>,
<nailgun.entities.ConfigTemplate at 0x107c0b910>,
<nailgun.entities.ConfigTemplate at 0x107c16050>,
<nailgun.entities.ConfigTemplate at 0x107c16310>,
<nailgun.entities.ConfigTemplate at 0x107c165d0>,
<nailgun.entities.ConfigTemplate at 0x107c16890>,
<nailgun.entities.ConfigTemplate at 0x107c16b50>,
<nailgun.entities.ConfigTemplate at 0x107c16e10>,
<nailgun.entities.ConfigTemplate at 0x107c19110>,
<nailgun.entities.ConfigTemplate at 0x107c193d0>,
<nailgun.entities.ConfigTemplate at 0x107c19690>,
<nailgun.entities.ConfigTemplate …
```
> Adding support for Location entity.

- nailgun/entities.py
- tests/test_entities.py
Though creating a new capsule (aka smart proxy) via the API is something
thst requires a bit more research, one can at least GET existing ones:
```python
In [5]: from nailgun.entities import SmartProxy
In [6]: sp = SmartProxy(id=1).read()
In [7]: sp.get_values()
Out[7]:
{'id': 1,
'name': u'$FQDN',
'url': u'https://$FQDN:9090'}
```
Also, added a new ``refresh`` method to ``SmartProxy``:
```python
In [2]: SmartProxy(id=1).refresh()
Out[2]:
{u'created_at': u'2015-04-27T20:34:54Z',
u'id': 1,
u'name': u'$FQDN',
u'updated_at': u'2015-04-27T20:34:54Z',
u'url': u'https://$FQDN:9090'}
```
> Adding ``EntityReadMixin`` to ``SmartProxy``.

- nailgun/entities.py
- tests/test_entities.py
I have updated the instance attibutes for ``Subnet`` to match what's
currently exposed via the v2 API.
```python
In [21]: from nailgun import entity_mixins
In [22]: entity_mixins.CREATE_MISSING = True
In [23]: foo = Subnet().create()
In [24]: foo.get_values()
Out[24]:
{'boot_mode': u'DHCP',
'dhcp': None,
'dns': None,
'dns_primary': None,
'dns_secondary': None,
'domain': [],
'from_': None,
'gateway': None,
'id': 4,
'ipam': u'DHCP',
'location': [],
'mask': u'192.0.0.0',
'name': u'\ub05b\u7330\u34bf\u5ad6\u58ae\u80e0\ua45e\u86dc\u3d32\u77d9\u587b\u51f1\uba8f\u39ab\u4fee\u7180\u3de3\u5e04\u0510\u5d94\u5133\u49ab\u5c48\u95a9\uad34\u8fbb\u48f4\u81ad\ua5b3',
'network': u'242.126.150.103',
'organization': [],
'tftp': None,
'to': None,
'vlanid': None}
In [25]: foo.delete()
Out[25]:
{u'boot_mode': …
```
> Updated instance attributes for ``Subnet``.

- nailgun/entities.py
Users can be associated with zero or more roles via the API, as stated by [BZ 1216239](https://bugzilla.redhat.com/show_bug.cgi?id=1216239).
> Add the "role" field to the "User" entity

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Fix #55. Prevent users from assigning non-iterable values to `OneToManyField`s.
For example:
>>> from nailgun.entities import Architecture
>>> Architecture(operatingsystem=[1])
<nailgun.entities.Architecture object at 0x7f17df759390>
>>> Architecture(operatingsystem=1)
File "<stdin>", line 1, in <module>
File "nailgun/entities.py", line 239, in __init__
super(Architecture, self).__init__(server_config, **kwargs)
File "nailgun/entity_mixins.py", line 280, in __init__
.format(field_name, field_value)
nailgun.entity_mixins.BadValueError: An inappropriate value was assigned to the "operatingsystem" field. An iterable of entities and/or entity IDs should be assigned, but the following was given: 1
> Check values assigned to `OneToManyField`s

- nailgun/client.py
- nailgun/config.py
- nailgun/entity_mixins.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entity_mixins.py
Fix #53:
> When a nailgun.entity_mixins.Entity object is stringified, little useful
> information is provided. The full dotted path to the object's type is
> provided, in addition to its memory address. However, […] that's not terribly
> useful, and it's ugly to boot
Implement and unit test the following methods:
* `nailgun.config.ServerConfig.__repr__`
* `nailgun.entity_mixins.Entity.__repr__`
Example usage (slightly edited):
```python
>>> from nailgun.entities import Product
>>> product = Product(id=1).read()
>>> product
nailgun.entities.Product(
nailgun.config.ServerConfig(
url=u'https://sat.example.com';,
verify=False,
version=<Version('6.1')>,
auth=(…)
),
gpg_key=None,
description=None,
label=u'Red_Hat_Beta',
organization=nailgun.entities.Organization(
nailgun.config.ServerConfig( …
```
> Customize how entity objects are stringified

- nailgun/__init__.py
- nailgun/client.py
Fix #61:
> When a message is sent to the logging system, that message must be handled
> some how. A typical method of handling a logging message is to simply print it
> to stderr, but other handlers might send the message to a file, fire off an
> email, emit an SMTP message or anything else you can dream up.
>
> Currently, NailGun has no logging handlers. Thus, when the nailgun.client
> logging element a logging message, that message is handed up to nailgun
> logging element, and it is then discarded.
Here's what a logging message now looks like:
> WARNING:nailgun.client:Received HTTP 422 response: {
>   "error": {"id":null,"errors":{"name":["can't be blank"]},"full_messages":["DNS domain can't be blank"]}
> }
Also, replace a call to `warn` with a call to `warning`. `warn` is deprecated.
> Properly configure logging system

- docs/create_organization_nailgun_v2.py
- docs/examples.rst
- nailgun/config.py
Fix #44:
> The API documentation briefly mentions how to effectively use `ServerConfig`
> objects in the docstring for class `Entity`:
>
> > An entity object is useless if you are unable to use it to communicate with a
> > server. The solution is to provide a nailgun.config.ServerConfig when
> > instantiating a new entity. This configuration object is stored as an instance
> > variable named _server_config and used by methods such as
> > nailgun.entity_mixins.Entity.path().
> >
> > 1. If the server_config argument is specified, then that is used.
> > 2. Otherwise, if nailgun.entity_mixins.DEFAULT_SERVER_CONFIG is set, then that
> > is used.
> > 3. Otherwise, call nailgun.config.ServerConfig.get().
>
> That's it, though. And the docstring for `ServerConfig.get` is pretty terrible.
> The …
> Provide examples of using ServerConfig objects

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Fix #63 and add unit tests for the fix:
> When `create_missing` is called on an entity, it fills in all fields that are
> required and that do not have values. When filling in a field such as an
> `IntegerField` or a `StringField`, the process of creating a bogus value is
> straight-forward. When filling in a `OneToOneField` or `OneToManyField`, the
> process is more delicate. The correct entity class must be instantiated with
> an appropriate `nailgun.config.ServerConfig` object, and all of the dependent
> entity's required fields must also be filled in. Currently, method
> `nailgun.entity_mixins.EntityCreateMixin.create_missing` does not do that.
> Currently, the method instantiates a new entity without passing in a
> `ServerConfig` object (causing the new object to search for a server …
> Give generated entities a server config object

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Fix #30:
> The inner Meta classes are arguably a bad idea. A class should contain a
> bundle of data and logic that operates on that data. However, the Entity
> classes contain only data. By this reasoning, it is better to drop the Meta
> classes and add a regular class attribute to hold the same data.
A more serious issue is that the use of an inner class brings shared state to
all entity classes. One way in which this is problematic is that is prevents
safe customization of an entity's API path. One class that does this is
`ContentViewPuppetModule`. It has API paths in the following form:
/content_views/:content_view_id/content_view_puppet_modules
/content_views/:content_view_id/content_view_puppet_modules/:id
When a `ContentViewPuppetModule` is instantiated, it sets its API path to …
> Drop the inner `Meta` class from entities

- nailgun/entities.py
- tests/test_entities.py
One thing that the default `read` method does is to pass the current entity
object's server configuration to the entity object being created. Both parent
and child entity objects should talk to the same server with the same
credentials and so on. Unfortunately, several of the `read` method overrides in
module `nailgun.entities` fail to do that. Add a unit test for these methods to
ensure that they do so.
`ContentViewFilterRule.read` calls `keys` on a dict, then iterates through those
keys and modifies the underlying dict. This works on Python 2 where `keys`
returns an entirely new object, but it fails in Python 3 where `keys` returns a
view object:
$ make test
…
File "/home/ichimonji10/code/nailgun/tests/test_entities.py", line 435, in test_sync_plan …
> Unit test overridden read() methods

- nailgun/entities.py
- tests/test_entities.py
`entities.DockerHubContainer` needs to 'inherit' the fields from
`entities.AbstractDockerContainer`.
Before change:
```python
In [9]: AbstractDockerContainer().get_fields().keys()
Out[9]:
['cpu_set',
'tty',
'attach_stderr',
'name',
'attach_stdin',
'compute_resource',
'command',
'location',
'memory',
'organization',
'entrypoint',
'id',
'attach_stdout',
'cpu_shares']
In [10]: DockerHubContainer().get_fields().keys()
Out[10]:
['cpu_set',
'tty',
'attach_stderr',
'name',
'attach_stdin',
'compute_resource',
'command',
'location',
'memory',
'organization',
'entrypoint',
'id',
'attach_stdout',
'cpu_shares']
In [11]: AbstractDockerContainer().get_fields().keys() == DockerHubContainer().get_fields().keys()
Out[11]: True
```
After changes:
```python
In [2]: DockerHubContainer().get_fields().keys() …
```
> Abstracted Docker entity should inherit fields.

- .gitignore
- Makefile
- nailgun/client.py
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_client.py
- tests/test_entities.py
- tests/test_entity_fields.py
Add unit tests for all manner of code in NailGun. Improve coverage from 64% to
82%. There is still room for significantly improving the test suite, and these
added tests simply represent some of the low-hanging fruit.
Test results against a downstream system:
$ nosetests tests/foreman/api/test_multiple_paths.py
...S...S......S...............................................................S...S..........................................................................................................................................SSS..S.S.SSSSSS.S..SS.SSSSSSSSSSSSSSSSSSSSSSSSSSSS
Ran 271 tests in 487.348s
OK (SKIP=47)
Also, document the new `test-coverage` make target.
> Improve test coverage

- docs/create_user_nailgun.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_mixins.py
Why use this method? From the method docstring:
> This method returns a dict of attributes that can be unpacked and used as
> kwargs via the ``**`` operator. For example::
>
>     cfg = ServerConfig.get()
>     client.get(cfg.url + '/api/v2', **cfg.get_client_kwargs())
>
> This method is useful because client code may not know which attributes should
> be passed from a ``ServerConfig`` object to one of the ``nailgun.client``
> functions. Consider that the example above could also be written like this::
>
>     cfg = ServerConfig.get()
>     client.get(cfg.url + '/api/v2', auth=cfg.auth, verify=cfg.verify)
>
> But this latter approach is more fragile. It will break if ``cfg`` does not
> have an ``auth`` or ``verify`` attribute.
In other words, using `get_client_kwargs` is more robust than …
> Use method `ServerConfig.get_client_kwargs`

- requirements-dev.txt
- setup.py
First commit:
> Mark fauxfactory as a required dependency
>
> Fix #81. fauxfactory is a required dependency of NailGun. Mark it as such.
Second commit:
> List `requests>=2.7` in dependencies
>
> NailGun requires that requests 2.7.0 or higher be installed. List this
> requirement in `setup.py`. This should address the following use case:
>
> ```sh
> rm -rf env
> virtualenv env
> source env/bin/activate
> pip install requests==2.6.0
> pip install -e ~/code/nailgun
> pip list | grep requests
> ```
>
> If no minimum requests version is specified, then the above script will output
> `requests (2.6.0)`. Specifying a minimum version will cause the above script to
> output `requests (2.7.0)`.
> Mark fauxfactory as a required dependency

- nailgun/entities.py
- tests/test_entities.py
The entity class `AbstractComputeResource` defines a set of fields that all
inheriting classes use. For example, all compute resources have a name and
provider. Child classes should be able to extend that set of fields. For
example, `LibvirtComputeResource` adds the `display_type` and
`set_console_password` fields.
Currently, that inheritance is broken. The following fails:
from nailgun.entities import LibvirtComputeResource
LibvirtComputeResource(display_type='VNC')
Similarly, any field which is defined on a child class cannot be assigned to
directly. Fix this.
> Fix AbstractComputeResource inheritance

- nailgun/entities.py
- tests/test_entities.py
A domain can be associated with a smart proxy via its "dns" field. Add this
field and all workaround necessary for this field to function properly. Example
usage:
```python
>>> domain = entities.Domain(dns=1).create()
>>> domain.get_values()
{
'dns': nailgun.entities.SmartProxy(
nailgun.config.ServerConfig(…),  # redacted
id=1
),
'domain_parameters_attributes': [],
'fullname': None,
'id': 53,
'location': [],
'name': 'j9jm4wvery',
'organization': [],
}
>>> domain2 = domain.read()
>>> domain3 = entities.Domain(id=53).read()
```
Fix #93. Related to #94.
> Add field `Domain.dns`

- Makefile
Also, rearrange the `.PHONY` list of targets to match the actual ordering of the
targets in the body of the make file.
> Mark "test-coverage" as a phony make target

- nailgun/entities.py
Method `EntityCreateMixin.create` has the following method signature:
create(create_missing=None)
Several methods in module `nailgun.entities` extend or override it. Those other
methods should have the same signature.
> Fix `create()` method signatures

- docs/examples.rst
Fix #90.
Link directly to the YouTube video so that all documents produced by Sphinx —
HTML, EPUB, PDF, etc — can properly reference the video. In addition, embed the
video directly in to the documentation when HTML output is generated.
For technical details, see:
http://docutils.sourceforge.net/docs/ref/rst/directives.html#raw-data-pass-through
Tested with `make html` and `make epub`.
> Reference the "NailGun Hands On" video

- nailgun/entities.py
- tests/test_entities.py
Added in paths for RHCI's satellite-based deployments.
POST fusor/api/v2/deployments
PUT fusor/api/v2/deployments/:id/deploy
DELETE fusor/api/v2/deployments/:id
Added three unit tests for the added paths.
> Add support for RHCI deployment testing

- docs/index.rst
NailGun is no longer in the process of being extraced from Robottelo. Reference
example code before pointing to real-world usages of NailGun.
> Make minor corrections to documentation

- nailgun/entities.py
- requirements-dev.txt
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
Add "unittest2" as a dependency. This package backports many features to older
versions of Python. For example, it makes the `assertRegex` assertion and
`subTest` context manager available in older versions of Python. As a result:
* Drop "ddt" as a dependency.
* Drop some testing logic that makes use of versioning information.
Reorganize `tests/test_entities.py`:
> This file is divided in to three sets of test cases (`TestCase` subclasses):
>
> 1. Tests for inherited methods.
> 2. Tests for entity-specific methods.
> 3. Other tests.
Fiddle with a few methods in module `nailgun.entities` by replacing custom
response handling logic with calls to function
`nailgun.entities._handle_response`. Add some new unit tests for module
`nailgun.entities.`
> Change dependencies, revamp tests/test_entities.py

- nailgun/entity_fields.py
Fix #113:
> the `module` attribute is absolutely useless. It does nothing. The `module`
> argument and attribute are outdated relics of when the `OneToOneField` was a
> class attribute. As a result, it should be removed.
> Drop extra attribute from `OneTo*Field` classes

- nailgun/entities.py
- nailgun/entity_mixins.py
- setup.py
- tests/test_entities.py
- tests/test_entity_mixins.py
Fix #110:
> Rather than hacking around the hash/ID discrepancies on an individual basis,
> NailGun should search for both IDs and hashes when trying to populate foreign
> key fields on entities. Doing so will let NailGun be more robust and let us
> remove much redundant code from module `nailgun.entities`.
Fix #114:
> NailGun should be capable of dealing with the pluralized version of a field
> name.
Test results against downstream:
$ make test-foreman-api
python -m cProfile -o test-foreman-api.pstats $(which nosetests) --logging-filter=nailgun,robottelo --with-xunit --xunit-file=foreman-results.xml tests/foreman/api
......SSS.....................S....................E......................SSSSSSSSSSSSSSSSSSSSSSSS........SSSSSSSSSSSSSSSSSSSSSSSSS..............SSSSSSSSSSSSS.............S.SS …
> Deal more robustly with server responses

- nailgun/entities.py
- tests/test_entities.py
Fix #112: "RHCIDeployment entity has bad fields". Change the following from
`IntegerField`s to `OneToOneField`s:
* lifecycle_environment_id
* organization_id
* rhev_engine_host_id
Also, extend the `read()` method and make it normalize the server's response.
Manual test results:
>>> rhci_deployment = entities.RHCIDeployment(id=1).read()
> Fix RHCIDeployment fields

- nailgun/entities.py
The `ContentView.component` field points to a content view version, not a
content view. The `ContentViewVersion` entity has a "content_view" attribute.
Fix both of these discrepancies.
> Fix bug with ContentView and ContentViewVersion

- nailgun/entities.py
- tests/test_entities.py
Added ```entities.Product.list_available_rhrepos()``` func. Need it in tests to verify after ```enable_rhrepo()``` or ```disable_rhrepo()``` repository was actually enabled/disabled, not just by checking response status.
Tests results:
```
make test
.............................................................................................................................................
Ran 141 tests in 0.247s
OK
```
> Added entities.Product.list_available_rhrepos() func

- docs/examples.rst
* Add table of contents where appropriate.
* Place the video introduction in to its own section.
* Explain how it is possible to call `create()`, `read()`, etc on both brand new
and existing objects.
> Update "examples" section in documentation

- docs/create_organization_plain.py
After updating script with a correct URL and adding a param so that it ignores
SSL verification, it runs just fine:
$ docs/create_organization_plain.py
{'ancestry': None,
'apply_info_task_id': None,
'created_at': '2015-06-25T14:49:42Z',
'default_info': {'distributor': [], 'system': []},
'description': None,
'id': 463,
'ignore_types': [],
'katello_default': True,
'label': 'junk_org',
'name': 'junk org',
'service_level': None,
'service_levels': [],
'title': 'junk org',
'updated_at': '2015-06-25T14:49:42Z'}
> Update documentation example

- nailgun/entities.py
- tests/test_entities.py
Added ```entities.Location.update()```, as it's needed for SatelliteQE/robottelo#2427 .
Also updated tests and submitted [BZ1236008](https://bugzilla.redhat.com/show_bug.cgi?id=1236008).
> Add entities.Location.update()

- nailgun/entities.py
- tests/test_entities.py
These two commits are logically separate, but I'm bundling them together for convenience's sake. They touch the same bits of code, so it'd be a pain to submit separate PRs due to the resultant merge conflicts. For full details, see the individual commit messages. Summary of changes:
1. Fix a bug in `HostGroup.read` caused by c420ab6e1ecbe2b7b802a8b9114bb1a87f2f8529. (And this is why we have releases and no longer make Robottelo clone the repo fresh for each test run.)
2. Make some code much more concise by taking advantage of #110.
> Fix a bug. Refactor for conciseness.

- nailgun/entities.py
Added ```entities.PartitionTable.update()```, as it's needed for SatelliteQE/robottelo#2502.
Part of #111.
> Add entities.PartitionTable.update()

- nailgun/entities.py
- tests/test_entities.py
Add the `content_view` and `lifecycle_environment` fields to the `HostGroup`
entity for Satellite 6.1.0 and beyond. Make `HostGroup.read` deal with BZ
1235377 [1]:
> A hostgroup has at least the following attributes:
>
> […]
>
> GET /api/v2/hostgroups/:id returns the following attributes:
>
> […]
>
> The following attributes are not mentioned in the response:
>
> * content_view
> * lifecycle_environment
Doing this allows the `HostGroup` entity to make use of features available in
Satellite 6.1.0 while retaining backward compatibility with Satellite 6.0.8. Add
unit tests and perform manual testing:
>>> cfg_608 = ServerConfig.get('sat608-rhel6')
>>> cfg_610 = ServerConfig.get('sat6-rhel71')
>>> hg_608 = entities.HostGroup(cfg_608, id=1).read()
>>> hg_610 = entities.HostGroup(cfg_610, …
> Add fields to `HostGroup` entity

- nailgun/entities.py
Added support to update content view filters, need it for SatelliteQE/robottelo#2463.
No bugs/workarounds for ```update()```, CVF are updating just fine.
```
make test 
..................................................................................................................................................
Ran 146 tests in 0.180s
OK
```
> Added support to update content view filters

- nailgun/entities.py
Place a `pylint:disable` directive at the end of a line. Doing so causes pylint
to ignore the named warning for that one line, rather than for all following
code at the same indentation level — in this case, almost a thousand lines of
code.
> Move a pylint directive

- docs/create_organization_nailgun.py
- docs/create_organization_nailgun_v2.py
- docs/create_organization_plain.py
- docs/create_user_nailgun.py
- docs/create_user_plain.py
- docs/index.rst
Add brief examples of how to use NailGun to the beginning of the documentation.
This should serve as a simple reference that will help new-comers on-board.
Fiddle with existing documentation. Make the calls to `pprint` more concise and
add a few explanatory comments.
> Rearrange documentation

- nailgun/entities.py
Fix #105. The `ActivationKey` entity's `environment` field is incorrectly
defined as referencing an `Environment` entity. It should reference a
`LifecycleEnvironment` entity.
Before fix:
```python
>>> env = entities.Environment(id=1)
>>> lce = entities.LifecycleEnvironment(id=1)
>>> entities.ActivationKey(environment=env).create_payload()
{'environment_id': 1}
>>> entities.ActivationKey(environment=lce).create_payload()
{'environment_id': nailgun.entities.LifecycleEnvironment(…)}  # uh oh!
```
After fix:
```python
>>> env = entities.Environment(id=1)
>>> lce = entities.LifecycleEnvironment(id=1)
>>> entities.ActivationKey(environment=env).create_payload()
{'environment_id': nailgun.entities.Environment(…)}
>>> …
```
> Fix a OneToOneField

- nailgun/entities.py
The `System` entity's `environment` field is incorrectly defined as referencing
an `Environment` entity. It should reference a `LifecycleEnvironment` entity.
Before fix:
>>> env = entities.Environment(id=1)
>>> lce = entities.LifecycleEnvironment(id=1)
>>> entities.System(environment=env).create_payload()
{'environment_id': 1}
>>> entities.System(environment=lce).create_payload()
{'environment_id': nailgun.entities.LifecycleEnvironment(…)}
After fix:
>>> env = entities.Environment(id=1)
>>> lce = entities.LifecycleEnvironment(id=1)
>>> entities.System(environment=env).create_payload()
{'environment_id': nailgun.entities.Environment(…)}
>>> entities.System(environment=lce).create_payload()
{'environment_id': 1}
> Fix a System OneToOneField

- nailgun/entities.py
Got tired of random test [failures](https://github.com/SatelliteQE/robottelo/issues/2211) [because](https://github.com/SatelliteQE/robottelo/issues/2319) [of](https://github.com/SatelliteQE/robottelo/issues/2318) [partition](https://github.com/SatelliteQE/robottelo/issues/2291) [tables](https://github.com/SatelliteQE/robottelo/issues/2229) [bug (BZ1229384)](https://bugzilla.redhat.com/show_bug.cgi?id=1229384).
This one-line PR should get rid of it.
**Pros**:
+ Tests will stop failing
+ Bug is pretty annoying, as failures are random (only when randint(1,30) throws 1), short failure log contains just common '422' error. As a result it's always time-consuming to detect the issue for each new build. 
+ We're not decreasing coverage, as there already …
> Fix for a random ptable.name bug

- nailgun/entities.py
- Previously the partition table name length was defined to be a minimum of 2 characters.  But sometimes when the name is decoded from bytes to a logical character, the name of 2 characters length becomes one character long which causes the failure again.  To fix this, the partition table name minimum length will be 4 characters now.
> Fixes an api unicode issue for partition table names.

- nailgun/entities.py
- tests/test_entities.py
As of Satellite 6.1.1, the `/katello/api/v2/sync_plans` path is available. Make
use of it. Ensure that NailGun uses the
`/katello/api/v2/organizations/<id>/sync_plans` path when working with Satellite
6.1.0 and older. Manual test results:
```python
>>> from nailgun import entities; from nailgun.config import ServerConfig
>>> cfg1 = ServerConfig.get('old-sat')  # 6.1.0
>>> cfg2 = ServerConfig.get('new-sat')  # 6.1.1
>>> sp1 = entities.SyncPlan(cfg1, id=1, organization=1)
>>> sp2 = entities.SyncPlan(cfg2, id=1)
>>> hasattr(sp1, 'enabled'), hasattr(sp2, 'enabled')
(False, True)
>>> sp1.path()
'https://old-sat.example.com/katello/api/v2/organizations/1/sync_plans/1'
>>> sp2.path()
'https://new-sat.example.com/katello/api/v2/sync_plans/1'
>>> sp1 = sp1.read()
>>> sp2 = sp2.read()
```
> Update SyncPlan entity

- nailgun/entities.py
- tests/test_entities.py
Fix #150:
> AuthSourceLDAP.create_missing overwrites values #150
>
> To reproduce this bug, do something like the following:
>
>     auth_source = AuthSourceLDAP(attr_firstname='foo')
>     auth_source.create_missing()
>     auth_source.attr_firstname == 'foo'
>
> You'll see that the `attr_firstname` field is overwritten. That's bad!
> Do not overwrite fields

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
As per #134 discussion, together with @oshtaier made `read`'s `ignore` argument to be instance of set instead of tuple. Default value for `ignore` changed to `None`.
This will retain the two advantages:
- None is immutable
- Field should default to an empty iterable
And introduce a new one:
- Sets are much easier to manipulate, e.g. no need to use type castings to add/remove some elements
Closes #134
`[DO NOT MERGE]` prefix till i get test run results and validate everything's OK (~ 1 hour)
> Make `read`'s `ignore` argument easier to manipulate

- docs/create_user_nailgun.py
- docs/examples.rst
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
The first commit implements and tests class `EntitySearchMixin`. The second commit integrates the mixin with several entity classes. See the individual commit messages for more details.
The current NailGun version is 0.18.2. I'd like to release version 0.19.0 today, then include this change in 0.20.0. I am marking this PR as "DO NOT MERGE" for that reason, but am posting the PR now to collect feedback and to keep track of it.
For proof that this PR functions correctly, see <del>FIXME: Fetch information from the future</del> <ins>SatelliteQE/robottelo#2610</ins>.
> EntitySearchMixin

- Makefile
Lint `docs/create_organization_nailgun_v2.py`. List each script one its own line
in the makefile, thus improving readability.
> Tweak `make lint`

- requirements-dev.txt
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Adjust the `requirements-dev.txt` file so that unittest2 is only installed if
Python 3.3 or below is being used. Adjust test modules to only import unittest2
if Python 3.3 or below is being used.
unittest2 is used on Python 3.3 and below so that the `subTest` context manager
can be used in unit tests. There is no need to use unittest2 on Python 3.4 and
above, as this feature has been added to the standard library.
Bonus: refactor out some unnecessary version-checking code.
> Only require unittest 2 for Python 3.3 and below

- nailgun/entities.py
Many entities need to make an assumption about what software version the server
is running. This is currently a PITA to do. The expressions that result are
idiosyncratic and ugly.
Related to #163.
> Standardize versioning logic

- nailgun/entities.py
- tests/test_entities.py
Robottelo part will be provided in separate PRs
Progress:
| Method    | Fix payload   | Fix path      | Transform to search |
| --------- | ------------- | ------------- | ------------------- |
| ActivationKey.add_subscriptions  | Done  | Not needed  | Not needed        |
| ActivationKey.content_override  | Done  | Not needed  | Not needed        |
| AbstractDockerContainer.power  | Done  | Already using best one  | Not needed        |
| AbstractDockerContainer.logs  | Done  | Already using best one  | Not needed        |
| ContentViewVersion.promote  | Done  | Not needed  | Not needed        |
| ContentView.publish  | Done  | Not needed  | Not needed        |
| ContentView.set_repository_ids  | Done  | Seems good enough  | Not needed        |
| ContentView.available_puppet_modules  | Not …
> Fixing 'payload' part for 17 methods from #41 list.

- nailgun/entities.py
- tests/test_entities.py
`Product`:
* `list_repositorysets()` moved to `RepositorySet.list_all()`
* removed `fetch_rhproduct_id()` (use `Product.search()` instead)
* removed `fetch_reposet_id()` (use `RepositorySet.search()` instead)
* `enable_rhrepo()` now accepts `payload` dict instead of explicit parameters
* `enable_rhrepo()` moved to `RepositorySet.enable()`
* `disable_rhrepo()` now accepts `payload` dict instead of explicit parameters
* `disable_rhrepo()` moved to `RepositorySet.disable()`
* `repository_sets_available_repositories()` moved to `RepositorySet.available_repositories()`
`Repository`:
* Added ability to use `search()`
* removed `fetch_repoid` (use `Repository.search()` instead)
* `upload_content()` now accepts `payload` dict instead of explicit parameters
`RepositorySet`:
* Added new entity …
> Review entity methods, part 2

- nailgun/entities.py
- tests/test_entities.py
I would like to add tests around discovery feature. But for this, we need infrastructure along with provisioning where we can boot a unknown host via PXE and it gets IP from configured DHCP server on specific subnet on Foreman server. We don't have such infra for now though I really wanted to have one.
So, here I'm trying to discover a dummy  host via api to add basic tests. We have two api's to create discovered host.
```
POST /api/v2/discovered_hosts 
Create a discovered host
```
Unfortunately, this api doesn't work. I filed an issue in upstream after discussing with dev: http://projects.theforeman.org/issues/11277
The other api is to upload facts for discovered host and it creates the host as well. So I'm trying to create the dummy discovered host using this.
```
POST …
```
> Added discovered_host entity

- nailgun/entities.py
- tests/test_entities.py
* According to the API docs, updates should be wrapped in an extra hash.
* Simplify the test case for `upload_facts`.
* Rename `upload_facts` to `facts`, to match the underlying path.
> Update the `DiscoveredHost` entity

- nailgun/entities.py
- tests/test_entities.py
<ins>What follows is the contents  of the third commit message.</ins>
Fix #41:
> Several methods in module `nailgun.entities` do not map nicely to an
> underlying path. In addition, several methods do not have appropriate
> arguments. The methods exposed by the entity classes should be reviewed to
> make sure that they are appropriately named and placed on the most appropriate
> class.
Though many actions can be performed with the mixins, some do not map nicely to
one of the CRUD verbs. For example, publishing a content view or uploading
content to a repository are actions that cannot be described by the CRUD verbs.
NailGun must be able to carry out actions such as publishing or uploading. But
how? NailGun has thus far addressed these needs by simply adding methods on an
ad-hoc basis. …
> Normalize Helper Methods

- nailgun/entities.py
- tests/test_entities.py
An HTTP POST request should be made, not an HTTP PUT request. Without this fix,
the server responds to requests with an HTTP 404 error.
> Fix a bug in method Subscription.upload

- nailgun/entities.py
- tests/test_entities.py
There are two kinds of methods on entities:
* Methods inherited from a mixin. For example, `ActivationKey.create` is
inherited from the `EntityCreateMixin`.
* Methods defined on that entity, such as `ActivationKey.add_subscriptions`.
The latter set of methods was recently overhauled to make them more uniform. The
methods are now named after the path they call, they are placed on the correct
entities, and their signatures are very similar. However, there are still
differences. Some methods provide default values for their arguments; some
require a second argument; some require only one argument but of a different
kind than others; and so on. This is bad for several reasons:
* It is hard to learn the various methods. A user has to look at the signature
of each individual method and figure …
> Re-work helper methods, again

- nailgun/config.py
- tests/test_config.py
`BaseServerConfig.get` returns an object of type `ServerConfig`. This is
ridiculous. A parent class should never return a sub-class. Before the fix:
```python
>>> from nailgun.config import BaseServerConfig, ServerConfig
>>> path = '/home/ichimonji10/.config/nailgun/server_configs.json'
>>> for cls in (BaseServerConfig, ServerConfig):
...     print(type(cls.get('junk', path=path)))
...
<class 'nailgun.config.ServerConfig'>
<class 'nailgun.config.ServerConfig'>
```
After the fix:
```python
>>> from nailgun.config import BaseServerConfig, ServerConfig
>>> path = '/home/ichimonji10/.config/nailgun/server_configs.json'
>>> for cls in (BaseServerConfig, ServerConfig):
...     print(type(cls.get('junk', path=path)))
...
<class 'nailgun.config.BaseServerConfig'>
<class …
```
> Fix typing issue

- nailgun/config.py
- nailgun/entities.py
- tests/test_config.py
There are two commits in this PR. They're logically separate, but I'm bundling them together for expediency. I can submit two separate PRs if people like. Summary of changes:
* Make `BaseServerConfig.__repr__` encode the `version` attribute in a more sane manner.
* Make `ServerConfig` set a default version is none is passed in.
I expect this will be the last set of changes before I release version 0.21.0 and mark NailGun as beta quality.
> Change BaseServerConfig and ServerConfig classes

- nailgun/config.py
- nailgun/entities.py
- tests/test_config.py
This reverts commit 3857d01803883661503fd90739eb1fbcc0224f20.
This prevents failures due to issues like so:
File "…/tests/foreman/api/test_syncplan.py", line 41, in test_get_routes
org = entities.Organization().create()
File "…/nailgun/entities.py", line 2337, in __init__
if server_config.version >= Version('6.1.1'):  # default: True
AttributeError: 'NoneType' object has no attribute 'version'
> Revert "Make class ServerConfig set a default version"

- nailgun/entities.py
Inspired by #182. Manual verification shows that this works:
>>> from nailgun.entities import HostGroup, DiscoveryRule
>>> host_groups = HostGroup().search()
>>> discovery_rules = DiscoveryRule().search()
>>> len(host_groups), len(discovery_rules)
(11, 1)
>>> all((isinstance(host_group, HostGroup) for host_group in host_groups))
True
>>> isinstance(discovery_rules[0], DiscoveryRule)
True
> Add search mixin to DiscoveryRule and HostGroup

- nailgun/entities.py
- tests/test_entities.py
Rename the `search` field to `search_` in order to avoid a name conflict between
the field and method names.
> Rename DiscoveryRule field

- nailgun/entities.py
I need to this to validate and search some of the entities those are configured by default for configuring a hostgroup.
```
In [3]: arch = entities.Architecture(server_config).search(query={u'search': u'name="x86_64"'})
In [4]: arch[0].id
Out[4]: 1
```
```
In [5]: template1 = entities.ConfigTemplate(server_config).search(query={u'search': u'name="Satellite Kickstart Template"'})
In [6]: template1[0].id
Out[6]: 31
```
```
In [7]: domain = entities.Domain(server_config).search(query={u'search': u'name="idmqe.lab.eng.bos.redhat.com"'})
In [8]: domain[0].name
Out[8]: u'idmqe.lab.eng.bos.redhat.com'
```
```
In [9]: ptable = entities.PartitionTable(server_config).search(query={u'search': u'name="Kickstart default"'})
In [10]: ptable[0].id
Out[10]: 7
```
> updated search mixin for various entities

- nailgun/entities.py
- tests/test_entities.py
According to the bug:
> An HTTP GET /api/v2/discovery_rules/:id returns a hash of information about a
> discovery rule. The "max_count" key is missing from this hash.
Work around this issue. When `DiscoveryRule.read` is called, submit a no-op PUT
request and fetch the `max_count` attribute from the response. Test the change.
See: https://bugzilla.redhat.com/show_bug.cgi?id=1257255
Test results from Robottelo:
$ nosetests tests/foreman/api/test_multiple_paths.py -m DiscoveryRule
..........S
Ran 11 tests in 14.982s
OK (SKIP=1)
$ nosetests tests/foreman/api/test_discoveryrule.py
..........
Ran 10 tests in 10.777s
OK
> Work around BZ 1257255

- nailgun/entities.py
- tests/test_entities.py
After recent fix for https://bugzilla.redhat.com/show_bug.cgi?id=1206679 defect, it become possible to add one more entity to API
> Adding new 'registry' entity

- nailgun/entities.py
- nailgun/entity_fields.py
- tests/test_entities.py
+Removing corresponding workaround
+Removing redundant unit tests
> Make 'nailgun.entity_fields.URLField.gen_value' method always generates unique value

- nailgun/entities.py
Sample test results:
>>> cv_filter = entities.RPMContentViewFilter(content_view=1).create(True)
>>> entities.ContentViewFilterRule(content_view_filter=cv_filter).search()
[]
> Make content view filter rules searchable

- nailgun/entities.py
Add the `EntitySearchMixin` to the following entity classe:
* `AbstractComputeResource`
* `AbstractDockerContainer`
Example of usage:
>>> compute_resources = entities.AbstractComputeResource().search()
>>> compute_resources = [
...     compute_resource
...     for compute_resource in compute_resources
...     if compute_resource.provider == 'Docker'
... ]
>>> len(compute_resources)
25
>>> for compute_resource in compute_resources:
...     compute_resource.id, entities.AbstractDockerContainer(compute_resource=compute_resource).search()
...
(12, [])
(6, [])
(41, [])
(5, [])
(11, [])
(19, [])
(9, [])
(37, [])
(20, [nailgun.entities.AbstractDockerContainer(…), nailgun.entities.AbstractDockerContainer(…), nailgun.entities.AbstractDockerContainer(…)])
(67, [])
(7, [])
(13, [])
(21, …
> Make two more entities searchable

- nailgun/entities.py
- tests/test_entities.py
Updated `Subnet` entity with search and update mixin.
`Search results:`
```
In [8]: entities.Subnet(server_config, name="testsubnet", network="192.168.142.0", mask="255.255.255.0").create()
Out[8]: nailgun.entities.Subnet(nailgun.config.ServerConfig(url='https://foreman_server', verify=False, auth=('admin', 'changeme')), dns_primary=None, domain=[], name=u'testsubnet', organization=[], dns_secondary=None, id=2, network=u'192.168.142.0', boot_mode=u'DHCP', from=None, ipam=u'DHCP', mask=u'255.255.255.0', vlanid=None, gateway=None, to=None, location=[], dns=None, dhcp=None, tftp=None)
In [9]: subnet = entities.Subnet(server_config).search(query={u'search': u'network="192.168.142.0"'})
In [10]: subnet
Out[10]: [nailgun.entities.Subnet(nailgun.config.ServerConfig(url='https://foreman_server', …
```
> Updated 'subnet' entity with search and update mixin

- nailgun/entities.py
- tests/test_entities.py
Make the following changes:
* Make `ContentViewVersion.path` accept "incremental_update" as an argument.
* Add method `ContentViewVersion.incremental_update`.
* Add the `EntitySearchMixin` to the `PuppetModule` entity class.
These changes make it possible to add puppet modules to a content view version
via the "incremental update" mechanism.
> Add functionality for puppet module inc updates

- nailgun/entities.py
Update the docstring for method `HostGroup.create`. Make it reference
https://bugzilla.redhat.com/show_bug.cgi?id=1235377.
Fix #197.
> Make bug work-around reference bug ID

- nailgun/entities.py
Update the docstring for method `Environment.update`. Make it reference
https://bugzilla.redhat.com/show_bug.cgi?id=1262029.
Fix #202.
> Make Environment.update reference bug

- nailgun/entities.py
Update the docstring for method `SmartProxy.update`. Make it reference
https://bugzilla.redhat.com/show_bug.cgi?id=1262037
Fix #203.
> Make SmartProxy.update reference bug

- docs/create_user_nailgun.py
- docs/examples.rst
One of the sample scripts in the documentation is missing a call to the
`create()` method. Add this missing method call.
One of the paragraphs mentions a "hass". This is a typo of "hash". Change the
word to "dict", which will likely be more familiar term to Python users.
> Fix typos in documentation

- nailgun/entities.py
It's possible to search for an activation key so long as either an organization
or environment ID is specified. This is easy to do:
>>> orgs = entities.Organization().search(query={'per_page': 25})
>>> for org in orgs:
...     org.id, len(entities.ActivationKey(organization=org).search())
...
(486, 1)
(743, 0)
(677, 0)
(259, 0)
(494, 0)
(291, 0)
(51, 0)
(261, 0)
(688, 0)
(227, 0)
(280, 0)
(41, 0)
(43, 0)
(672, 0)
(496, 0)
(56, 0)
(245, 0)
(181, 0)
(580, 0)
(489, 0)
(270, 0)
(179, 0)
(321, 0)
(29, 1)
(5, 0)
>>> act_key = entities.ActivationKey(organization=486).search()[0]
>>> act_key = act_key.read()
>>> type(act_key)
<class 'nailgun.entities.ActivationKey'>
> Add EntitySearchMixin to ActivationKey entity

- nailgun/entities.py
Small fix for `DockerComputeResource.read()` method.
As per [BZ](https://bugzilla.redhat.com/show_bug.cgi?id=1223540), POST and GET don't contain `email` field, so PUT is used here to do the trick.
The problem is that on upstream PUT doesn't contain `email` field too, and as we're accessing key directly, all the DockerComputeResource tests (20 of them) are failing because of missing key.
`get()` will search for key and return `None` if not found, making all the tests (except those which test `email` field) pass.
Some random test result before and after:
```
nosetests tests/foreman/api/test_docker.py -m test_create_external_docker_compute_resource
E^C
======================================================================
ERROR: @Test: Create a Docker-based Compute Resource using an …
```
> Fix DockerComputeResource.read()

- nailgun/entities.py
Docker container names must follow the following rule
`[a-zA-Z0-9][a-zA-Z0-9_.-]`, to match that, update the length of the
random generated length to have at least two characters.
Closes #228
> Change the length of AbstractDockerContainer name

- nailgun/entities.py
- tests/test_entities.py
Check for presence of `application/json` on response headers instead
equality since on the header value the charset can be specified, like
`application/json; charset=utf-8`.
> Improve _handle_response

- nailgun/entities.py
Closes #232
```
orgs = entities.Organization().search(query={'per_page': 25})
for org in orgs:
...     org.id, len(entities.ContentView(organization=org).search())
... 
(88, 1)
(16, 2)
(514, 1)
(129, 1)
(301, 1)
(3, 2)
(21, 2)
(22, 2)
(46, 1)
(118, 1)
(53, 1)
(303, 1)
(298, 1)
(12, 2)
(105, 1)
(56, 1)
(48, 1)
(30, 2)
(137, 1)
(306, 1)
(225, 1)
(62, 1)
(325, 1)
(221, 1)
(400, 1)
We have one Content View per each Organization by default ('Default Organization View')
cv = entities.ContentView(organization=30).search()[0]
cv = cv.read()
type(cv)
<class 'nailgun.entities.ContentView'>
cv.name
u'Default Organization View'
cv = entities.ContentView(organization=30).search()[1]
cv = cv.read()
type(cv)
<class 'nailgun.entities.ContentView'>
cv.name …
```
> Add search functionality to CV entity

- nailgun/entities.py
- Update list of possible OS families according to UI:
- Remove duplication of code for Media entity as it has same list of operation systems:
Verified that change works properly using `test_update_with_new_os` test from `api/test_partitiontable.py`
Corresponding update for robottelo part will be provided soon (there are no impact by any of that change, so we are free to merge current PR whenever we like)
> Update list of OS families

- nailgun/entities.py
- tests/test_entities.py
Made necessary changes for `upload_payload()` method in Media entity to have similar look as that entity has for `create_payload()` method. +Added required unit test
Tested using robottelo and functionality started to work as intended
> Fix upload_payload method for Media entity

- nailgun/entities.py
Verify that functionality really works properly:
```
>>> entities.OperatingSystem().create(create_missing=True)
nailgun.entities.OperatingSystem(nailgun.config.ServerConfig(url=u'https://cisco-c220m3-01.klab.eng.bos.redhat.com', verify=False, auth=(u'admin', u'changeme')), major=u'93', family=None, media=[], ptable=[], description=None, config_template=[], architecture=[], password_hash=u'MD5', release_name=None, id=38, minor=u'', name=u'\u07cd\u9654\U000266f9\U00023ca0\U0002aa5e\u0279\U00022d0b\U0002a3ba\u9734\U0002297c\u7e34\U0002ada4\ub096\ua186\U000250ef\u3a62\u4020\ufbf2\u9954\U00028d50\u7b82\ud2ac\ud525\ua695\u017c\u9955')
>>> entities.OperatingSystem(password_hash='SHA256').create(create_missing=True)
nailgun.entities.OperatingSystem(nailgun.config.ServerConfig(url=u'https://cisco-c …
```
> Add one more field to OS entity

- nailgun/entities.py
According to APIdoc we have `medium` field, not `media` field:
```
operatingsystem[medium_ids]  - IDs of associated media
optional , nil allowed	
```
Of course, we can add some renaming functionality to `create()` and `update()` methods, but proposed solution seems much better
Before fix:
```
>>>media = entities.Media().create(create_missing=True)
>>>entities.OperatingSystem(media=[media]).create(create_missing=True)
WARNING:nailgun.client:Received HTTP 500 response: {
"error": {"message":"unknown attribute: media_ids"}
}
File "<stdin>", line 1, in <module>
File "/home/oshtaier/Desktop/nailgun/nailgun/entity_mixins.py", line 842, in create
return self.read(attrs=self.create_json(create_missing))
File …
```
> Fix Media name field for Operating System entity

- nailgun/entities.py
- tests/test_entities.py
When it is not mandatory to wrap every attribute for update procedure, there is still some (like `family`) that need it, so overriding `update_payload` method like we usually did in similar situations
> Override update_payload for operating system entity

- requirements-dev.txt
Fix #246:
> Pylint 1.5 and astroid 1.4 have recently been released. Due to this update,
> the `make lint` target is now failing.
As a follow-up, #247 should be addressed:
> Let's make NailGun compatible with the current version of Pylint and/or work
> with the Pylint developers to fix any possible regressions in the tool.
> Use old version of Pylint

- nailgun/entities.py
```python
>>> os1 = entities.OperatingSystem(name=gen_string('alphanumeric')).create()
2015-12-07 18:14:51 - nailgun.client - DEBUG - Making HTTP POST request to https://**************************.redhat.com:443/api/v2/operatingsystems with options {'verify': False, 'auth': ('*****', '********'), 'headers': {'content-type': 'application/json'}} and data {"operatingsystem": {"major": "5", "name": "co3zQU6cUT"}}.
2015-12-07 18:14:52 - nailgun.client - DEBUG - Received HTTP 200 response: {"id":249,"name":"co3zQU6cUT","title":"co3zQU6cUT 5","description":null,"major":"5","minor":"","family":null,"release_name":null,"password_hash":"MD5","created_at":"2015-12-07T16:14:52Z","updated_at":"2015-12-07T16:14:52Z","parameters":[],"media":[],"architectures":[],"ptables":[],"config_templates":[],"os_de …
```
> Add 'title' field to OperatingSystem entity

- docs/index.rst
- nailgun/entities.py
Katello issue 4638 [1] has been resolved. As a result, the workaround for that
bug in `ActivationKey.create_raw` is no longer needed. It is possible to create
an activation key without this workaround in place:
```python
>>> from nailgun import config, entities
>>> cfg = config.ServerConfig(…)
>>> act_key = entities.ActivationKey(cfg).create(create_missing=True)
>>> act_key.id
204
```
Fix #250.
[1] http://projects.theforeman.org/issues/4638
> Drop unneeded workaround

- nailgun/entities.py
Need these fields for SatelliteQE/robottelo#3253
```python
>>> host = entities.Host()
>>> host.create_missing()
>>> proxy = entities.SmartProxy().search()[0]
>>> host.puppet_ca_proxy = proxy
>>> host.comment = gen_string('alpha')
>>> host = host.create(create_missing=False)
>>> host.comment
u'qLdBcGCdMp'
>>> host.puppet_ca_proxy.read().name
u'**************************.redhat.com'
```
> Add 2 new fields for Host entity

- nailgun/entities.py
- tests/test_entities.py
POST /api/v2/usergroups doesn't return `users`, `roles` and some other fields. Adding workaround to fetch the complete set of attributes
Before:
```python
>>> role = entities.Role().create(True)
>>> user = entities.User(
...     location=[location],
...     organization=[organization],
...     role=[role],
... ).create(True)
>>> usergroup = entities.UserGroup(
...     role=[role],
...     user=[user],
... ).create(True)
File "<stdin>", line 4, in <module>
File "nailgun/entity_mixins.py", line 842, in create
return self.read(attrs=self.create_json(create_missing))
File "nailgun/entities.py", line 4145, in read
return super(UserGroup, self).read(entity, attrs, ignore)
File "nailgun/entity_mixins.py", line 697, in read
in _get_entity_ids(field_name, attrs) …
```
> Fix Usergroup creation

- nailgun/entities.py
- tests/test_entities.py
```
>>> gpg_key = entities.GPGKey(content='test').create(create_missing=True)
>>> gpg_key.name = 'test1'
>>> gpg_key = gpg_key.update(['name'])
>>> gpg_key
nailgun.entities.GPGKey(nailgun.config.ServerConfig(url=u'https://qe-sat6iso-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), content=u'test', organization=nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://qe-sat6iso-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), id=845), id=107, name=u'test1')
```
> Add update functionality for gpg keys

- nailgun/entities.py
- tests/test_entities.py
On Satellite 6.2 the work around for the HostGroup.read is not needed
anymore. Just run the work around for Satellite 6.1.z.
> Fix HostGroup.read for Satellite 6.2

- nailgun/entities.py
The API has changed for 'Host Collection' and some attributes have
been renamed, namely `max_content_hosts` has changed to `max_hosts`
and `unlimited_content_host` to `unlimited_host`.
> Updating attributes for 'Host Collection' entity.

- nailgun/entities.py
- tests/test_entities.py
Adding location and organization fields to Partition Table entity
Please refer to https://bugzilla.redhat.com/show_bug.cgi?id=1320459 for more details
```
>>> test = entities.PartitionTable(organization=[1]).create(True)
>>> test
nailgun.entities.PartitionTable(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), layout=u'\u7abf\ufc1c\U00029f67\U00020d89\u7cbb\u0178\U00023182\U000210be\ua20d\U00022c5e\U0002766f\ucb75\U00010008\ubb7d\U00023153\U00022bbe\ufeaa\u857e\U000290e5\u5a17\U00022e79\U0002630e\u5099\U0002a0c1', os_family=None, location=[], organization=[nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'https://server', verify=False, auth=(u'admin', u'changeme')), id=1)], id=198, …
```
> Adding two more fields for partition table entity

- nailgun/entities.py
- tests/test_entities.py
```python
>>> cg = entities.ConfigGroup().create(True)
>>> cg.read()
nailgun.entities.ConfigGroup(nailgun.config.ServerConfig(url=u'https://example.com', verify=False, auth=(u'admin', u'changeme')), id=21, name=u'\U0002a628\U00022f0b\U00021064\u4c73\U00020f45\ucaac\U000247fb\U000260c3\U0002241b\ub864\U0001047f\ua560\u11ee\u8013\uc7e9\u37d1\u6ef1\U00025c53\u1610')
>>> entities.ConfigGroup(name=cg.name).search()[0]
nailgun.entities.ConfigGroup(nailgun.config.ServerConfig(url=u'https://example.com', verify=False, auth=(u'admin', u'changeme')), id=16, name=u'\U00026eb4\U000213b5\u3718')
>>> cg.name = 'test12345'
>>> cg.update(['name'])
nailgun.entities.ConfigGroup(nailgun.config.ServerConfig(url=u'https://example.com', verify=False, auth=(u'admin', u'changeme')), id=21, name=u'test12345')
```
> Add Create/Read/Search/Update mixins for ConfigGroup entity

- nailgun/entities.py
- tests/test_entities.py
1) Adding Update mixin
2) Removing `required` flag for `User` parameter as it is optional per documentation and in fact
```
>>> user_group = entities.UserGroup().create(True)
>>> user_group
nailgun.entities.UserGroup(nailgun.config.ServerConfig(url=u'https://qe-sat6-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), admin=False, role=[], user=[], usergroup=[], id=123, name=u'\u4a5b\ub4fd\U000121ff\U00028f4e\uc0c7\uaa70\U000261f2\u4b0b\U0002567a\U00026b31')
>>> user_group.name = 'test12345'
>>> user_group.update(['name'])
nailgun.entities.UserGroup(nailgun.config.ServerConfig(url=u'https://qe-sat6-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), admin=False, role=[], user=[], usergroup=[], id=123, name=u'test12345')
```
> Quick fix for UserGroup entity

- nailgun/entities.py
- tests/test_entities.py
Before fix:
```
>>> entities.Filter(permission=[1], role=1).create()
Received HTTP 500 response: {
"error": {"message":"ERROR:  operator does not exist: character varying = integer\nLINE 1: ...oles\"  WHERE ((\"roles\".\"id\" = 1 OR \"roles\".\"name\" = 1))  ORD...\n                                                             ^\nHINT:  No operator matches the given name and argument type(s). You might need to add explicit type casts.\n"}
}
File "<stdin>", line 1, in <module>
File "nailgun/entity_mixins.py", line 842, in create
return self.read(attrs=self.create_json(create_missing))
File "nailgun/entity_mixins.py", line 813, in create_json
response.raise_for_status()
File "/usr/lib/python2.7/site-packages/requests/models.py", line 837, in …
```
> Wrap POST requests for filter entity

- nailgun/entities.py
Rename uuid to puppet_module_id when reading the entity information. The same way that puppet_module_id is converted to uuid when creating, when reading, it should be converted back from uuid to puppet_module_id.
The uuid field is populated when reading when the ContentViewPuppetModule entity is created by passing the content_view_id and the puppet_module_id:
```
2016-04-11 19:00:40 - nailgun.client - DEBUG - Making HTTP POST request to https://sat62.example.com:443/katello/api/v2/content_views/345/content_view_puppet_modules with options {'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}, 'verify': False} and data {"content_view_id": 345, "uuid": 3}.
2016-04-11 19:00:41 - nailgun.client - DEBUG - Received HTTP 200 response: …
```
> Update ContentViewPuppetModule entity

- nailgun/entities.py
- tests/test_entities.py
> Deprecate the use of `entities.System` in favor of `entities.Host`

- nailgun/entities.py
- tests/test_entities.py
`content_facet_attributes` are not even documented yet :smile: , but that's the way we are supposed to associate host with content view or lifecycle environment, just like that:
```python
host = entities.Host(
content_facet_attributes={
'content_view_id': content_view.id,
'lifecycle_environment_id': lc_env.id,
},
organization=org,
).create()
```
The thing with this field is it's returned as `content`, and is only returned when it was set to some value, that's why some workarounds were added.
Some proofs it's actually working:
```python
>>> org = entities.Organization().create()
>>> lc_env = entities.LifecycleEnvironment(organization=org).create()
>>> content_view = entities.ContentView(organization=org).create()
>>> content_view.publish()
>>> content_view = content_view.read()
>>> …
```
> Added 'content_facet_attributes' field for Host entity

- nailgun/entities.py
Current version of Satellite 6 has finally renamed both attributes for
`entities.ActivationKey` to drop `content` from `max_content_hosts` and
`unlimited_content_hosts`. This changeset removes them from the class.
> Update `entities.ActivationKey` to drop `content` attribute name.

- Makefile
The `lint` make targets calls flake8 and pylint. By default, pylint uses
one CPU core. Update the make file and tell pylint to use all available
CPU cores. On the author's anemic quad-core system, `git clean -dfx &&
time make lint` reports the following times (in seconds) without this
patch:
1. 31
2. 31
3. 31
4. 31
5. 31
…and with this patch:
1. 19
2. 19
3. 18
4. 19
5. 19
> Let pylint use all CPU cores

- README.rst
- docs/examples.rst
- docs/index.rst
From an announcement sent on 2016-04-27:
> Starting today, Read the Docs will start hosting projects from
> subdomains on the domain readthedocs.io, instead of on
> readthedocs.org. This change addresses some security concerns around
> site cookies while hosting user generated data on the same domain as
> our dashboard.
> Link to readthedocs.io, not readthedocs.org

- Makefile
- release.sh
- requirements-dev.txt
The script will help on releasing NailGun to PyPI by performing a sanity check
of the generated packages and also dealing with git workflow: bump the version
number, commit with the latest changes as a shortlog and tag the new commit.
> Add release script

- nailgun/entities.py
`display_type` attribute of LibvirtComputeResource entity is now returned in lower case.
Uppercase is still accepted, but we have some tests which validate consistency between accepted & returned values.
Related robottelo PR: SatelliteQE/robottelo#3436
Test results:
```python
py.test tests/foreman/api/test_multiple_paths.py -k DoubleCheckTestCase
================================ test session starts =================================
platform linux2 -- Python 2.7.10, pytest-2.9.1, py-1.4.31, pluggy-0.3.1
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 16 items 
tests/foreman/api/test_multiple_paths.py ...
=================== 13 tests deselected by '-kDoubleCheckTestCase' ===================
===================== 3 passed, 13 deselected in …
```
> Updated `display_type` attribute of LibvirtComputeResource for GA

- nailgun/entities.py
Just an example that fix is working
```
for i in {1..10}; do py.test tests/foreman/api/test_syncplan.py -k test_positive_update_interval; done
=========================================================================== test session starts ============================================================================
platform linux2 -- Python 2.7.5, pytest-2.8.1, py-1.4.30, pluggy-0.3.1
rootdir: /home/oshtaier/Desktop/robottelo, inifile: 
collected 30 items 
tests/foreman/api/test_syncplan.py .
========================================================= 29 tests deselected by '-ktest_positive_update_interval' =========================================================
================================================================= 1 passed, 29 deselected in 12.65 seconds …
```
> Fixing sync plan update_payload to update only specific field

- nailgun/entities.py
- tests/test_entities.py
It seems that overall logic for the flow that we have for that entity has been changed and none from:
```
GET /katello/api/content_views/:content_view_id/content_view_puppet_modules
POST /katello/api/content_views/:content_view_id/content_view_puppet_modules
GET /katello/api/content_views/:content_view_id/content_view_puppet_modules/:id
PUT /katello/api/content_views/:content_view_id/content_view_puppet_modules/:id
DELETE /katello/api/content_views/:content_view_id/content_view_puppet_modules/:id
```
accept `'puppet_module': entity_fields.OneToOneField(PuppetModule)` parameter
and
`payload['uuid'] = payload.pop('puppet_module_id')` is invalid as uuid parameter has nothing in common with puppet module id
It doesn't seem that conditions mentioned in …
> Fix parameter list for content view puppet modules entity

- nailgun/entities.py
- tests/test_entities.py
Satellite is now returning the `content_facet_attributes` as
`content_facet_attributes` key and not more content.
An updated request and response to the host path can be seen below:
```
2016-05-30 09:38:26 - nailgun.client - DEBUG - Making HTTP POST request to https://10.16.4.117:443/api/v2/hosts with options {'verify': False, 'headers': {'content-type': 'application/json'}, 'auth': ('admin', 'changeme')} and data {"host": {"name": "mgcwlg", "root_pass": "\u1fba\u370c\ud853\udd58\ub1a9\ud868\udf42\ud862\ude39\ud866\uddf6\ud3b1\ud86b\uddf5\u8286\ud81a\udc97\u390e\ua444\ufab4\ud864\udd2e\ud85d\udce1\ud868\udfd6\ud85d\ude56\ud852\udca1\ud86c\udeaa\ud867\udc9c\ud867\udf2b\ud71d\ud844\ude4d\u051c\ud851\udee6\u9394\ud854\udd76", "content_facet_attributes": {"lifecycle_environment_id": 7, …
```
> Read content_facet_attributes directly

- Makefile
- docs/signals.rst
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_mixins.py
- nailgun/signals.py
- setup.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entity_mixins.py
- tests/test_signals.py
I was annoyed by the amount of **.send()** calls we added and thinking on follow the DRY concept I turned all the **.send()** calls in to a decorator.
Now whenever we want to emit a signal we just need to decorate it.
> ~~That decorator can be turned in to an opensource python library itself as a blinker plugin, as I did not found any plugin or blinker feature that does that out of the box~~  https://github.com/SatelliteQE/blinker_herald
Instead of
```python
def create(self, ...):
signals.pre_create.send(....)
...
signals.post_create.send(...)
return ...
```
Now we just need to to do
```python
@signals.emit()
def create(self, ....):
...
```
No need to change anything in method or function and the **pre** and **post** signals will be emitted.
> Checked the overhead and no significant …
> Using a decorator to emit signals "DRY"

- tests/test_entity_mixins.py
Using enumerate will make the code more cleaner and will avoid us to call two functions for retrieving the value.
It is possible to iterate a sequence by using range and len, as seen below:
```python
for index in range(len(obj)):
value = obj[index]
print(value)
```
This can be rewritten in a more Pythonic way by using the concept of iterable that Python has. If the object provides this capability, this can be rewritten more cleanly as:
```python
for value in obj:
print(value)
```
But if both the index of the value and value itself are needed, a more Pythonic way of writing an iteration, instead of using range and len, is to use the enumerate builtin, which returns an iterator of pairs, where the first item is the index and the second one is the value:
```python
for index, value in …
```
> Small fix: using enumerate instead of iterating with range and len

- nailgun/entities.py
- tests/test_entities.py
```
>>> org = entities.Organization().create(True)
>>> act_key = entities.ActivationKey(organization=org).create(True)
>>> act_key.host_collection
[]
>>> host_collection = entities.HostCollection(organization=org).create(True)
>>> act_key.add_host_collection(data={'host_collection_ids': [host_collection.id]})
>>> act_key.read().host_collection
[nailgun.entities.HostCollection(nailgun.config.ServerConfig(url=u'https://qe-sat6-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), id=71)]
>>> host_collection.id
71
>>> act_key.remove_host_collection(data={'host_collection_ids': [host_collection.id]})
>>> act_key.read().host_collection
[]
```
> Add two more helpers to activation key entity

- nailgun/entities.py
- tests/test_entities.py
```python
>>> entities.DockerRegistryContainer(
...     compute_resource=215,
...     organization=[1784],
...     registry=38,
...     repository_name='rhel',
... ).create()
nailgun.entities.DockerRegistryContainer(nailgun.config.ServerConfig(url=u'https://example.com', verify=False, auth=(u'admin', u'changeme')), tty=None, attach_stdin=None, command=None, tag=None, registry=nailgun.entities.Registry(nailgun.config.ServerConfig(url=u'https://example.com', verify=False, auth=(u'admin', u'changeme')), id=38), id=36, name=u'hopeful_babbage', cpu_set=None, repository_name=u'rhel', attach_stderr=None, compute_resource=nailgun.entities.AbstractComputeResource(nailgun.config.ServerConfig(url=u'https://example.com', verify=False, auth=(u'admin', u'changeme')), id=215), entrypoint=None, …
```
> Add DockerRegistryContainer entity

- nailgun/entities.py
Its required to create `ostree` repo via nailgun.
> Updated repo entity with ostree type content

- nailgun/entities.py
Adding newer `download_policy` field to the `Repository` entity. As per
official API documentation:
download policy for yum repos (either 'immediate', 'on_demand', or
'background')
Validations:
Must be one of: immediate, on_demand, background.
> Added 'download_policy' to `Repository` entities.

- nailgun/entities.py
The required flag for `download_policy` should only be set for `yum` type repos but not for others.
> Fixed download_policy required flag only if content_type='yum'

- nailgun/entities.py
```console
$ manage shell
In [1]: hcs = entities.HostCollection(organization=5).search(query={'search':'name=GtLsWQY'})
2016-08-19 18:20:44 - nailgun.client - DEBUG - Making HTTP GET request to https://FQDN:443/katello/api/v2/host_collections with options {'verify': False, 'data': '{"organization_id": 5, "search": "name=GtLsWQY"}', 'auth': ('admin', 'xxxxxxx'), 'headers': {'content-type': 'application/json'}} and no data.
2016-08-19 18:20:46 - nailgun.client - DEBUG - Received HTTP 200 response: {"total":13,"subtotal":1,"page":1,"per_page":20,"error":null,"search":"name=GtLsWQY","sort":{"by":null,"order":null},"results":[{"name":"GtLsWQY","organization_id":5,"max_hosts":null,"description":null,"total_hosts":0,"unlimited_hosts":true,"created_at":"2016-08-19 21:17:31 …
```
> Add EntitySearchMixin to HostCollection closes #307

- nailgun/entities.py
- tests/test_entities.py
This is my first PR for nailgun so I would be appreciate for any comments and suggestions. Especially about what unit-tests should be added.
```python
entities.SmartClassParameters().search(query={'search': 'puppetclass="ntp"', 'per_page': 100})
2016-09-02 11:15:47 - nailgun.client - DEBUG - Making HTTP GET request to https://example.com/api/v2/smart_class_parameters
2016-09-02 11:15:48 - nailgun.client - DEBUG - Received HTTP 200 response:
[nailgun.entities.SmartClassParameters(nailgun.config.ServerConfig(url='https://example.com', verify=False, auth=('admin', 'changeme')), description=None, puppetclass=nailgun.entities.PuppetClass(nailgun.config.ServerConfig(url='example.com', verify=False, auth=('admin', 'changeme')), id=12), hidden_value=u'*****', validator_type=None, id=120, …
```
> Added Smart Class Parameters entity and helpers needed for SCP.

- nailgun/entities.py
- tests/test_entities.py
```
2016-09-09 18:10:38 - nailgun.client - DEBUG - Making HTTP POST request to https://qe-sat6-rhel6.com/katello/api/v2/host_collections with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"organization_id": 21, "host_ids": [14, 15], "name": "zLSOvpHqMeR"}.
2016-09-09 18:10:39 - nailgun.client - DEBUG - Received HTTP 200 response:   {"host_ids":[14,15],"name":"zLSOvpHqMeR","organization_id":21,"max_hosts":null,"description":null,"total_hosts":2,"unlimited_hosts":true,"created_at":"2016-09-09 16:10:38 UTC","updated_at":"2016-09-09 16:10:38 UTC","id":7,"permissions":{"deletable":true,"editable":true}}
```
We probably want to backport this to `6.2.z` too
> [needs cherrypick to 6.2.z] removing workaround for BZ#1325989 after it has been resolved

- nailgun/entities.py
- tests/test_entities.py
```python
hostgroup = entities.HostGroup().create()
hostgroup.add_puppetclass(data={'puppetclass_id': puppet.id})
hostgroup.list_smart_variables()
016-09-14 10:32:04 - nailgun.client - DEBUG - Making HTTP GET request to https://example.com/api/v2/hostgroups/14/smart_variables with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
2016-09-14 10:32:05 - nailgun.client - DEBUG - Received HTTP 200 response: {
"total": 190,
"subtotal": 190,
"page": 1,
"per_page": 20,
"search": null,
"sort": {
"by": null,
"order": null
},
"results": [{"description":null,"parameter_type":null,"default_value":"example","hidden_value?":false,"hidden_value":"*****","validator_type":"list","validator_rule":"test, example, …
```
> Add Smart Variables helpers

- nailgun/entities.py
- tests/test_entities.py
```python
hostgroup.delete_puppetclass(data={'puppetclass_id': puppet.id})
DEBUG - Making HTTP DELETE request to https://example.com/api/v2/puppetclasses/429 with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
DEBUG - Received HTTP 200 response: {"id":429,"name":"firewall","created_at":"2016-09-28T15:47:40.960Z","updated_at":"2016-09-28T15:47:40.960Z"}
```
> Add puppet class helpers

- nailgun/entities.py
- tests/test_entities.py
```
>>> hg = entities.HostGroup().create()
>>> newHg = entities.HostGroup(id=hg.id).clone(data={u'name':'cloned'})
>>> newHg['name']
u'cloned'
```
> added helpers for hostgroup clone, fixes #318

- nailgun/entities.py
```python
> scp_list = entities.SmartClassParameters().search(query={'search': 'puppetclass="ntp"'})
> print scp_list[0].parameter
u'authprov'
```
> Add smart class parameter name field ('parameter')

- nailgun/entities.py
Adding newer `download_policy` field to the `Repository` entity. As per
official API documentation:
download policy for yum repos (either 'immediate', 'on_demand', or
'background')
Validations:
Must be one of: immediate, on_demand, background.
> CherPick to 6.2.z - adding 'download_policy' to `Repository` entities

- nailgun/entities.py
cherry-picking: https://github.com/SatelliteQE/nailgun/pull/309
before
```bash
2016-10-25 10:42:38 - nailgun.client - DEBUG - Making HTTP POST request to https://sat6.com/katello/api/v2/repositories with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"product_id": 2, "url": "http://davidd.fedorapeople.org/repos/random_puppet/", "download_policy": "immediate", "content_type": "puppet", "name": "BPoKqNJKzmC"}.
2016-10-25 10:42:39 - nailgun.client - WARNING - Received HTTP 422 response: {"displayMessage":"Validation failed: Download policy cannot be set for non-yum repositories.","errors":{"download_policy":["cannot be set for non-yum repositories."]}}
E
====================================================================== …
```
> [6.2.z] Fixed download_policy required flag only if content_type='yum' (#309)

- docs/examples.rst
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
close #323
Once the methods uses _payload, some Entities maybe need
override this to match names expected on API
I followed @elyezer tip and made a this POC that worked for simple properties: https://github.com/renzon/nailgun/commit/d092468853d49239fa909ceba1da8af0e3271ba0.
The problem is when the default naming mapping is not correct with the expected for API. But in this case Subclasses can override _to_json_dict for the exceptions.
@ehelms and @rochacbruno could give it a try to check exceptions as they use it and creating issues here for them. What you guys think?
> Added json method to Entity

- nailgun/entities.py
```console
In [5]: hg = HostGroup(server_config, name='testpass14', root_pass='test@1234').create()
In [6]: hg
Out[6]: nailgun.entities.HostGroup(nailgun.config.ServerConfig(url='SERVER', verify=False, auth=('admin', 'changeme')), domain=None, medium=None, parent=None, ptable=None, content_source=None, lifecycle_environment=None, operatingsystem=None, name=u'testpass14', subnet=None, puppet_proxy=None, realm=None, content_view=None, id=46, environment=None, location=[], organization=[], puppet_ca_proxy=None, architecture=None)
```
> Added a new field root_pass to hostgroup entity

- nailgun/entities.py
It doesn't seem that we add entities with required parameters to unit tests when adding new mixins to them.
```
>>> cvf_rule = entities.ContentViewFilterRule(id=1, content_view_filter=5).read()
>>> cvf_rule
nailgun.entities.ContentViewFilterRule(nailgun.config.ServerConfig(url=u'server', verify=False, auth=(u'admin', u'changeme')), id=1, types=[u'bugfix'], content_view_filter=nailgun.entities.AbstractContentViewFilter(nailgun.config.ServerConfig(url=u'server', verify=False, auth=(u'admin', u'changeme')), id=5))
>>> cvf_rule.types = ['enhancement']
>>> cvf_rule = cvf_rule.update(['types'])
>>> cvf_rule
nailgun.entities.ContentViewFilterRule(nailgun.config.ServerConfig(url=u'server', verify=False, auth=(u'admin', u'changeme')), id=1, types=[u'enhancement'], …
```
> Add UpdateMixin for CV Filter Rules entity

- nailgun/entities.py
```
>>> cv = entities.ContentView(name='test', organization=22).create()
>>> cv
nailgun.entities.ContentView(nailgun.config.ServerConfig(url=u'server', verify=False, auth=(u'admin', u'changeme')), puppet_module=[], last_published=None, repository=[], composite=False, component=[], id=41, next_version=1, name=u'test', description=None, label=u'test', version=[], content_host_count=0, organization=nailgun.entities.Organization(nailgun.config.ServerConfig(url=u'server', verify=False, auth=(u'admin', u'changeme')), id=22))
```
> Add host count field to CV entity

- tests/test_entities.py
@abalakh @oshtaier : Please see if changes in this PR addresses the comment given on https://github.com/SatelliteQE/nailgun/pull/336#issuecomment-265119909
> Updated test for root_pass from hostgroup entity

- nailgun/entities.py
fixes #332 
Results:
```python
>>> from nailgun.entities import HostGroup, Environment, ConfigTemplate, TemplateCombination
>>> cfg = ServerConfig('https://foo.bar', 
...                    auth=('baz', '****'), verify=False)
>>> def creat_ent(cls, **kwargs):
...     return cls(cfg, **kwargs)
>>> hostgroup=creat_ent(HostGroup, name='group').create()
>>> env=creat_ent(Environment, name='env').create()
>>> config_template=creat_ent(
...     ConfigTemplate,snippet=False,name='comb',template='cat', template_kind=8,
...     template_combinations=[{'hostgroup_id': hostgroup.id, 'environment_id': env.id}]
... ).create()
>>> combination_dct=config_template.template_combinations[0]
>>> combination_dct
{u'environment_id': 6, u'provisioning_template_name': …
```
> api fixed and methods GET and DELETED added for TemplateCombination

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
> Implemented Entity __eq__ method comparing all fields

- nailgun/entities.py
- tests/test_entities.py
Looks like that field `host[puppet_class_id]` was changed to `host[puppetclass_ids]`, so currently passing `puppet_class` does nothing when creating/updating host.
```python
puppet_classes = entities.PuppetClass().search(query={
'search': u'name ~ "generic_1" and environment = "KT_kWtydc_Library_nbVyItrg_60"'})
2016-12-23 00:31:09 - nailgun.client - DEBUG - Making HTTP GET request to https://sat6.com/api/v2/puppetclasses with options {'verify': False, 'data': '{"search": "name ~ \\"generic_1\\" and environment = \\"KT_kWtydc_Library_nbVyItrg_60\\""}', 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
2016-12-23 00:31:10 - nailgun.client - DEBUG - Received HTTP 200 response: {
"results": {"generic_1":[{"id":24,"name":"generic_1","created_at":"2016- …
```
> Update Host.puppet_class field name.

- nailgun/entities.py
- tests/test_entities.py
Cherry-picked from #346
Verified on 6.2.7
```python
host = entities.Host(
organization=self.org,
location=self.loc,
environment=self.env,
puppetclass=self.puppet_classes,
).create()
2017-01-17 09:28:20 - nailgun.client - DEBUG - Making HTTP POST request to https://sat6.com/api/v2/hosts with ... and data {"host": {..., "puppetclass_ids": [15]}}.
2017-01-17 09:28:21 - nailgun.client - DEBUG - Received HTTP 201 response: {...,"puppetclasses":[{"id":15,"name":"generic_1","module_name":"generic_1"}], ...}}
```
> [6.2.z] Cherry-pick - Update Host.puppet_class field name. (#346)

- nailgun/entities.py
Resolves #279 
Issue is pretty old, i'd even think of removing such workaround, but just in case somebody is using sat6.1 with latest nailgun - fix is very trivial.
> Fix read() of hostgroup without content_source, lce or cv for sat6.1

- nailgun/entities.py
Default value for timeout is 5 minutes. Subscription upload takes more
time and as an exclusion has timeout of 15 minutes.
Automation results uncovered manifest delete/refresh commands take
pretty much comparable with upload amount of time (latest run shows
they took ~7 mins), which causes failures.
Updating timeout for manifest delete/refresh to match upload, hopefully
this will help us to get rid of constant subscription test failures.
Test results:
```python
py.test tests/foreman/api/test_subscription.py -k 'delete or refresh'
============================= test session starts ==============================
platform linux2 -- Python 2.7.10, pytest-3.0.3, py-1.4.31, pluggy-0.4.0
rootdir: /home/andrii/workspace/robottelo, inifile: 
plugins: xdist-1.13.1, repeat-0.2
collected 4 items …
```
> Increase timeout for manifest delete/refresh

- nailgun/entities.py
- tests/test_entities.py
Cherry-picked from #347 
Update: looks like it was not enough only to add mixins to `Image`, its behavior was not correct.
Update 2: Also it requires changes in `Host` class.
> [6.2.z] Update Image and Host entities

- nailgun/entities.py
Default value for timeout is 5 minutes. Subscription upload takes more
time and as an exclusion has timeout of 15 minutes.
Automation results uncovered manifest delete/refresh commands take
pretty much comparable with upload amount of time (latest run shows
they took ~7 mins), which causes failures.
Updating timeout for manifest delete/refresh to match upload, hopefully
this will help us to get rid of constant subscription test failures.
> [Cherry-pick][6.2.z] Increase timeout for manifest delete/refresh (#359)

- nailgun/entities.py
- tests/test_entities.py
Bug [1] that required changes in `read` method for `SmartVariable` is fixed.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1375881
> Removed overriden read method for Smart Variable

- nailgun/entities.py
```console
/home/dlezz/bin/redhat/6.2.z/python/2.7/bin/python2.7 /home/dlezz/bin/pycharm-2016.3/helpers/pydev/pydevconsole.py 44384 40530
PyDev console: starting.
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/dlezz/projects/nailgun'])
Python 2.7.12 (default, Oct 11 2016, 17:04:14) 
[GCC 4.8.4] on linux2
from nailgun import entities
from nailgun.config import ServerConfig
server_config = ServerConfig(
auth=('admin', 'changeme'),
url='server-host-masked',
verify=False
)
org = entities.Organization(server_config, name='htttttt').create()
hc = entities.HostCollection(server_config, organization=org, name='ht_host').create()
hc_list = entities.HostCollection(server_config, organization=org).search()
len(hc_list)
1
type(hc_list[0])
<class …
```
> [Cherry-pick][6.2.z] Add EntitySearchMixin to HostCollection

- nailgun/entities.py
Default name length for `AbstractComputeResource` (and subentities like LibvirtComputeResource) was not set, which can lead to entities with one character in name being created, which in rare cases (like latest automation run 😄 ) can attempt to create 2 entities with the same name (the longer name is, the less is the chance of the same name generation).
Also removing `cjk` from the tuple of acceptable string types as it creates issues with readability and basically increases efforts for debugging.
This PR should have been implemented as a part of #290
> Provide default name length & type for ComputeResource entities

- nailgun/entities.py
> [6.2.z] [Cherry-pick] Provide default name length & type for ComputeResource entities (#369)

- nailgun/entities.py
> [6.1.z] [Cherry-pick] Provide default name length & type for ComputeResource entities (#369)

- nailgun/entities.py
- tests/test_entities.py
* Implemented Interface entity (as before it was basically a stub with
no available operations and even wrong path)
* Added all possible fields variations
* Implemented unit tests
Key features:
* Interface requires a host id in its path, so some additional logic
was required for initialization, `read()` and `search()`
* Set of available Interface fields depends on Interface's ``type``
(some fields are only returned for specific type), extra logic was
requred here too
> Implemented Interface entity with all its fields and basic operations

- nailgun/entities.py
- tests/test_entities.py
`Config Template` entity now is deprecated and it is just an alias for `Provisioning Template`, so rename should be enough.
Probably same change should be made for 6.2 as well.
> Add ProvisioningTemplate.

- nailgun/entities.py
```python
Making HTTP PUT request to https://sat6.com/api/v2/config_templates/73 with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"config_template": {"operatingsystem_ids": [5, 5, 5]}}.
Received HTTP 200 response: [... skipped ...]
```
> Fix update_payload method for ConfigTemplate/ProvisioningTemplate

- nailgun/entities.py
- tests/test_entities.py
(cherry picked from commit 12875cacfe2af68e55e504cd6ac004a61c2dab17)
> Cherry-picked from master [Added a new field root_pass to hostgroup entity (#336)]

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Please see #378 for more details 
In [2]: entities.Host().create(True)
Out[2]: nailgun.entities.Host(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), comment=None, domain=nailgun.entities.Domain(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=7), managed=True, ip=None, image=None, provision_method=u'build', hostgroup=None, owner=nailgun.entities.User(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.subdomains.com', verify=False, auth=(u'admin', u'password')), id=3), operatingsystem=nailgun.entities.OperatingSystem(nailgun.config.ServerConfig(url=u'https://very-long-server-name.here.with.sub …
> Drop ServerConfig from Entity's __repr__

- nailgun/entities.py
- tests/test_entities.py
Basically wanted to introduce `ActivationKey.product_content()` helper but found out that Subscription entity is implemented with numerous incorrect field names and outdated workarounds. None of our tests use `Subscription().read()` as apparently it was failing (`Subscription().read_json()` is used instead).
```python
In [3]: entities.Subscription(id=28).read()
Out[3]: nailgun.entities.Subscription(nailgun.config.ServerConfig(url='https://example.redhat.com', verify=False, auth=('admin', 'changeme')), activation_key=[nailgun.entities.ActivationKey(nailgun.config.ServerConfig(url='https://example.redhat.com', verify=False, auth=('admin', 'changeme')), id=10)], system=[], name=u'Red Hat Enterprise Linux Server, Premium (Physical or Virtual Nodes)', …
```
> Fix Subscription entity and add ActivationKey.product_content helper

- nailgun/entities.py
- tests/test_entities.py
Cherry-picked from #334, #342, #365, #366, #380
Results for 6.2.8:
#334 / Create:
```python
>>> env=entities.Environment(name='env2').create()
>>> hostgroup=entities.HostGroup(name='hgroup2').create()
>>> combination=entities.TemplateCombination(hostgroup=hostgroup, environment=env)
>>> cfg_template=entities.ConfigTemplate(
name='cfg2', snippet=False,
template='cat', template_kind=8,
template_combinations=[combination]
)
>>> cfg_template.create()
>>> print(cfg_template.template_combinations)
[nailgun.entities.TemplateCombination(..., environment=nailgun.entities.Environment(..., name=u'env2', organization=[], id=80, location=[]), hostgroup=nailgun.entities.HostGroup(...), domain=None, medium=None, parent=None, ptable=None, content_source=None, lifecycle_environment=None, …
```
> [6.2.z] Cherry-pick changes related to ConfigTemplates/ProvisioningTemplates

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Cherry-pick of #384 
Part of #378 
```python
In [2]: entities.Organization(id=1).read()
Out[2]: nailgun.entities.Organization(domain=[], description=None, default_content_view=nailgun.entities.ContentView(id=1), library=nailgun.entities.LifecycleEnvironment(id=1), user=[], id=1, name=u'Default Organization', subnet=[], title=u'Default Organization', smart_proxy=[nailgun.entities.SmartProxy(id=1)], hostgroup=[], label=u'Default_Organization', environment=[], config_template=[nailgun.entities.ConfigTemplate(id=7), nailgun.entities.ConfigTemplate(id=8), nailgun.entities.ConfigTemplate(id=9), nailgun.entities.ConfigTemplate(id=41), nailgun.entities.ConfigTemplate(id=10), nailgun.entities.ConfigTemplate(id=11), nailgun.entities.ConfigTemplate(id=14), nailgun.entities.ConfigTemplate(id=13), …
```
> [6.2.z][Cherry-pick] Dropped ServerConfig from Entity's __repr__

- nailgun/entities.py
- tests/test_entities.py
Cherry-pick of #385 
* Fixed Subscription entity and added ActivationKey.product_content helper
* Removed not used import and outdated tests
* Improved coverage
```python
In [6]: entities.Subscription(id=27).read()
Out[6]: nailgun.entities.Subscription(nailgun.config.ServerConfig(url=u'http://example.com', verify=False, auth=(u'admin', u'changeme')), activation_key=[], system=[], name=u'Red Hat Enterprise Linux for Virtual Datacenters, Premium', provided_product=[nailgun.entities.Product(nailgun.config.ServerConfig(url=u'http://example.com', verify=False, auth=(u'admin', u'changeme')), id=116), nailgun.entities.Product(nailgun.config.ServerConfig(url=u'http://example.com', verify=False, auth=(u'admin', u'changeme')), id=118), nailgun.entities.Product(nailgun.config.ServerConfig(url=u'http: …
```
> [6.2.z][Cherry-pick] Fix Subscription entity and add ActivationKey.product_content helper

- nailgun/entities.py
Regression added in #382. Original idea of that change was to remove `ConfigTemplate` as deprecated and use new `ProvisioningTemplate` instead. But later it was decided to keep `ConfigTemplate` as it is still supported. Robottelo tests continue using `ConfigTemplate` entities for fields where ProvisioningTemplate` object is expected and that's cause failures.
This change can be reverted later in scope of #375 (should be done on both nailgun and robottelo sides).
> [6.2.z] Use entities.ConfigTemplate for 'config_template' fields.

- nailgun/entities.py
Cherry-picked from #394. Change is quite easy so cherry-picking it immediately.
Description copy:
> Regression added in #382. Original idea of that change was to remove ConfigTemplate as deprecated and use new ProvisioningTemplate instead. But later it was decided to keep ConfigTemplate as it is still supported. Robottelo tests continue using ConfigTemplate entities for fields where ProvisioningTemplate` object is expected and that's cause failures.
> This change can be reverted later in scope of #375 (should be done on both nailgun and robottelo sides).
> [6.3] [Cherry-pick] Use entities.ConfigTemplate for 'config_template' fields.

- nailgun/entities.py
- tests/test_entities.py
Cherry-pick of #396 
```python
In [3]: entities.Capsule(id=1).read()
Out[3]: nailgun.entities.Capsule(url=u'https://example.com:9090', name=u'example.com', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=18), nailgun.entities.Organization(id=21), nailgun.entities.Organization(id=12), nailgun.entities.Organization(id=15), nailgun.entities.Organization(id=1), nailgun.entities.Organization(id=19), nailgun.entities.Organization(id=14), nailgun.entities.Organization(id=11), nailgun.entities.Organization(id=20), nailgun.entities.Organization(id=23), nailgun.entities.Organization(id=17), nailgun.entities.Organization(id=3), nailgun.entities.Organization(id=16), nailgun.entities.Organization(id=4), nailgun.entities.Organization(id=9), …
```
> [Cherry-pick] Added Capsule entity and its helpers (#396)

- nailgun/entities.py
- tests/test_entities.py
Inspired by @abalakh comment in https://github.com/SatelliteQE/robottelo/pull/4458#issuecomment-287330692
`Host`'s `create_missing` helper tried to access to some fields inside nested entities without checking whether these fields actually present. And they don't when passing `id` to `Host` instead of `Entity` object obtained by `read`, so additional read is necessary. 
Before:
```python
In [4]: entities.Host(config, environment=1).create(create_missing=True)
AttributeError: 'Environment' object has no attribute 'location'
In [5]: entities.Host(config, domain=1).create(create_missing=True)
AttributeError: 'Domain' object has no attribute 'location'
In [6]: entities.Host(config, operatingsystem=1).create(create_missing=True)
AttributeError: 'OperatingSystem' object has no attribute …
```
> Update Host.create_missing with additional reads.

- nailgun/entities.py
- tests/test_entities.py
`POST` request doesn't return `host_parameters_attributes` nor `parameters`. `GET` request still returns `parameters` instead of `host_parameters_attributes`. So workaround for the second problem should not just rename field but also check that it exists. Also additional read is required to obtain all parameters.
```python
host = entities.Host(host_parameters_attributes=parameters).create()
self.assertEqual(host.host_parameters_attributes[0]['name'], parameters[0]['name'])
self.assertEqual(host.host_parameters_attributes[0]['value'], parameters[0]['value'])
=================== 1 passed, 69 deselected in 67.52 seconds ===================
```
```
2017-05-08 17:51:18 - nailgun.client - DEBUG - Making HTTP POST request to https://sat6.com/api/v2/hosts with options {'verify': False, 'auth': …
```
> Update Host.read to check if host_parameters_attributes really was sent

- nailgun/entities.py
- tests/test_entities.py
Unit test is removed as it checks specific cases for Sat 6.0.8 and 6.1.0 but now branch separation method is used for different versions.
Quick example from the in-progress robottelo test:
```python
hg = entities.HostGroup(
organization=[org],
content_view=content_view,
kickstart_repository=repo_id,
lifecycle_environment=content_view.environment[0].read(),
content_source=1,
architecture=entities.Architecture().search(query={'search': 'name=x86_64'})[0],
operatingsystem=entities.OperatingSystem().search(query={'search': 'name=RedHat 7.0'})[0],
).create()
```
```
2017-05-12 15:21:13 - nailgun.client - DEBUG - Making HTTP POST request to https://sat6.com/api/v2/hostgroups with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data …
```
> Add some missing fields to the HostGroup and ContentView entities

- nailgun/entities.py
```python
In [2]: from nailgun import entities
In [3]: repo = entities.Repository(mirr
...: or_on_sync=True).create(True)
In [4]: repo.mirror_on_sync
Out[4]: True
```
> [6.2.z] Added 'mirror_on_sync' field to Repository entity

- nailgun/entities.py
- tests/test_entities.py
Changes:
* `use_puppet_default` now is deprecated, `omit` should be used
* `hidden_value` now is used only to set boolean flag and `hidden_value?` is used to read it back, so `hidden_value` is missing in POST/GET response and should be ignored. Actual value now can be read from `default_value` instead of `hidden_value`: `u'*****'` when using GET without parameters and actual value when using GET with `show_hidden` parameter.
```
In [9]: entities.SmartVariable(server_config, puppetclass=10, variable='123', default_value='123', hidden_value=True).create()
Out[9]: nailgun.entities.SmartVariable(merge_overrides=False, override_value_order=u'fqdn\nhostgroup\nos\ndomain', puppetclass=nailgun.entities.PuppetClass(id=10), override_values=[], validator_type=None, variable=u'123', id=3072, …
```
> Update SmartClassParameters and SmartVariables entities

- nailgun/entities.py
```python
In [5]: entities.ContentViewFilterRule(content_view_filter=109, date_type='issue
...: d', end_date='2017-06-26', start_date='2017-06-21').create()
2017-06-21 17:26:06 - nailgun.client - DEBUG - Making HTTP POST request to https://example.com/katello/api/v2/content_view_filters/109/rules with options {'verify': False, 'auth': ('admin', '*********'), 'headers': {'content-type': 'application/json'}} and data {"end_date": "2017-06-26", "content_view_filter_id": 109, "date_type": "issued", "start_date": "2017-06-21"}.
2017-06-21 17:26:07 - nailgun.client - DEBUG - Received HTTP 200 response:   {"content_view_filter_id":109,"start_date":"2017-06-21","end_date":"2017-06-26","types":["bugfix","enhancement","security"],"date_type":"issued","id":18,"created_at":"2017-06-21 14:26:07 …
```
> Added `date_type` field to ContentViewFilterRule entity and updated default login for User

- nailgun/entities.py
- tests/test_entities.py
For example:
```python
activation_key = ActivationKey(self._server_config, id=3)
subs = activation_key.subscriptions() # {... u'product_name': u'Employee SKU', u'instance_multiplier': 1, u'stacking_id': None, u'account_number': 1212729, u'cores': None, u'quantity': 5}], u'error': None, u'per_page': 20, u'organization': {}, u'total': 2, u'subtotal': 2, u'page': 1}
activation_key.remove_subscriptions(data={'subscription_id': subs['results'][0]['id']})
```
> Allow getting and deleting AK subscriptions

- nailgun/client.py
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Update `read` method to accept `params` and send it to `requests.get`, allows passing parameters in URLs.
```
In [7]: entities.SmartVariable(server_config, id=28).read()
Out[7]: nailgun.entities.SmartVariable(merge_overrides=False, override_value_order=u'fqdn\nhostgroup\nos\ndomain', puppetclass=nailgun.entities.PuppetClass(id=1), override_values=[], validator_type=None, variable=u'\u4498\ubae1\U000239ee\U00023218', id=28, description=None, default_value=u'*****', validator_rule=None, avoid_duplicates=False, merge_default=False, variable_type=None, hidden_value?=True)
In [8]: getattr(entities.SmartVariable(server_config, id=28).read(), 'hidden_value?')
Out[8]: True
In [5]: entities.SmartVariable(server_config, id=28).read(params={'show_hidden': 'true'})
Out[5]: …
```
> Update read method to accept params

- nailgun/entity_mixins.py
This format of attrs currently breaks the `_get_entity_id` function:
Check out the example inputs to this function below (unnecessary data left out with '...').
```python
field_name = 'sync_plan'
attrs = {..., u'sync_plan_id': 10, ..., u'sync_plan': {u'name': u'Weekly RHEL Sync', u'interval': u'weekly', u'sync_date': u'2017-01-01 00:00:00 UTC', u'next_sync': None, u'description': None}, ...}
```
Note the absence of `attrs['sync_plan']['id']`
> Check for r[field + '_id'] if not 'id' in r[field]

- nailgun/entities.py
Needed for enhancing robottelo syncplan tests
> In [8]: repo.read()
> Out[8]: nailgun.entities.Repository(product=nailgun.entities.Product(id=3), gpg_key=None, name=u'lswliVTpzf', mirror_on_sync=True, content_counts={u'puppet_module': 0, u'erratum': 0, u'package': 0, u'docker_manifest': 0, u'ostree_branch': 0, u'package_group': 0, u'file': 0, u'docker_tag': 0, u'rpm': 0}, unprotected=True, content_type=u'yum', label=u'lswliVTpzf', id=5, container_repository_name=None, docker_upstream_name=None, url=u'...', **last_sync=None**, download_policy=u'on_demand', checksum_type=None)
> In [9]: repo.sync()
>In [10]: repo.read()
>Out[10]:` nailgun.entities.Repository(product=nailgun.entities.Product(id=3), gpg_key=None, name=u'GHrRpq', mirror_on_sync=True, content_counts={u'puppet_module': 0, …
> last_sync added to repo read output

- nailgun/entities.py
Cherry pick of #425 
> repo.read()
> Out[8]: nailgun.entities.Repository(product=nailgun.entities.Product(id=5), gpg_key=None, name=u'shxCnQlZISbz', mirror_on_sync=True, content_counts={u'puppet_module': 0, u'erratum': 0, u'package': 0, u'docker_manifest': 0, u'ostree_branch': 0, u'package_group': 0, u'file': 0, u'docker_tag': 0, u'rpm': 0}, unprotected=True, content_type=u'yum', label=u'shxCnQlZISbz', id=7, container_repository_name=None, docker_upstream_name=None, url=u'...', **last_sync=None**, download_policy=u'on_demand', checksum_type=None)
> repo.sync()
> repo.read()
> nailgun.entities.Repository(product=nailgun.entities.Product(id=5), gpg_key=None, name=u'shxCnQlZISbz', mirror_on_sync=True, content_counts={u'puppet_module': 0, u'erratum': 4, u'package': 32, u'docker_manifest': 0, …
> [6.2.z] cherry-pick last_sync added to repo read output

- nailgun/entities.py
- tests/test_entities.py
This allows setting the Red Hat Repository URL (i.e. https://cdn.redhat.com) to an alternate provider (i.e. another katello server or CDN).
> Add RH repository URL to Organization

- nailgun/entities.py
tested with robottelo subscription tests
```console
(sat-6.3.0) dlezz@elysion:~/projects/robottelo-fork$ py.test -v tests/foreman/api/test_subscription.py
================================================= test session starts ==================================================
platform linux2 -- Python 2.7.13, pytest-3.1.3, py-1.4.34, pluggy-0.4.0 -- /home/dlezz/.pyenv/versions/sat-6.3.0/bin/python2.7
cachedir: .cache
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.15.0, services-1.2.1, mock-1.6.0, cov-2.4.0
collected 4 items 
2017-08-03 15:49:49 - conftest - DEBUG - Found WONTFIX in decorated tests ['1147100', '1269208', '1269196', '1378009', '1245334', '1217635', '1226425', '1156555', '1199150', '1204686', '1267224', '1221971', '1103157', '1230902', '1230865', …
```
> Increase manifest functions timeout

- nailgun/entities.py
- tests/test_entities.py
Organization/location fields were missing from Registry entity. But POST request does not return org/loc information, so additional read is needed after create/update [1]. And password is missing from GET response.
[1] https://bugzilla.redhat.com/show_bug.cgi?id=1479391
```python
In [6]: entities.Registry(server_config, url='https://registry.access.redhat.com').create(create_missing=True)
Out[6]: nailgun.entities.Registry(username=None, url=u'https://registry.access.redhat.com', description=None, organization=[], id=18, name=u'ZTBnuuXFJj')
In [7]: entities.Registry(server_config, id=18).delete()
Out[7]: 
{u'created_at': u'2017-08-08T13:40:03.199Z',
u'description': None,
u'id': 18,
u'name': u'ZTBnuuXFJj',
u'password': None,
u'updated_at': u'2017-08-08T13:40:03.199Z',
u'url': …
```
> Update Registry entity / add organization/location fields.

- nailgun/entities.py
```python
In [4]: org = entities.Organization(conf).create(create_missing=True)
In [5]: product = entities.Product(conf, organization=org).create(create_missing=True)
In [6]: repo = entities.Repository(conf, product=product).create(create_missing=True)
In [7]: repo
Out[7]: nailgun.entities.Repository(product=nailgun.entities.Product(id=489), gpg_key=None, mirror_on_sync=True, content_counts={u'puppet_module': 0, u'erratum': 0, u'package': 0, u'docker_manifest': 0, u'ostree_branch': 0, u'package_group': 0, u'file': 0, u'docker_tag': 0, u'rpm': 0}, unprotected=True, content_type=u'yum', label=u'OZUCVndBADM', id=109, name=u'OZUCVndBADM', docker_upstream_name=None, url=u'http://inecas.fedorapeople.org/fakerepos/zoo3/', last_sync=None, download_policy=u'on_demand', …
```
> repository add backend identifier field

- nailgun/entities.py
- tests/test_entities.py
```
aud = entities.Audit(id=1889).read()
2017-09-15 04:27:55 - nailgun.client - DEBUG - Making HTTP GET request to https://server/api/v2/audits/1889 with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}}, no params and no data.
2017-09-15 04:27:56 - nailgun.client - DEBUG - Received HTTP 200 response: {"user_id":3,"user_type":null,"user_name":"admin","version":1,"comment":null,"associated_id":null,"associated_type":null,"remote_address":"10.8.183.246","associated_name":null,"created_at":"2017-09-14 08:02:36 UTC","id":1889,"auditable_id":375,"auditable_name":"HBkSxQ","auditable_type":"Organization","action":"create","audited_changes":{"name":"HBkSxQ","ignore_types":[],"description":"stYWZdGzbCBByJq","label":"YAJBwmpaky","ancestry":null …
```
> Add Audit entity

- nailgun/entities.py
```console
In[9]: ak = entities.ActivationKey(server_config, service_level='Premium').create(create_missing=True)
In[10]: ak.read()
Out[10]: nailgun.entities.ActivationKey(host_collection=[], service_level=None, max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, organization=nailgun.entities.Organization(id=105), id=65, name=u'ZYbPnwr')
In[11]: ak.service_level
Out[11]: u'Premium'
In[12]: ak2 = entities.ActivationKey(server_config).create(create_missing=True)
In[13]: ak2.service_level
In[14]: ak2.read()
Out[14]: nailgun.entities.ActivationKey(host_collection=[], service_level=None, max_hosts=None, content_view=None, description=None, unlimited_hosts=True, environment=None, auto_attach=True, …
```
> Add ActivationKey service_level field

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
sometimes DELETE returns HTTP 200 with an empty response, but it's not
really empty, but contains only a blank. strip that blank and accept
this response as empty, not trying to parse JSON from it
> allow DELETE responses with a single blank

- release.sh
Allow the script to accept an optional argument which will be the
version that should be released when specified.
> Improve release.sh script

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
```python
In [4]: entities.Host(id=46).read().all_parameters
Out[4]:
[{u'created_at': u'2017-09-21 16:13:39 UTC',
u'id': 52,
u'name': u'qfjO9vcs69',
u'priority': 20,
u'updated_at': u'2017-09-21 16:13:39 UTC',
u'value': u'WN35rcRpbQ'},
{u'created_at': u'2017-09-21 16:13:16 UTC',
u'id': 51,
u'name': u'4ZRqG21c79',
u'priority': 10,
u'updated_at': u'2017-09-21 16:13:16 UTC',
u'value': u'tU0wjkFVqP'}]
In [5]: entities.Parameter(id=51, organization=126).read()
Out[5]: nailgun.entities.Parameter(value=u'tU0wjkFVqP', priority=10, organization=nailgun.entities.Organization(id=126), id=51, name=u'4ZRqG21c79')
In [9]: entities.Parameter(id=51, organization=126, name='foo', value='bar').cre
...: ate()
Out[9]: nailgun.entities.Parameter(value=u'bar', priority=10, …
```
> Added Parameter entity and Host.all_parameters field

- nailgun/entities.py
- tests/test_entities.py
@philippj implemented these two entities within https://github.com/theforeman/foreman-ansible-modules/pull/26
But we think they could be of broader interest.
> Add tangible ComputeResource entities for vmware and ovirt

- nailgun/entities.py
- tests/test_entities.py
```console
In[2]: from nailgun.config import ServerConfig
In[3]: from nailgun import entities 
In[4]: conf = ServerConfig(url='https://XXXXXXXXXXXXXXXXXXX', auth=('XXX', 'XXX'), verify=False)
In[5]: org = entities.Organization(server_config=conf)
In[6]: org.create_missing()
In[7]: org = org.create()
In[8]: host = entities.Host(conf, organization=org)
In[9]: host.create_missing()
In[10]: host = host.create()
In[11]: host_enc = host.enc()
In[12]: host_enc
Out[12]: 
{u'data': {u'classes': {},
u'environment': u'i3MPBuq5OQ',
u'parameters': {u'content_view': None,
u'content_view_info': {u'components': {},
u'label': None,
u'latest-version': None,
u'published': None,
u'version': None},
u'domainname': u'6wx8mer5qj',
u'foreman_config_groups': [],
u'foreman_env': u'i3MPBuq5OQ', …
```
> Host read ENC information

- nailgun/entities.py
- tests/test_entities.py
Since errata and packages installations can't be done 1-linear easily, pls refer to SatelliteQE/robottelo#5575 to see test results. Results of calling `errata_apply()` and `install_content()` in robottelo.log:
<details>
<summary>robottelo.log</summary>
```
2017-11-14 19:05:47 - nailgun.client - DEBUG - Making HTTP PUT request to https://example.com/api/v2/hosts/5/errata/apply with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"errata_ids": ["RHEA-2012:0056"]}.
2017-11-14 19:05:48 - nailgun.client - DEBUG - Received HTTP 202 response:   {"id":"54ee31a3-ab4a-41d2-9411-891a8ee123f9","label":"Actions::Katello::Host::Erratum::Install","pending":true,"username":"admin","started_at":"2017-11-14 17:05:48 …
```
> [6.2.z] Backport Host's errata_apply and install_content helpers

- nailgun/entities.py
> Added Filters field in Role entity

- nailgun/entities.py
Issue #451 
Results 
Before
```
>>> from nailgun.entities import Subscription
>>> server_config = ServerConfig(auth=('admin', 'password'),url='http://satellite',verify=False)
>>> org_sub = Subscription(organization='xSxOhmTVNGpG').search()
>>> org_sub[0].read()
File "<stdin>", line 1, in <module>
File "nailgun/entities.py", line 6097, in read
return super(Subscription, self).read(entity, attrs, ignore, params)
File "nailgun/entity_mixins.py", line 815, in read
in _get_entity_ids(field_name, attrs)
File "nailgun/entity_mixins.py", line 292, in _get_entity_ids
attrs.keys()
nailgun.entity_mixins.MissingValueError: Cannot find a value for the "system" field. Searched for keys named ('system_ids', 'system', …
```
> Subscription entity no longer contains content host info

- nailgun/entities.py
Backports https://github.com/SatelliteQE/nailgun/pull/322 to 6.2.z.
> Allow content view versions to be searched (#322)

- nailgun/entities.py
- tests/test_entities.py
Force regenerate errata applicability
```bash
In[15]: org = entities.Organization(conf).create(create_missing=True)
In[16]: host = entities.Host(conf, organization=org).create(create_missing=True)
In[17]: host.errata_applicability()
Out[17]: 
{u'cli_example': None,
u'ended_at': u'2017-11-28 09:38:19 UTC',
u'humanized': {u'action': u'Generate applicability',
u'errors': [],
u'input': u'{"current_user_id"=>3}\n',
u'output': u''},
u'id': u'8d672137-f81f-4b2c-8184-537e100e49c7',
u'input': {u'current_user_id': 3},
u'label': u'Actions::Katello::Host::GenerateApplicability',
u'output': {},
u'pending': False,
u'progress': 1,
u'result': u'success',
u'started_at': u'2017-11-28 09:38:19 UTC',
u'state': u'stopped',
u'username': u'admin'}
In[18]: host.errata()
Out[18]: 
{u'error': None,
u'page': 1, …
```
> Host errata applicability

- nailgun/entities.py
This behavior cause all robottelo RHEV provisioning hosts with images tests to fail when searching for hosts (especially on teardown when searching for the provisioned hosts to delete).
```bash
In[2]: from nailgun import entities, config
In[3]: conf = config.ServerConfig('XXXXXXXXXXXXXXXXXXX', auth=('admin', 'changeme'), verify=False)
In[4]: hosts = entities.Host(conf).search(query=dict(search='name="annie-odear.sjlpfazwcj.mbz"'))
In[5]: len(hosts)
Out[5]: 1
In[6]: hosts[0]
Out[6]: nailgun.entities.Host(comment=u'', domain=nailgun.entities.Domain(id=10), managed=True, content_facet_attributes={u'content_view_id': 11, u'content_view_name': u'Default Organization View', u'content_source_id': None, u'kickstart_repository_id': None, u'uuid': None, u'content_view': {u'id': 11, u'name': …
```
> Fix Host search that fail when host contain image

- nailgun/entities.py
- tests/test_entities.py
```python
In [2]: sn = entities.Subnet(network_type='IPv4', network='255.255.255.0', remot
...: e_execution_proxy=[1]).create()
In [3]: sn
Out[3]: nailgun.entities.Subnet(dns_primary=None, domain=[], name=u'cVinKe', organization=[], cidr=5, id=33, boot_mode=u'DHCP', dns_secondary=None, from=None, network=u'255.255.255.0', subnet_parameters_attributes=[], to=None, ipam=u'None', mask=u'248.0.0.0', vlanid=None, gateway=None, location=[], dns=None, dhcp=None, tftp=None, network_type=u'IPv4')
In [4]: sn.network_type
Out[4]: u'IPv4'
```
> Add `network_type` and `remote_execution_proxy` fields to Subnet

- .travis.yml
When a tagged commit (e.g: new release on github UI) is done
travis will perform the release to PyPI.
NOTE: The release will only happen if the version is increased.
and also the build passed and only for tagged commits `git push --tags` or UI release is created,
> Automated PyPI deployment based on tagged releases

- nailgun/client.py
requests.urllib3 exists when you install requests via pip, but it should
not. and it does not exist when you install requests via rpm/deb.
thus let's filter the warnings directly from the urllib3 namespace, thus
making stuff work regardless how requests was installed
> filter urllib3.exceptions not requests.urllib3.exceptions

- setup.py
this tries to install a "tests" python package, which we don't own.
at the same time, also exclude docs and contrib as done in the PyPA
sample project [1]
[1] https://github.com/pypa/sampleproject/blob/master/setup.py
> don't install tests into the binary distribution

- nailgun/entity_mixins.py
Current create_missing will run if any non-negative value is passed in.
This change will make it run only if the user passes in True.
This shouldn't affect 'normal' usage, but rizza exploits this to abuse create_missing.
Example:
Executing: ActivationKey create with fields: {} and args {'create_missing': 'e9e5490b-6596-4f1f-817e-11c445c76d63'}
> create_missing only if explicitly True

- nailgun/entities.py
- tests/test_entities.py
> Do not return bytes, but str

- nailgun/entities.py
- tests/test_entities.py
Added fields `upstream_username` and `upstream_password` for `Repository` entity as it is required for the support of private docker registries.
Test also updated.
> Added fields to support docker private registry

- nailgun/entities.py
- tests/test_entities.py
`errata` param already exists but the Satellite expects `errata_id` to be set to the Red Hat Errata ID when creating Content View Filter Rules if I use the errata field Nailgun ends up sending the Database ID to Satellite, but I need to Red Hat Errata ID.
> add errata_id param to ContentViewFilterRule

- docs/conf.py
This is causing Travis jobs to fail on docs generation
```bash
sphinx-build -b html -d _build/doctrees  -W . _build/html
Running Sphinx v1.8.0
making output directory...
Warning, treated as error:
autodoc_default_flags is now deprecated. Please use autodoc_default_options instead.
Makefile:52: recipe for target 'html' failed
make[1]: *** [html] Error 2
make[1]: Leaving directory '/home/dlezz/projects/nailgun/docs'
Makefile:17: recipe for target 'docs-html' failed
make: *** [docs-html] Error 2
```
> Fix Sphinx deprecated option

- nailgun/entities.py
**Test Result:**
```
(robottelo-3y-ct8Zt) [root@okhatavk robottelo]# pytest tests/foreman/api/test_syncplan.py -v -k "test_positive_add_remove_products_custom_cron"
======================================================================== test session starts =========================================================================
platform linux -- Python 3.4.8, pytest-3.6.1, py-1.6.0, pluggy-0.6.0 -- /root/.local/share/virtualenvs/robottelo-3y-ct8Zt/bin/python3.4m
cachedir: .pytest_cache
rootdir: /home/okhatavk/Satellite/robottelo, inifile:
plugins: services-1.2.1, mock-1.10.0, cov-2.6.0
collecting 33 items …
```
> added custom cron field for 6.5 feature in sync plan

- nailgun/entities.py
Pulp/Django limit the upload size to about 2.5MB, so let's play safe and
use 2MB here.
> lower the chunk size for content uploads to 2MB

- Makefile
It started to fail on 4 years old commits.
Some say W503 and W504 are contradictory. We can expect some change regarding these rules. So I better ignore than go fixing it.
> Ignore arguable "W504 line break after binary operator"

- .flake8
spreading max-line-length = 99 across team's repositories
See SatelliteQE/robottelo#6344
> E501: Allow longer lines

- .flake8
spreading max-line-length = 99 across team's repositories
See SatelliteQE/robottelo#6344
> [6.3.z] E501: Allow longer lines

- .flake8
spreading max-line-length = 99 across team's repositories
See SatelliteQE/robottelo#6344
> [6.4.z] E501: Allow longer lines

- Makefile
It started to fail on 4 years old commits.
Some say W503 and W504 are contradictory. We can expect some change regarding these rules. So I better ignore than go fixing it.
> [6.4.z] Ignore arguable "W504 line break after binary operator"

- Makefile
It started to fail on 4 years old commits.
Some say W503 and W504 are contradictory. We can expect some change regarding these rules. So I better ignore than go fixing it.
> [6.3.z] Ignore arguable "W504 line break after binary operator"

- nailgun/entities.py
product sync plan read result in a sync plan entity with id=None if sync_plan_id=None
test output
suppose this test 
```python 
from nailgun import entities
from pytest import raises
from requests.exceptions import HTTPError
def test_product_sync_plan():
org = entities.Organization(id=1).read()
sync_plan = entities.SyncPlan(organization=org).create()
product = entities.Product(organization=org).create()
entities.Repository(product=product).create()
sync_plan.add_products(data={'product_ids': [product.id]})
product.sync()
product = product.read()
assert product.sync_plan.id == sync_plan.id
sync_plan.delete()
product = product.read()
assert product.sync_plan is None
with raises(HTTPError):
sync_plan.read()
```
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v …
```
> Fix Product sync_plan field read

- nailgun/entities.py
- tests/test_entities.py
This allows me to just pass in `add_content`:
```
>>> data = dict(data=dict(add_content=dict(package_ids=[1,2])))
>>> ContentViewVersion(config, content_view=cv).search()[0].incremental_update(synchronous=True, **data)
{u'username': u'admin', u'ended_at': u'2018-08-22 16:36:03 UTC', u'output': {u'changed_content': [{u'content_view_version': {u'id': 18}, u'added_units': {u'puppet_module': [], u'rpm': [], u'erratum': []}}]}, u'cli_example': None, u'label': u'Actions::Katello::ContentView::IncrementalUpdates', u'state': u'stopped', u'result': u'success', u'input': {u'services_checked': [u'pulp', u'pulp_auth'], u'version_outputs': [{u'output': {u'added_units': {u'puppet_module': [], u'rpm': [], u'erratum': []}}, u'version_id': 18}]}, u'action': u'Incremental Update of 1 Content View …
```
> Don't require content_view_version_id kwargs to CVV incremental_update()

- nailgun/entities.py
Reverts SatelliteQE/nailgun#531
Okay, going to skip all social aspects of previous conversations (and reasons why that PR stayed for so long without review). Here are only technical points for PR revert:
1) Introduce regression for at least one module (https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_contentviewversion.py). 
Didn't test more, but there is a chance for more global issues:
Before changes:
===19 passed, 3 skipped in 3110.24 seconds===
After:
===14 failed, 5 passed, 3 skipped in 2084.41 seconds===
It can be not only naming problem, but entity type used for environment
2) We never use plural format for arguments, please refer to:
https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L1980 …
> Revert "Add more attrs to ContentViewVersion"

- nailgun/entities.py
- tests/test_entities.py
This change will allow us to support SSL certificate management with
foreman_ansible_modules
> Use content credentials katello API instead of old gpg_keys

- nailgun/entities.py
- tests/test_entities.py
This also removes the requirements for the `product` field.
> Make repository_sets use /repository_sets/

- nailgun/entities.py
To test:
```py
>>> cvv=ContentViewVersion(id=11).read()
>>> cvv.environment
[nailgun.entities.LifecycleEnvironment(id=1), nailgun.entities.LifecycleEnvironment(id=2), nailgun.entities.LifecycleEnvironment(id=3)]
>>> cvv.environment[0].read()
nailgun.entities.LifecycleEnvironment(description=None, label=u'Library', prior=None, organization=nailgun.entities.Organization(id=1), id=1, name=u'Library')
```
> CVV have lifecycle environments, not puppet envs

- nailgun/entities.py
- tests/test_entities.py
Test results:
```python
In [1]: hc = entities.HostCollection(organization=3, host=[2]).create()
2018-11-28 18:18:43 - nailgun.client - DEBUG - Making HTTP POST request to https://example.com/katello/api/v2/host_collections with options {'auth': ('admin', 'some_password'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and data {"name": "ytdGyDgHTrIc", "host_ids": [2], "organization_id": 3}.
2018-11-28 18:18:44 - nailgun.client - DEBUG - Received HTTP 200 response:   {"name":"ytdGyDgHTrIc","organization_id":3,"max_hosts":null,"description":null,"total_hosts":1,"unlimited_hosts":true,"created_at":"2018-11-28 16:18:44 UTC","updated_at":"2018-11-28 16:18:44 UTC","id":10,"permissions":{"deletable":true,"editable":true}}
2018-11-28 18:18:44 - nailgun.client - DEBUG …
```
> Added 6.5 workaround for Host Collection create

- nailgun/entities.py
As MTU support for subnet has landed in [foreman 1.18](https://theforeman.org/manuals/1.18/index.html#Releasenotesfor1.18) and this version is included in [Satellite 6.4 (login required)](https://access.redhat.com/articles/1343683), this add MTU attribute in subnets for Satellite >= 6.4 and is needed by [theforeman/foreman-ansible-modules
#203](https://github.com/theforeman/foreman-ansible-modules/pull/203)
> Add MTU support to subnets

- nailgun/entities.py
Lifecycle Environment entity gained two fields in future Satellite 6.5 release.
To test:
```
entities.LifecycleEnvironment(id=1).read()
2018-11-29 13:37:05 - nailgun.client - DEBUG - Making HTTP GET request to https://sat-6-5-qa-rhel7.mzalewsk.example.com/katello/api/v2/environments/1 with options {'auth': ('admin', 'changeme'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and no data.
2018-11-29 13:37:06 - nailgun.client - DEBUG - Received HTTP 200 response:   {"library":true,"registry_name_pattern":"<%= organization.label %>-<%= lifecycle_environment.label %>-<%= content_view.label %>-<%= product.name %>-<%= repository.label %>","registry_unauthenticated_pull":false,"id":1,"name":"Library","label":"Library","description":null,"organization_id":1,"organizat …
```
> Add registry name fields to Lifecycle Environment

- nailgun/entities.py
**Description:** 
This is a new field was added in  sync plan for Satellite 6.5 feature while migrating sync plan from Pulp to Katello 
**How to use?**
```
In [10]: org = entities.Organization(id=1).read()
In [11]: sync_plan = entities.SyncPlan(organization=org, name='ddsd').search()
In [12]: sync_plan[0].foreman_tasks_recurring_logic.id
Out[12]: 2
```
**Objective** 
This will help to resolve https://github.com/SatelliteQE/robottelo/issues/6511 issue
> added foreman_tasks_recurring_logic_id in sync plan entity

- nailgun/entities.py
- tests/test_entities.py
Fixes https://github.com/SatelliteQE/satellite6-upgrade/issues/260 issue
This fixes the Product entity search was breaking because it was not able to read the sync plan without organization.
The issue was observed due to bug - https://bugzilla.redhat.com/show_bug.cgi?id=1237283
Results post Fix:
```
In [14]: entities.Product(name='Red Hat Software Collections (for RHEL Server)', organization=org).search()
Out[14]: [nailgun.entities.Product(description=None, gpg_key=None, label='Red_Hat_Software_Collections__for_RHEL_Server_', name='Red Hat Software Collections (for RHEL Server)', organization=nailgun.entities.Organization(id=1), id=2, sync_plan=nailgun.entities.SyncPlan(id=1, organization=nailgun.entities.Organization(id=1)))]
In [16]: prod = entities.Product(name='Red Hat Software …
```
> Fix search of Product added in Syncplan asks for organization

- tests/test_entities.py
Increasing coverage of searching for the Host having relation with image entity.
> Fix PRs coverage decresed issue by adding Host-Image related unit test

- nailgun/entities.py
```
auth = AuthSourceLDAP(server_config, onthefly_register=True, `name='test4',server_type='free_ipa',port='389',account='admin',account_password='changeme',base_dn='dc=example,dc=com',host='192.168.101.1', attr_login='login_ad',attr_lastname='surname',attr_firstname='firstname',attr_mail='mail', organization=[org],location=[loc]).create()
```
```
>>> auth.read()
nailgun.entities.AuthSourceLDAP(account='admin', attr_photo=None, base_dn='dc=example,dc=com', groups_base=None, host='192.168.101.1', name='test4', onthefly_register=True, port=389, server_type='free_ipa', tls=False, attr_firstname='firstname', attr_lastname='surname', attr_login='login_ad', attr_mail='mail', location=[nailgun.entities.Location(id=10)], organization=[nailgun.entities.Organization(id=11)], id=13)
```
> Added org and loc for authsource entity

- nailgun/entities.py
- tests/test_entities.py
This change will allow us to support SSL certificate management with
foreman_ansible_modules
------
Cherry-pick from https://github.com/SatelliteQE/nailgun/pull/554
> Use content credentials katello API instead of old gpg_keys (#554)

- nailgun/entities.py
- tests/test_entities.py
```
entities.JobInvocation().run(synchronous=False, data={
'job_template_id': 117,
'inputs': {'command': "ls"},
'targeting_type': 'static_query',
'search_query': "name = {0}".format('***'),
})
{'id': 16, 'description': 'Run ls', 'job_category': 'Commands', 'targeting_id': 16, 'status': 3, 'start_at': '2018-12-20 12:50:03 UTC', 'status_label': 'running', 'dynflow_task': {'id': '6fdb8f93-a521-4717-b458-f701e66c0215', 'state': 'planned'}, 'succeeded': 'N/A', 'failed': 'N/A', 'pending': 'N/A', 'total': 1, 'targeting': {'bookmark_id': None, 'search_query': 'name = ***', 'targeting_type': 'static_query', 'user_id': 4, 'hosts': [{'name': '***', 'id': 1}]}, 'task': {'id': '6fdb8f93-a521-4717-b458-f701e66c0215', 'state': 'planned'}, 'template_invocations': []}
```
> Add Job Invocation entity

- nailgun/entities.py
- tests/test_entities.py
The code applied to the 6.4 branch with PR 589 can be applied to 6.3 almost unchanged.
At my company we are still on Satellite 6.3, so if CCV support for 6.3 can be added upstream, it would save us from maintaining our own private fork.
> Backport support for composite content views to 6.3 branch (from PR #589)

- nailgun/entities.py
- tests/test_entities.py
- Cherry pick of #596 
- Same API does exists with Satellite6.4
- Test results:
```
>>> entities.JobInvocation().run(synchronous=False, data={'job_template_id': 89, 'inputs': {'command': "ls"},'targeting_type': 'static_query', 'search_query': "name = 'test'"})
{'id': 12, 'description': 'Run ls', 'job_category': 'Commands', 'targeting_id': 12, 'status': 3, 'start_at': '2019-01-29 05:17:17 UTC', 'status_label': 'running', 'dynflow_task': {'id': 'c42f3ee2-e1e4-4520-9ba8-49bc1de92b66', 'state': 'planned'}, 'succeeded': 'N/A', 'failed': 'N/A', 'pending': 'N/A', 'total': 0, 'targeting': {'bookmark_id': None, 'search_query': "name = 'test'", 'targeting_type': 'static_query', 'user_id': 3, 'hosts': []}, 'task': {'id': 'c42f3ee2-e1e4-4520-9ba8-49bc1de92b66', 'state': 'planned'}, …
```
> [Cherry-pick 6.4.z] Add Job Invocation entity

- nailgun/entities.py
```python
In [5]: entities.UserGroup().search()
Out[5]:
[nailgun.entities.UserGroup(admin=False, name='test_group1', id=1),
nailgun.entities.UserGroup(admin=False, name='test_group2', id=2)]
In [6]: entities.UserGroup().search(query={'search': 'name=test_group1'})
Out[6]: [nailgun.entities.UserGroup(admin=False, name='test_group1', id=1)]
```
> Made UserGroup entity searchable

- nailgun/entities.py
Hoping to be able to remove https://github.com/theforeman/foreman-ansible-modules/blob/master/module_utils/ansible_nailgun_cement.py#L200
Its been in FAM for 1 year now, https://github.com/theforeman/foreman-ansible-modules/blob/master/module_utils/ansible_nailgun_cement.py#L468
> Make ComputeProfile searchable

- nailgun/entities.py
- tests/test_entities.py
```
>>> org = entities.Organization(name='test10').create()
>>> loc = entities.Location(name='test11').create()
>>> usergroup = entities.UserGroup(name="abc10").create()
>>> auth = entities.AuthSourceLDAP(onthefly_register=True, name='test4',server_type='free_ipa',port='389',account='uid=foreman,cn=example,dc=com',account_password='changeme',base_dn='cn=users,cn=example,dc=com', groups_base='cn=foobargroup,cn=example,dc=com',host='192.168.100.2', attr_login='uid',attr_lastname='givenName',attr_firstname='sn',attr_mail='mail', organization=[org],location=[loc]).create()
>>> entities.ExternalUserGroups(name='foobargroup',usergroups=usergroup,auth_source=auth).create()nailgun.entities.ExternalUserGroups(usergroups=nailgun.entities.UserGroup(admin=False, …
```
> Added external usergroup entity

- nailgun/entities.py
* Depends on [Fixes #25975 - Add ability to read compute_attributes via foreman API](https://github.com/theforeman/foreman/pull/6457)
* Needed by [Add compute_attributes support to foreman-ansible-modules #222](https://github.com/theforeman/foreman-ansible-modules/issues/222)
> Add vm_attributes to compute_attribute

- nailgun/entities.py
Add fields:
* datacenter
* ovirt_quota
```
>>> from nailgun import entity_mixins, entity_fields, entities
>>> from nailgun.entities import Entity, AbstractComputeResource, OVirtComputeResource, ComputeProfile, ComputeAttribute, Location, Organization, Domain
>>> cr = AbstractComputeResource(id=2).read()
>>> cr
nailgun.entities.OVirtComputeResource(description='', location=[], name='ovirt-cr01', organization=[nailgun.entities.Organization(id=1)], provider='Ovirt', provider_friendly_name='oVirt', url='https://ovirt.example.com/ovirt-engine/api', user='bagasse@example.com', use_v4=True, datacenter='c1479626-99a2-44eb-8401-14b5630f417f', ovirt_quota='502a76bb-a3fe-42f1-aed6-2a7c892a6786', id=2)
>>>
```
> Add datacenter and quota for ovirt CR

- nailgun/entities.py
Implemented additional fields for `Host` entity. This unlocks the possibility of using nailgun for true compute-resource-based provisioning 
for the `build_status_label`:
```bash
In [8]: h = entities.Host(id=53).read()
2019-02-12 01:21:29 - nailgun.client - DEBUG - Making HTTP GET request to https://sat-6-5-qa-rhel7.localhost.example.com/api/v2/hosts/53 with options {'auth': ('admin', 'changeme'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and no data.
2019-02-12 01:21:30 - nailgun.client - DEBUG - Received HTTP 200 response: {"ip":"192.168.100.124","ip6":null,"environment_id":31,"environment_name":"KT_JHiqyw_OHOssaCw_WvsPhv_112","last_report":null,"mac":"52:54:00:bb:51:8d","realm_id":null,"realm_name":null,"sp_mac":null,"sp_ip":null,"sp_name":null,"domain …
```
> add compute_attributes, interface_attributes and build_status_label fields to Host entity

- nailgun/entities.py
closes https://github.com/SatelliteQE/nailgun/issues/617
Think  we have to keep it simple and rely only only server response , if return initialize
out put of a test when not returned , and was failing in automation
```
(robottelo) dlezz@dlezz:~/projects/robottelo-fork$ pytest -v tests/foreman/ui_airgun/test_hostcollection.py::test_positive_install_package_group 
============================================ test session starts =============================================
platform linux -- Python 3.6.6, pytest-4.0.2, py-1.5.4, pluggy-0.8.0 -- /home/dlezz/.pyenv/versions/robottelo/bin/python3.6
cachedir: .pytest_cache
shared_function enabled - ON - scope: ffff - storage: redis
rootdir: /home/dlezz/projects/robottelo-fork, inifile:
plugins: xdist-1.26.0, timeout-1.3.3, services-1.3.1, …
```
> Fixes build_status_label, not always returned

- nailgun/entities.py
- tests/test_entities.py
```
>>> entities.ArfReport(server_config,id=2425).read()
nailgun.entities.ArfReport(location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1)], host=nailgun.entities.Host(id=4), openscap_proxy=nailgun.entities.Capsule(id=1), policy=nailgun.entities.CompliancePolicies(id=1), id=2425)
>>> entities.ArfReport(server_config,id=2425).delete()
{'id': 2425, 'host_id': 4, 'reported_at': '2019-04-04T11:40:21.000Z', 'created_at': '2019-04-04T11:40:23.696Z', 'updated_at': '2019-04-04T11:40:23.696Z', 'status': {'passed': 20, 'othered': 1, 'failed': 32}, 'metrics': {'passed': 20, 'failed': 32, 'othered': 1}, 'origin': None, 'openscap_proxy_id': 1}
```
> Added arf report entity

- nailgun/entities.py
- tests/test_entities.py
- Added support for rebuild_config in hostgroup
- test result:
```
(Pdb) dir(hostgroup)
['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__init_subclass__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_fields', '_meta', '_server_config', 'add_puppetclass', 'architecture', 'clone', 'compare', 'content_source', 'content_view', 'create', 'create_json', 'create_missing', 'create_payload', 'create_raw', 'delete', 'delete_puppetclass', 'delete_raw', 'domain', 'environment', 'get_fields', 'get_values', 'id', 'lifecycle_environment', 'list_scparams', …
```
> Added support for rebuild_config in hostgroup

- nailgun/entities.py
$subject
Results:
----------------
```
In [2]: entities.AuthSourceLDAP().search(query={'search': 'name=31JSNDAxSE'})
Out[2]: [nailgun.entities.AuthSourceLDAP(account='foobar', attr_photo='', base_dn='cn=Users,dc=hidden,dc=hidden,dc=hidden,dc=hidden,dc=redhat,dc=com', groups_base='cn=foobargroup,dc=hidden,dc=hidden,dc=hidden,dc=hidden,dc=redhat,dc=com', host='some_ip', name='31JSNDAxSE', onthefly_register=False, port=000, server_type='active_directory', tls=False, attr_firstname='givenName', attr_lastname='sn', attr_login='same', attr_mail='mail', location=[nailgun.entities.Location(id=2), nailgun.entities.Location(id=37)], organization=[nailgun.entities.Organization(id=1), nailgun.entities.Organization(id=36)], id=15)]
```
> authSourceLDAP Search support

- nailgun/entities.py
deprecated in this commit: https://github.com/Katello/katello/pull/8135/files
Robottelo api tests for classparameters are affected by this, example test result after change:
```
pytest tests/foreman/api/test_classparameters.py -k test_negative_enable_avoid_duplicates_checkbox================================================================= test session starts ==================================================================
platform linux -- Python 3.7.3, pytest-4.0.2, py-1.7.0, pluggy-0.12.0
rootdir: /home/pondrejk/Documents/robottelo, inifile:
plugins: cov-2.7.1, mock-1.10.4, forked-0.2, services-1.3.1, xdist-1.29.0
collecting ... 2019-06-19 13:08:01 - conftest - DEBUG - BZ deselect is disabled in settings
collected 49 items / 48 …
```
> uuid for ContentViewPuppetModule now deprecated

- nailgun/entities.py
- tests/test_entities.py
1. Add support to kubevirt for virt-who-config
2. Add support to Interval for Satellite New features. (support to chose 1440,2880,4320)
3. Add support to Get List of virt-who configurations per organization
> Add support to kubevirt for virt-who-config

- nailgun/entities.py
1. Add filter_host_parents and exclude_host_parents options
2. Sort the fields by alphabetically.
> Add filter_host_parents and exclude_host_parents options for virt-who entity

- nailgun/entities.py
- tests/test_entities.py
Cherry-pick #660 #650 to stable-branch 
#660 :
1.Add filter_host_parents and exclude_host_parents options
2.Sort the fields by alphabetically.
#650 :
1.Add support to kubevirt for virt-who-config
2.Add support to Interval for Satellite New features. (support to chose 1440,2880,4320)
3.Add support to Get List of virt-who configurations per organization
> Add host_parents options for virt-who entity

- nailgun/entities.py
```
(Pdb++) sn = entities.Subnet(id=4).read()
2019-10-10 11:38:16 - nailgun.client - DEBUG - Making HTTP GET request to https://192.168.121.209/api/v2/subnets/4 with options {'auth': ('admin', 'changeme'), 'verify': False, 'headers': {'content-type': 'application/json'}}, no params and no data.
2019-10-10 11:38:16 - nailgun.client - DEBUG - Received HTTP 200 response: {"network":"7350:325a:3baa:fd41:2224:1288:5c5:5855","network_type":"IPv6","cidr":24,"mask":"ffff:ff00::","priority":null,"vlanid":null,"mtu":1600,"gateway":"","dns_primary":"","dns_secondary":"","from":"","to":"","created_at":"2019-10-10 09:32:44 UTC","updated_at":"2019-10-10 09:32:44 UTC","ipam":"EUI-64","boot_mode":"DHCP","id":4,"name":"ToQeuQkixB","description":"4NFGKQnBsv","network_address":"7350:325a:3baa:fd41:2224:1288: …
```
> add description field to Subnet entity

- nailgun/entity_mixins.py
If property is ListField and current value is null (which is common for fields that never got any value assigned), leave it as is and don't try to iterate over it.
Introduced as fix for long-running failures in docker repositories (see https://github.com/SatelliteQE/robottelo/issues/7540):
```
$ pytest -v tests/foreman/api/test_docker.py::DockerRepositoryTestCase::test_positive_update_url tests/foreman/api/test_docker.py::DockerRepositoryTestCase::test_positive_update_upstream_name tests/foreman/api/test_docker.py::DockerRepositoryTestCase::test_positive_update_name
===================================================================================== test session starts ===================================================================================== …
```
> Don't try to iterate over null

- nailgun/entity_mixins.py
This is cherry-pick of #686 into stable-satellite.
If property is ListField and current value is null (which is common for fields that never got any value assigned), leave it as is and don't try to iterate over it.
> [cherry-pick] Don't try to iterate over null

- .travis.yml
- docs/create_organization_nailgun.py
- docs/create_organization_nailgun_v2.py
- docs/create_organization_plain.py
- docs/create_user_nailgun.py
- docs/create_user_plain.py
- docs/examples.rst
- nailgun/__init__.py
- nailgun/client.py
- nailgun/entities.py
- nailgun/entity_mixins.py
- release.sh
- setup.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Update setup.py/travis supported python versions.
Make some updates in regard to py3.6 support including f-strings, and no `u''` string specs.
NOTE: At the moment this includes the commits from #700, they will be re-based out.
> Drop py2 support, specify py 3.6

- nailgun/entities.py
Fixes #714 : Setup for UI testing failed
Add the 'config_template' `ignore` in `read()` can fix the issue, works fine for virt-who ui-testing
> Remove `config_template` in Organization and Location entities

- nailgun/entities.py
Causing errors with subnet entity. 
This mistake was done accidentally in #702 
Look at entities and search for `mtu`, you can see it was deleted during replacement process, probably macro looked like `u'`
I tested it with `test_positive_create_with_subnet`. But all test in automation using API subnet calls should be fixed by this. 
```
test_host.py::HostTestCase::test_positive_create_with_subnet 
=================== 1 passed, 77 deselected in 76.68 seconds ===================
```
> subnet fix mt to mtu [1-liner]

- nailgun/entities.py
- tests/test_entities.py
config template was causing error in `test_positive_get_per_page`
I would like to finish here what was started in #714 
And I would like open discussion here, what we are going to do with all other occurencies which are still in `entities.py`: 
```
output of command grep -nr 'config_template'
entities.py:1561:            'api_path': 'api/v2/config_templates',
entities.py:1591:        return {'config_template': payload}
entities.py:1599:        return {'config_template': payload}
entities.py:1607:            /config_templates/build_pxe_default
entities.py:1609:            /config_templates/clone
entities.py:1611:            /config_templates/revision
``` 
I had local problems with `test_positive_get_per_page`:
```
cls.compresource_libvirt = entities.LibvirtComputeResource( …
```
>  deleting all occurencies of config template

- nailgun/entities.py
- tests/data/ssg-rhel7-ds-tailoring.xml
- tests/test_entities.py
```
In [2]: tf = entities.TailoringFile( scap_file="/home/jpathan/Downloads/ssg-rhel7-ds-tailoring.xml", organization=[1], location=[2], name='tailoring_file1').create()                    
In [3]: tf                                                                                                                                                                               
Out[3]: nailgun.entities.TailoringFile(name='tailoring_file1', original_filename=None, id=20)
In [4]: tf.read()                                                                                                                                                                        
Out[4]: nailgun.entities.TailoringFile(name='tailoring_file1', original_filename=None, id=20)
In [7]: tf = entities.TailoringFile(id=tf.id, …
```
> Fixes #721 - Added support for Tailoring file entity

- nailgun/entities.py
prior 6.8, API always returned `audit_comment` in the GET requests.
This is now gone.
> add audit_comments to the ignored fields for ProvisioningTemplate

- nailgun/entities.py
Cherry-picking commit f207095b0d77d53228cadd562021e488d6d1fd0e (#723) to `stable-satellite` branch.
> [cherry-pick] Add audit_comments to the ignored fields for ProvisioningTemplate

- nailgun/entities.py
'use_puppet_default' was deprecated and removed from Satellite 6.8, we shall use 'omit' instead.
Reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1791659
https://projects.theforeman.org/issues/28583
> Deprecation of 'use_puppet_default'

- nailgun/entities.py
'use_puppet_default' was deprecated and removed from Satellite 6.8, we shall use 'omit' instead.
Reference:
https://bugzilla.redhat.com/show_bug.cgi?id=1791659
https://projects.theforeman.org/issues/28583
> [cherry-pick] Deprecation of 'use_puppet_default'

- nailgun/entities.py
Currently, all the CLI classparameters tests are failing in setup during the host creation here:
tests/foreman/cli/test_classparameters.py:
```
73         cls.host = entities.Host(
74             organization=cls.org['id'], location=cls.loc['id'], environment=cls.env['name']
75         ).create()
```
The problem appears in the create_missing() method of nailgun entities:
venv/lib64/python3.7/site-packages/nailgun/entities.py:
```
3891             if not hasattr(self.environment, 'organization'):
3892                 self.environment = self.environment.read()
3893             if self.location.id not in [
3894                     loc.id for loc in self.environment.location]:
3895                 self.environment.location.append(self.location)
3896 …
```
> Host creation fix.

- nailgun/entities.py
cherry-picking #737 into `stable-satellite`.
> [cherry-pick] removed resource-type parameter from Permission entity

- nailgun/entities.py
Hello
I need to write test[1] which has to use `bulk/add_subscriptions` API. Therefore, need nailgun support for this API [2]
[1]  https://github.com/SatelliteQE/robottelo/blob/0d0bec299cad1d587e64b53cf48561aa3d4c46dd/tests/foreman/api/test_hostcollection.py#L383
[2] https://theforeman.org/plugins/katello/3.15/api/apidoc/v2/hosts_bulk_actions/add_subscriptions.html
> Add bulk_add_subscriptions (#733)

- nailgun/entities.py
Turns out that removing the parameter in #737 was premature, the permissions search test depends on listing those resource types which led to unforeseen failure
> restore permissions resource type

- nailgun/entities.py
Hello
committing for feedback, this does not work yet, I am getting  an extra `subscription` on the end. Somehow need to change this line:
`response = client.get(self.path('subscriptions'), **kwargs)`
to not send the extra `subscription`
Edit: setting 'base'  works:
`response = client.get(self.path('base'), **kwargs)`
Ref:
https://theforeman.org/plugins/katello/3.15/api/apidoc/v2/host_subscriptions/index.html
> Add support for reading subscriptions

- nailgun/entities.py
This PR brings the possibility to work with Host Traces.
4 new methods in Katello API => 4 nailgun methods.
> GET /api/hosts/:host_id/traces | List services that need restarting on the host
> PUT /api/hosts/:host_id/traces/resolve | Resolve Traces
> POST /api/hosts/bulk/traces | Fetch traces for one or more hosts
> PUT /api/hosts/bulk/resolve_traces | Resolve traces for one or more hosts
> katello-tracer component implementation

- nailgun/entities.py
Fixing the tests, 
Needs cherry-pick to `stable branch` and to `6.8.z`
Connected to #748 and  #758 
If there is no traces_status it should be ignored, on the other hand if there are traces it should be [read](https://github.com/tstrych/nailgun/blob/b46f8f13326dd4abb0fd3d3f24cd25cc0184f15f/nailgun/entities.py#L4252)
Thanks to @ogajduse it was tested also on host with  traces attributes:
Command below is using the same read method as the robotello tests mentioned below.
` entities.Host().search(query={'search': "dhcp-3-206.vms.sat.rdu2.redhat.com"})[0].read()`
shows:
Test results: 
```
collected 30 items / 26 deselected / 4 selected
test_host.py::test_positive_search_by_parameter 2020-10-29 15:30:09 - robottelo - DEBUG - Finished Test: test_host.py/test_positive_search_by_parameter …
```
> traces status ignored

- nailgun/entity_mixins.py
As part of the Satellite class, entity class inits are modified
to include the server_config by default.
This seems to conflict with existing argument structure when an
entity is created during create_missing.
This change will try the usual method and fall back to not passing
a server config if the TypeError is encountered
> Minor change to allow for incoming robottelo Satellite class

- nailgun/entities.py
- tests/test_entities.py
**Description**
Fix #774 temporary as we cannot read the HTTP option for the virt-who entity now.
Ignore it for now so that we can test other cases.
Related bug: 
https://bugzilla.redhat.com/show_bug.cgi?id=1902199
**Test Result**
```
(venv) [hkx303@kuhuang api]$ pytest test_esx.py -k test_positive_deploy_configure_by_id -s
==================================== test session starts =====================================
platform linux -- Python 3.7.3, pytest-5.4.3, py-1.9.0, pluggy-0.13.1
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo, inifile: pytest.ini
plugins: metadata-1.10.0, html-2.1.1, cov-2.10.1, services-1.3.1, xdist-1.34.0, mock-1.10.4, forked-1.3.0, ibutsu-1.1.1
collecting ... 2020-11-27 10:32:31 - conftest - DEBUG - …
```
> Update the virt-who entity temporary to fix the read error

- nailgun/entity_mixins.py
Deprecation warning is seen during unit test execution, and will change in Python 3.9.
> Fix deprecation warning for collections import

- nailgun/entities.py
Just like the `RPMContentViewFilter` with `original_package`, the
`ModuleStreamContentViewFilter` has a flag to include Module Streams with
no errata.
> Adding original_module_streams field to filter

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
Removed:
- Deprecated System and SystemPackage entities
- Entity method workarounds based on old versions of Satellite (6.1 and 6.2)
- server_modes
- Unit tests related to all of the above
<Jenkins Instance>/view/Satellite 6/job/satellite6-standalone-automation/2089/testReport/
- tests.foreman.api.test_contentview.TestContentViewRedHatContent  Has some failures in the standalone in test setup, a 403 on access to katello/api/v2/repository_sets, I don't believe this is related to my changes.
- Additional failures are in unmodified classes, I have confidence this PR doesn't have any negative impact on test results in robottelo. I'll followup with fixes for anything that does see an impact, but the test results give me confidence in the change.
> Remove long deprecated entities and Version based logic blocks

- nailgun/entities.py
All the settings update related test cases are getting failed due to missing keys error.
```
>               setattr(entity, field_name, attrs[field_name])
E               KeyError: 'created_at'
../../Nailgun/nailgun/nailgun/entity_mixins.py:804: KeyError
>               setattr(entity, field_name, attrs[field_name])
E               KeyError: 'updated_at'
../../Nailgun/nailgun/nailgun/entity_mixins.py:804: KeyError
```
After adding these filed in the ignore list all the test gets passed.
Before Fix:
```
$ pytest tests/foreman/api/test_setting.py
=============================================================================================== test session starts ===============================================================================================
platform linux -- Python 3.6.6, …
```
> Added "created_at" and "updated_at"  in the settings ignore field.

- nailgun/entities.py
- tests/test_entities.py
**Description**
Fix #774 
**Test Result**
```
(venv) [hkx303@kuhuang api]$ pytest test_esx.py -k test_positive_proxy_option -s
============================== test session starts ===============================
platform linux -- Python 3.7.3, pytest-6.2.1, py-1.9.0, pluggy-0.13.1
rootdir: /home/hkx303/Documents/CI/robottelo/robottelo, configfile: pyproject.toml
plugins: services-2.2.1, metadata-1.10.0, html-2.1.1, mock-3.4.0, cov-2.10.1, xdist-2.2.0, ibutsu-1.13, forked-1.3.0
collected 8 items / 7 deselected / 1 selected   
============ 1 passed, 7 deselected, 9 warnings in 101.09s (0:01:41) =============
```
> Update virt-who entity as http option has been changed

- nailgun/entity_mixins.py
This commits adds a task_id parameter to TaskTimedOutError and TaskFailedError. Knowing the task id helps to handle task related errors.
```
try:
do_something_task_related()
except TaskFailedError as error:
get_more_information_from_task(error.task_id)
```
At the moment you have to parse the task id from the exception message, which is not very convenient.
> add task_id parameter to TaskTimedOutError and TaskFailedError

- nailgun/entities.py
- tests/test_entities.py
host bulk/destroy action was added
[upstream documentation](https://theforeman.org/plugins/katello/3.5/api/apidoc/v2.html) 
search for `api/hosts/bulk/destroy`
In [robottelo PR](https://github.com/SatelliteQE/robottelo/pull/8468)
I did not run `tests/test_entities.py` locally. 
I would be happy if you can tell me how to do that.
> Bulk destroy

- nailgun/entities.py
Removed `puppet_module` field from ContentView class.
What changed in Sat 6.10:
```
I want to clarify a bit about what is and is not deleted upon upgrade to
6.10.
The TLDR; the 6.10 upgrade doesn't delete puppet environments and
puppet content used by hosts. Puppet clients can still use the puppet
content from before the upgrade.
The longer explanation:
First let me explain how the puppet content support worked. There are
two aspects to it:
1. puppet repositories - these are the pulp entities that would hold
compressed puppet modules, a user could sync or upload puppet content to
them
2. puppet environments - these are the foreman entities that correspond
to an on disk directory on the satellite server and capsules where the
puppet modules are extracted. Hosts consume puppet modules from …
```
> Remove puppet module field from CV

- nailgun/entities.py
- tests/test_entities.py
removal of puppet modules for satellite 6.10
it's only a removal, so there is no functionality to demonstrate
I did remove it based on change in adidoc. I **DID NOT** investigate it further. I would like to get ACK from team members that know more about puppet and puppet modules. 
the test is no longer failing when creating a Content View, but hitting other error connected to proxy. (fake capsule)
> removal of puppet modules

- nailgun/entities.py
- nailgun/entity_mixins.py
This is a continuation of the change introduced in #770
Robottelo injects the server config in the init methods of each entity.
As a result, passing the server config as part of the instantiation in
these places will result in multiple server configs being passed in.
> More changes needed for robottelo's config injection

- nailgun/entities.py
- nailgun/entity_mixins.py
This is a continuation of the change introduced in #770
Robottelo injects the server config in the init methods of each entity.
As a result, passing the server config as part of the instantiation in
these places will result in multiple server configs being passed in.
> [6.9.z] More changes needed for robottelo's config injection

- nailgun/entities.py
This adds the ability to enable/disable and check eligibility
of SCA for an organization.
Ref:  Add SCA functionality to the Organization entitiy #789
> [6.9.z cherry-pick] Add SCA functionality to the Organization entitiy

- nailgun/entities.py
Just adding new fields related to `ansible_collection` repository type so I can use it in test.
https://<sat_fqdn>/apidoc/v2/repositories/create.html
test in robottelo like
```
repo = entities.Repository(
ansible_collection_auth_url="https://auth.redhat.com",
ansible_collection_auth_token="auth_token",
ansible_collection_requirements=requirements,
content_type='ansible_collection',
product=module_product,
url='https://galaxy.ansible.com/',
).create()
repo = repo.read()
```
successfully creates the repo with provided args and reads like
```
{
...
"relative_path": "jUaneEUoSSLW/Library/custom/uAhljNDLMEJJ/HEYIcuAADk",
"created_at": …
```
> Add ansible-collection related fields 

- .vscode/settings.json
- nailgun/entities.py
I'm wondering if this is a valid way to add the size attribute to ContentUpload. I have to add the two lines in the `read()` function in order for the `super.read()` to pass. However, I am now having issues with the checksum not matching when the import upload is ran after this. I would like to get some feedback if this is valid, or if it could be causing the checksum issue.
None that I could find.
Example:
```
attrs
{'upload_id': '50ba7ca9-fc60-43ba-9...2a8ed31594', 'size': -9148830520927570858}
```
> Adding size attribute to ContentUpload

- nailgun/entities.py
An attribute was added to the `Subnet` class.
https://github.com/SatelliteQE/robottelo/pull/9246 depends on this
https://github.com/SatelliteQE/robottelo/blob/9bbec8c836b3ef345c9f27896c40c801b3c43303/tests/foreman/cli/test_provisioning.py#L66-L145
`subnet` instance:
```
robottelo.hosts.DecClass(boot_mode='DHCP', cidr=29, description=None, dhcp=nailgun.entities.SmartProxy(id=1), dns=nailgun.entities.SmartProxy(id=1), dns_primary='10.5.30.160', dns_secondary='10.11.5.19', domain=[nailgun.entities.Domain(id=18)], from_='10.1.5.90', gateway='10.1.5.94', httpboot=nailgun.entities.SmartProxy(id=1), ipam='None', location=[nailgun.entities.Location(id=22)], mask='255.255.255.248', mtu=1500, name='PTxwMv', network='10.1.5.88', network_type='IPv4', …
```
> Add httpboot proxy attribute to Subnet

- nailgun/entities.py
Attributes were added to the `HostGroup` class.
https://github.com/SatelliteQE/robottelo/pull/9246 depends on this
https://github.com/SatelliteQE/robottelo/blob/ecf0a9cd61863bc9674c2bc9481dea6f52ef1bec/tests/foreman/cli/test_provisioning.py#L190-L204
`hostgroup` instance:
```
robottelo.hosts.DecClass(organization=[nailgun.entities.Organization(compute_resource=[], description=None, domain=[], environment=[], hostgroup=[], label='uzyDYcFG', medium=[], name='uzyDYcFG', provisioning_template=[nailgun.entities.ProvisioningTemplate(id=44), nailgun.entities.ProvisioningTemplate(id=28), nailgun.entities.ProvisioningTemplate(id=10), nailgun.entities.ProvisioningTemplate(id=61), nailgun.entities.ProvisioningTemplate(id=63), nailgun.entities.ProvisioningTemplate(id=64), …
```
> Add description, content view and PXE loader to HG

- nailgun/entities.py
This is version - 1 of #799 that was initially raised by @swadeley to remove the environment param from the organization entity. 
This PR is being raised to fix the tons of failures we have due to #799 is not yet merged or the discussions are still happening on that to support the optional puppet feature even though it's not the default anymore with sat 7.0 but still some components would enable them and use them until they are depreciated.
So let's merge this PR to unblock with the current count of failures vs later we can work on #799 to address the entities using environment/puppet facility with fewer failures.
Refer #799 for [results](https://github.com/SatelliteQE/nailgun/pull/799#issue-1078591248) and discussions.
> [#799 - v1] Remove environment param from Organization entity

- nailgun/entities.py
The puppet-related URLs have changed with movement into a plugin in 7.0.
https://community.theforeman.org/t/the-road-to-making-puppet-optional/17983
or see the apidoc of a puppet-enabled Satellite
CRUD like the following with entities passed:
```
>>> cg = entities.ConfigGroup(name='ahoy').create()
>>> res = cg.read()
>>> res
nailgun.entities.ConfigGroup(name='ahoy', id=1)
>>> cg.name = 'astalavista'; res = cg.update(['name'])
>>> cg = entities.ConfigGroup().search(query={'search':f'name="astalavista"'})[0].read()
>>> cg
nailgun.entities.ConfigGroup(name='astalavista', id=1)
>>> res = cg.delete()
>>> res
{'id': 1, 'name': 'astalavista', 'created_at': '2021-12-20T15:29:41.261Z', 'updated_at': '2021-12-20T15:29:57.987Z'}
```
> Fix puppet-related URLs

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
Fixes issue related to `environment` and `puppetclass` field for `Host` and `SmartVariable` Entity.
```
(Pdb) entities.Host().create()
nailgun.entities.Host(all_parameters=[{'priority': 0, 'created_at': '2022-01-07 06:11:01 UTC', 'updated_at': '2022-01-07 06:11:01 UTC', 'id': 3, 'name': 'host_registration_remote_execution', 'parameter_type': 'boolean', 'value': True}, {'priority': 0, 'created_at': '2022-01-07 06:09:33 UTC', 'updated_at': '2022-01-07 06:09:33 UTC', 'id': 1, 'name': 'host_registration_insights', 'parameter_type': 'boolean', 'value': True}, {'priority': 0, 'created_at': '2022-01-07 06:11:01 UTC', 'updated_at': '2022-01-07 06:11:01 UTC', 'id': 4, 'name': 'host_packages', 'parameter_type': 'string', 'value': ''}, {'priority': 0, 'created_at': '2022-01-07 06:11:02 UTC', …
```
> Fix issue related to environment and puppetclass field for Host Entity.

- nailgun/entities.py
- tests/test_entities.py
Parameter mirror_on_sync has been added to API
in Katello PR 9834.
This is not returned as part of JSON on entity creation.
Consequently, read() fails.
It could be workarounded by ignoring errors when reading
non-required parameters. Also, this would be fixed if
Satellite started returning that value.
This solves the issue without unnecessary changes
in Nailgun's guts that might break something.
> #808 Ignore mirror_on_sync

- nailgun/entity_mixins.py
TLDR 
reverts #805 
intorucing the new way of reading environment
global ignore fields were problematic once the puppet was enabled via installer
with puppet enabled read the entity that uses environment, but read method already ignores the environment variable, so test fail, because asserts on environment has no values inside the object as result of ignorance
introducing new way 
during read if puppet is enabled there is environment it will be returned in `if` or `elif` clauses above 
if is not and attr is environment append the variable with empty  list and return it -> no more errors :+1: 
One think I am not sure about.  
Changed method `_get_entity_ids` is used also for search.  If you search for environment and there is none,  should the error be raised here ? I think it does not, …
> sat 7.0 environment fix

- nailgun/entities.py
Mirror on sync has been changed.  Changing it to reflect what's in repo setup page.  Testing still needs to be done in order to see if it passes and may reflect changes in airgun as well.
Here's the error that I got when I tested:
```
entities.Repository(name=repo_name, product=product).create()
{HTTPError}422 Client Error: Unprocessable Entity for url: <sat>:443/katello/api/v2/repositories
```
> Fix mirror_on_sync

- nailgun/entities.py
- tests/test_entities.py
Adding basic methods to bulk cancel or bulk resume Foreman Tasks. Follows conventional POST request methods found in other entities. No impact to existing tests.
Not available upstream, but API endpoints can be found in Satellite 7 API doc under Foreman Tasks.
```python
sync_task = repo.sync(synchronous=False)
entities.ForemanTask().cancel(data={"task_ids": [sync_task['id']]})
publish_task = cv.publish(synchronous=False)
entities.ForemanTask().resume(data={"task_ids": [publish_task['id']]})
```
You'll notice that I'm used `task_ids` and passing a list of task ids. That is because these are bulk cancel and bulk resume end points. Passing no data would cancel/resume any cancellable/resumable tasks. You can specify one or multiple tasks using `task_ids`.
I'm also unsure if `synchronous` even …
> Adding resume and cancel to Foreman Tasks

- nailgun/entities.py
- tests/test_entities.py
The tests are failing in 6.10.z due to missing `mirror_on_sync` in reading the repo entity as the `mirroring_policy` feature is cherrypicked to 6.10.z from 7.0
This PR allows both mirror_on_sync (the reading ignored) and mirroring_policy in 6.10.z. Keeping `mirror_on_sync` for 6.10.z wont fail the existing 6.10 tests.
> Mirror_on_sync (read ignored) and mirroring_policy for 6.10.z

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
Removing the python 3.6 checks from GitHub Actions since it was being used by InsightsQE CI to execute the FiFi/Insights tests using nailgun having the python 3.6 version but now they have moved to python 3.9!
> Removed py3.6 from checks as InsightsQE has updated to 3.9

- nailgun/entities.py
Just adding the `token` field in the Host class.
```
>>> entities.Host().search(query={'search': 'joey-altieri.vms.sat.rdu2.redhat.com'})[0].token
'6d361318-95e9-4d30-8543-bfa53242fd80'
```
I would like to use this field in a test where I would check rendered provisioning template for a puppet-specific content.
> Add token among host fields

- nailgun/entities.py
In #817 I added token among Host fields but didn't realize it's not returned every time on Host().create().
Adding to the ignore list now.
```
$ pytest tests/foreman/api/test_host.py::test_positive_end_to_end_with_puppet_class
============================================= test session starts =============================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.1
rootdir: /home/vsedmik/PycharmProjects/robottelo, configfile: pyproject.toml
plugins: forked-1.3.0, services-2.2.1, ibutsu-2.0.2, xdist-2.5.0, reportportal-5.0.11, mock-3.6.1
collected 1 item                                                                                              
tests/foreman/api/test_host.py . …
```
> Add token into the ignore list

- nailgun/entities.py
In #819 I added the token field to the ignore list as it caused problems for other host tests, but missed @tstrych's comment while being on PTO. Fixing it now.
The first test uses the `token` field, the second does not (it's not returned from SAT there), both passed.
```
(venv39) [vsedmik@localhost robottelo]$ pytest tests/foreman/api/test_puppetbootstrap.py tests/foreman/api/test_host.py::test_positive_end_to_end_with_puppet_class
=========================================================================================================== test session starts ===========================================================================================================
platform linux -- Python 3.9.9, pytest-6.2.5, py-1.10.0, pluggy-0.13.1 …
```
> Condition for token ignore

- nailgun/entities.py
In test fixes I need to replace `entities.OverrideValue(..).create()` with `default_sat.api.OverrideValue(..).create()`.
Without this the entity creation fails with `TypeError: __init__() got multiple values for argument 'server_config'`.
Robottelo classparam tests, original vs. fixed results:
```
tests/foreman/api/test_classparameters.py ...............F..FFFFFF.F..F
vs.
tests/foreman/api/test_classparameters.py .........................F...
```
(the last `F` is unrelated, fixed in https://github.com/SatelliteQE/robottelo/pull/9438)
> Fix override value

- nailgun/entities.py
There were more OS added to the list.  I've removed 'Debian' due to bz: 1709683.
> Add more OS to list for more coverage

- nailgun/entities.py
In test fixes replacing entities.Host(..).create() with session_puppet_enabled_sat.api.Host(..).create().
Without this the entity creation fails with TypeError: __init__() got multiple values for argument 'server_config'.
> Fix for compute resources-azure

- nailgun/entities.py
Adding option for SSL CA cert to repository entity. This option will be used in my upcoming PR for the convert2rhel feature in robottelo.
See linked robottelo PR.
> add ssl cert to repository

- nailgun/entities.py
Minor change to fix - **test_positive_tag_whitelist**
Limit sync tag parameter was earlier used for white listing of tags
which now is taken care of by include/exclude tags.
BZ : https://bugzilla.redhat.com/show_bug.cgi?id=2057782
BZ : https://bugzilla.redhat.com/show_bug.cgi?id=2057848
> Fix for container_management-content

- nailgun/entities.py
Add the support for Nutanix
POST /foreman_virt_who_configure/api/v2/configs | Create a virt-who configuration
`foreman_virt_who_configure_config[prism_flavor]optional , nil allowed | Select the Prism flavor you are connecting toValidations:Must be one of: central, element.`
> Add nutanix support

- nailgun/entities.py
update kubeconfig_path and hypervisor_server/username for kubevirt support
1. Add kubeconfig_path to support kubevirt
2. Update hypervisor_server and hypervisor_username to not required to support kubevirt and according apidoc
Kubevirt cases: Pass
https://satelliteserver/apidoc/v2/configs/create.html
```
foreman_virt_who_configure_config[hypervisor_server]optional , nil allowed | Fully qualified host name or IP address of the hypervisorValidations:String
-- | --
foreman_virt_who_configure_config[hypervisor_username]optional , nil allowed | Account name by which virt-who is to connect to the hypervisor.Validations:String
foreman_virt_who_configure_config[kubeconfig_path]optional , nil allowed | Configuration file containing details about how to connect to the cluster and authentication …
```
> Add kubeconfig_path and update hypervisor_server/username for kubevirt support

- nailgun/entities.py
- nailgun/entity_fields.py
Added a new entity class for Webhooks. There is quite a long list of events that are valid for creating a Webhook. The Satellite API returns them as a list from `/api/webhooks/events`. That is why I am updating the `event` field in the create function. I also had to change the entity_field for URLField in order to provide only URLs starting with `http`.
See /apidoc/v2/webhooks
```
[in] hook = entities.Webhooks().create()
[in] hook
[out] nailgun.entities.Webhooks(name='𘌫彩ꞗ𓄨叵', target_url='http://fbFPSQNDiy.org', http_method='POST', event='actions.remote_execution.run_host_job_succeeded.event.foreman', http_content_type='application/json', enabled=True, verify_ssl=True, ssl_ca_certs=None, user=None, http_headers=None, id=217)
[in] hook.name = 'test'
[in] hook.update(['name'])
[out] …
```
> Adding Webhooks entity

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/required_labels.yml
This PR adds the AutoCherryPick Github Actions for enforcing CherryPick labels and the cherrypick labeled PRs has been autocherrypicked to previous branches!
The parent PR to master should cherrypick PRs in n-2 branches , n-1 parent PR should open in n-1 branch and n-2 doesnt opens a cherrypick PR !
> Auto CherryPick commits to previous branches

- nailgun/entities.py
Realize the list subscription from organization. This requirement is from https://github.com/SatelliteQE/robottelo/pull/10017#discussion_r985645897
API doc:
GET /katello/api/organizations/:organization_id/subscriptions | List organization subscriptions
-- | --
[GET /katello/api/organizations/:organization_id/subscriptions](https://dell-per740-68-vm-09.lab.eng.pek2.redhat.com/apidoc/v2/subscriptions/index.en.html)	List organization subscriptions
As there the api is already exist in https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entities.py#L5101
So realize this method in api.Organization(id=default_org.id).subscriptions()
> Realize list subscription from Organization

- nailgun/entities.py
- tests/test_entities.py
Need to add a field for `build`, `location`, and `organization` to DiscoveredHost. `True` for build forces the host to boot into anaconda and install the kickstart repo. `False` will boot the host's default template. Default behavior is `False`.
See PUT /api/v2/discovered_hosts/:id
```
discovered_host.build = True
discovered_host.update(['build'])
```
> Adding build, org, and loc to discovered host

- .github/auto_assign.yml
- .github/workflows/auto_assignment.yaml
- .github/workflows/auto_cherry_pick.yml
Aligning AutoCherrypick GHA with Robottelo
- Mainly, switching to `https://github.com/jyejare/github-cherry-pick-action` from existing where we have new features satisfies our needs. One can see the recent commits we made after forking the original repo.
- Adding branch labels
- Assigning the autocherrypicked PR to original user
- Switching to the one branch per auto cherry-pick strategy from existing n-2
- Adding Notifications to GChat group improvement on failed auto cherrypick
- Adding Create issue on failed auto cherrypick
- [New] Added AutoAssign
> Alligning ACP GHA with Robottelo

- .github/auto_assign.yml
- .github/workflows/auto_assignment.yaml
- .github/workflows/auto_cherry_pick.yml
Cherrypick of commit: 17149a0d4e4b026072d8b6903094563eb80d8bda
Aligning AutoCherrypick GHA with Robottelo
- Mainly, switching to `https://github.com/jyejare/github-cherry-pick-action` from existing where we have new features satisfies our needs. One can see the recent commits we made after forking the original repo.
- Adding branch labels
- Assigning the autocherrypicked PR to original user
- Switching to the one branch per auto cherry-pick strategy from existing n-2
- Adding Notifications to GChat group improvement on failed auto cherrypick
- Adding Create issue on failed auto cherrypick
- [New] Added AutoAssign
> [6.11.z] Alligning ACP GHA with Robottelo

- tests/test_config.py
Unit tests for several PRs are failing with InvalidConfig issue. This PR only fixes that unit test.
> Fix unit tests for invalid config

- tests/test_config.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/867
Unit tests for several PRs are failing with InvalidConfig issue. This PR only fixes that unit test.
> [6.11.z] Fix unit tests for invalid config

- tests/test_config.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/867
Unit tests for several PRs are failing with InvalidConfig issue. This PR only fixes that unit test.
> [6.12.z] Fix unit tests for invalid config

- tests/test_config.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/867
Unit tests for several PRs are failing with InvalidConfig issue. This PR only fixes that unit test.
> [6.13.z] Fix unit tests for invalid config

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/866
Apidoc snippet:
```
job_invocation[inputs]optional , nil allowed | Inputs to useValidations:Hash
```
Usage:
```
job = entities.JobInvocation().run(
data={
'job_template_id': 89,
'inputs': {'command': 'ls'},
'targeting_type': 'static_query',
'search_query': f'name = {rhel7_contenthost.hostname}',
}
)
```
I came across this when I was trying to invoke an ansible job on a host, which raises an key error for not having an input.
> [6.13.z] Changing inputs as a optional parameter in job-invocation

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/866
Apidoc snippet:
```
job_invocation[inputs]optional , nil allowed | Inputs to useValidations:Hash
```
Usage:
```
job = entities.JobInvocation().run(
data={
'job_template_id': 89,
'inputs': {'command': 'ls'},
'targeting_type': 'static_query',
'search_query': f'name = {rhel7_contenthost.hostname}',
}
)
```
I came across this when I was trying to invoke an ansible job on a host, which raises an key error for not having an input.
> [6.12.z] Changing inputs as a optional parameter in job-invocation

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/866
Apidoc snippet:
```
job_invocation[inputs]optional , nil allowed | Inputs to useValidations:Hash
```
Usage:
```
job = entities.JobInvocation().run(
data={
'job_template_id': 89,
'inputs': {'command': 'ls'},
'targeting_type': 'static_query',
'search_query': f'name = {rhel7_contenthost.hostname}',
}
)
```
I came across this when I was trying to invoke an ansible job on a host, which raises an key error for not having an input.
> [6.11.z] Changing inputs as a optional parameter in job-invocation

- .github/workflows/auto_cherry_pick.yml
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
> No Cherrypick by default

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/874
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
> [6.11.z] No Cherrypick by default

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/874
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
> [6.13.z] No Cherrypick by default

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/874
Cherrypicking of Robottelo PR https://github.com/SatelliteQE/robottelo/pull/10436 that says:
```
By default the AutoCherrypicked PRs to labeled branches need not to again decide for auto-cherrypicking. The decision has should have already been made in parent PR itself as to what branch the PR will be cherrypicked and assigned branch labels.
```
> [6.12.z] No Cherrypick by default

- nailgun/entities.py
- from api/tests function of test_contentview.py at [line 1176](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_contentview.py#L1176) after call to read() get resolve auth values of "custom user" changes to "admin user". 
- server_config changed inside EntityReadMixin > read() [line 826](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L826)
- So the custom user with readonly role able to perform other operations on ContentView, operations like delete, update, publish and pramote.
> fix for ContentView server_config auth values

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/864
- from api/tests function of test_contentview.py at [line 1176](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_contentview.py#L1176) after call to read() get resolve auth values of "custom user" changes to "admin user". 
- server_config changed inside EntityReadMixin > read() [line 826](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L826)
- So the custom user with readonly role able to perform other operations on ContentView, operations like delete, update, publish and pramote.
> [6.12.z] fix for ContentView server_config auth values

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/864
- from api/tests function of test_contentview.py at [line 1176](https://github.com/SatelliteQE/robottelo/blob/master/tests/foreman/api/test_contentview.py#L1176) after call to read() get resolve auth values of "custom user" changes to "admin user". 
- server_config changed inside EntityReadMixin > read() [line 826](https://github.com/SatelliteQE/nailgun/blob/master/nailgun/entity_mixins.py#L826)
- So the custom user with readonly role able to perform other operations on ContentView, operations like delete, update, publish and pramote.
> [6.13.z] fix for ContentView server_config auth values

- nailgun/entities.py
- tests/test_entities.py
Small update to Ansible Nailgun PR recently merged, this properly sets the path to the endpoint it needs to point to.
> Change path to point to proper endpoint

- nailgun/entities.py
- tests/test_entities.py
#Cherry-picking #841 and #881 into 6.13
> Cherry-pick Ansible Role work to 6.13

- nailgun/entities.py
Email and project parameters are removed with the incoming of GCE as a plugin in 6.13 hence removing the params, also key_path is set to ignore as it's not getting collected in the response of API call
Signed-off-by: Adarsh Dubey <addubey@redhat.com>
> Feature changes for GCE plugin

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/886
Email and project parameters are removed with the incoming of GCE as a plugin in 6.13 hence removing the params, also key_path is set to ignore as it's not getting collected in the response of API call
Signed-off-by: Adarsh Dubey <addubey@redhat.com>
> [6.13.z] Feature changes for GCE plugin

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/automerge.yaml
Added support for automerge in the Nailgun repo
> added support for auto-merge in nailgun repo

- nailgun/entities.py
- nailgun/entity_mixins.py
`_poll_task` did check if the task succeeded, which caused a problem for negative tests where we want wait on the task to finish  but we expect failure. This pr adds a parameter to make this behavior configurable, the default is kept as it was, though no need to update existing callers.
Will provide a robottelo pr using the parameter.
[update] see https://github.com/SatelliteQE/robottelo/pull/10591
> poll for task intended to fail

- nailgun/entities.py
- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/888
`_poll_task` did check if the task succeeded, which caused a problem for negative tests where we want wait on the task to finish  but we expect failure. This pr adds a parameter to make this behavior configurable, the default is kept as it was, though no need to update existing callers.
Will provide a robottelo pr using the parameter.
[update] see https://github.com/SatelliteQE/robottelo/pull/10591
> [6.13.z] poll for task intended to fail

- nailgun/entities.py
Adding `choices` for `parameter_type` field as it was populating random string for parameter_type causing Networking tests to fail
```
$ pytest tests/foreman/api/test_subnet.py
========================================= test session starts =================================================================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: xdist-3.1.0, services-2.2.1, mock-3.10.0, cov-3.0.0, reportportal-5.1.3, ibutsu-2.2.4
collected 47 items / 7 deselected / 40 selected …
```
> Test fix for Networking tests

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/894
Adding `choices` for `parameter_type` field as it was populating random string for parameter_type causing Networking tests to fail
```
$ pytest tests/foreman/api/test_subnet.py
========================================= test session starts =================================================================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: xdist-3.1.0, services-2.2.1, mock-3.10.0, cov-3.0.0, reportportal-5.1.3, ibutsu-2.2.4
collected 47 items / 7 deselected / 40 selected …
```
> [6.12.z] Test fix for Networking tests

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/894
Adding `choices` for `parameter_type` field as it was populating random string for parameter_type causing Networking tests to fail
```
$ pytest tests/foreman/api/test_subnet.py
========================================= test session starts =================================================================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: xdist-3.1.0, services-2.2.1, mock-3.10.0, cov-3.0.0, reportportal-5.1.3, ibutsu-2.2.4
collected 47 items / 7 deselected / 40 selected …
```
> [6.13.z] Test fix for Networking tests

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/894
Adding `choices` for `parameter_type` field as it was populating random string for parameter_type causing Networking tests to fail
```
$ pytest tests/foreman/api/test_subnet.py
========================================= test session starts =================================================================
platform linux -- Python 3.11.1, pytest-7.2.1, pluggy-1.0.0
rootdir: /home/sganar/satellite/robottelo, configfile: pyproject.toml
plugins: xdist-3.1.0, services-2.2.1, mock-3.10.0, cov-3.0.0, reportportal-5.1.3, ibutsu-2.2.4
collected 47 items / 7 deselected / 40 selected …
```
> [6.11.z] Test fix for Networking tests

- nailgun/entities.py
Adding support for reading the Provisioning Template
**Reason for this addition**: There are several closed loop scenarios where we need to read the content of provisioning templates.
> Add support for reading a Provisioning Template

- nailgun/entities.py
ahv_internal_debug option support for virt-who configuration
https://<satellite-server>/apidoc/v2/configs/create.en.html
```
foreman_virt_who_configure_config[ahv_internal_debug]optional , nil allowed | Option Enable debugging output is required to enable AHV internal debug. It provides extra AHV debug information when both options are enabledValidations:Must be one of: true, false, 1, 0.
-- | --
```
Can create  and update this option virt-who configuration
target_sat.api.VirtWhoConfig(**form_data).create()
virtwho_config.update(['ahv_internal_debug'])
Example:
```
target_sat.api.VirtWhoConfig(**form_data).create()
virtwho_config.update(['ahv_internal_debug'])
```
Test cases :PASS 
```
(robottelo_vv) [yanpliu@yanpliu robottelo]$ pytest ./tests/foreman/virtwho/api/test_nutanix.py -k …
```
> ahv_internal_debug option support for virt-who configuration

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/889
ahv_internal_debug option support for virt-who configuration
https://<satellite-server>/apidoc/v2/configs/create.en.html
```
foreman_virt_who_configure_config[ahv_internal_debug]optional , nil allowed | Option Enable debugging output is required to enable AHV internal debug. It provides extra AHV debug information when both options are enabledValidations:Must be one of: true, false, 1, 0.
-- | --
```
Can create  and update this option virt-who configuration
target_sat.api.VirtWhoConfig(**form_data).create()
virtwho_config.update(['ahv_internal_debug'])
Example:
```
target_sat.api.VirtWhoConfig(**form_data).create()
virtwho_config.update(['ahv_internal_debug'])
```
Test cases :PASS 
```
(robottelo_vv) [yanpliu@yanpliu …
```
> [6.13.z] ahv_internal_debug option support for virt-who configuration

- nailgun/entities.py
- tests/test_entities.py
Ignore puppetclass attribute if Puppet is enabled, but the host does not have Puppet proxy assigned.
None
> Ignore puppetclass attribute conditionally

- nailgun/entities.py
- tests/test_entities.py
Adds support for /katello/api/alternate_content_sources endpoints. 
https://{SAT}/apidoc/v2/alternate_content_sources.en.html
```
$ pytest tests/foreman/api/test_acs.py
==================================== test session starts ====================================
platform linux -- Python 3.10.10, pytest-7.2.2, pluggy-1.0.0
plugins: services-2.2.1, forked-1.4.0, ibutsu-2.2.4, mock-3.10.0, xdist-3.2.1, reportportal-
collected 7 items
tests/foreman/api/test_acs.py .....s.                                                 [100%]
===================================== warnings summary ======================================
```
> Add AlternateContentSource entity

- nailgun/entities.py
Added new method `nailgun.entities.Host::list_provisioning_templates`
which returns all provisioning templates assigned to a host.
Local documentation via Satellite apidoc:
https://satellite.example.com/apidoc/v2/hosts/templates.en.html
Example:
```
In [1]: from nailgun.entities import Host
In [2]: host = Host(host='sat.instance.addr.com', id='snap_uuid').read()
In [3]: print([template['name'] for template in host.list_provisioning_templates()])
Out [3]: ['Kickstart default finish', 'Linux host_init_config default', ...] …
```
> host: add support for reading provisioning templates

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/911
Adds support for /katello/api/alternate_content_sources endpoints. 
https://{SAT}/apidoc/v2/alternate_content_sources.en.html
```
$ pytest tests/foreman/api/test_acs.py
==================================== test session starts ====================================
platform linux -- Python 3.10.10, pytest-7.2.2, pluggy-1.0.0
plugins: services-2.2.1, forked-1.4.0, ibutsu-2.2.4, mock-3.10.0, xdist-3.2.1, reportportal-
collected 7 items
tests/foreman/api/test_acs.py .....s.                                                 [100%]
===================================== warnings summary ======================================
```
> [6.13.z] Add AlternateContentSource entity

- requirements-dev.txt
~~codecov is no longer in PyPI.~~
UPDATE: codecov==2.1.12 has been removed from PyPI but developers uploaded
newer version 2.1.13 for those who still need it - like nailgun does.
More info:
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> Upgrade codecov dependency

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/906
Ignore puppetclass attribute if Puppet is enabled, but the host does not have Puppet proxy assigned.
None
> [6.12.z] Ignore puppetclass attribute conditionally

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/906
Ignore puppetclass attribute if Puppet is enabled, but the host does not have Puppet proxy assigned.
None
> [6.13.z] Ignore puppetclass attribute conditionally

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/906
Ignore puppetclass attribute if Puppet is enabled, but the host does not have Puppet proxy assigned.
None
> [6.11.z] Ignore puppetclass attribute conditionally

- nailgun/entities.py
New field `filters_applied` is returned by CVV entitiy in 6.14 and I would use it for new tests.
https://github.com/Katello/katello/pull/10527
```
In [1]: from robottelo.hosts import Satellite
In [2]: sat = Satellite('<SAT_FQDN>')
In [3]: sat.api.ContentViewVersion(id=1).read()
Out[3]: robottelo.hosts.DecClass(content_view=nailgun.entities.ContentView(id=1), description=None, environment=[nailgun.entities.LifecycleEnvironment(id=1)], errata_counts={'security': 3, 'bugfix': 0, 'enhancement': 1, 'total': 4}, file_count=0, filters_applied=None, major=1, minor=0, module_stream_count=0, package_count=0, repository=[nailgun.entities.Repository(id=1)], version='1.0', id=1)
In [4]: sat.api.ContentViewVersion(id=9).read()
Out[4]: robottelo.hosts.DecClass(content_view=nailgun.entities.ContentView(id …
```
> Add filters_applied field

- .github/workflows/dispatch_release.yml
Now, the release for changelogs will be tagged in this repo from the SatQE CI job.
How?
--------
1. Upon receiving UMB message for the new snap for a major downstream release in development, the CI job triggers.
2. The CI job sends an HTTP dispatch request to the `auto release` workflow in this repo (created in this PR)
3. Upon receiving the HTTP request, the workflow runs with new tag name and creates a new tag in the repo.
4. The same tag is then used to create a new release with automatic release notes.
So all the releases here would now be automatically created.
> Auto Release Nailgun

- .github/workflows/auto_cherry_pick.yml
Now Autocherrypick the merged PR by adding a branch and/or CherryPick label.
> AutoCherrypick of Merged PRs

- nailgun/entities.py
- nailgun/entity_mixins.py
Cherrypick of  #888, requested to fix some issues in upgrade scenarios. No need to update callers in 6.12 robotello branch as the default is kept the same
> [6.12.z] poll for task intended to fail

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/914
~~codecov is no longer in PyPI.~~
UPDATE: codecov==2.1.12 has been removed from PyPI but developers uploaded
newer version 2.1.13 for those who still need it - like nailgun does.
More info:
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> [6.13.z] Upgrade codecov dependency

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/914
~~codecov is no longer in PyPI.~~
UPDATE: codecov==2.1.12 has been removed from PyPI but developers uploaded
newer version 2.1.13 for those who still need it - like nailgun does.
More info:
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> [6.12.z] Upgrade codecov dependency

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/914
~~codecov is no longer in PyPI.~~
UPDATE: codecov==2.1.12 has been removed from PyPI but developers uploaded
newer version 2.1.13 for those who still need it - like nailgun does.
More info:
https://about.codecov.io/blog/message-regarding-the-pypi-package/
> [6.11.z] Upgrade codecov dependency

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/923
Add cacert to .fields in http_proxy, which is the path within the host to the cacert for the proxy.
Supports robottelo PR# [11454](https://github.com/SatelliteQE/robottelo/pull/11454)
> [6.13.z] Add cacert to .fields in HttpProxy

- nailgun/entities.py
- tests/test_entities.py
Adds helper to disassociate lifecycle environment from a capsule
<sat>/apidoc/v2/capsule_content.en.html
```
$ pytest tests/foreman/api/test_capsulecontent.py::TestCapsuleContentManagement::test_positive_remove_capsule_orphans
=================================================================== test session starts ===================================================================
...
collected 1 item                                                                                                                                          
tests/foreman/api/test_capsulecontent.py .                                                                                                          [100%]
======================================================== 1 passed, 1 warning in 111.38s (0:01:51) …
```
> Add helper to delete LCE from capsule

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/935
Adds helper to disassociate lifecycle environment from a capsule
<sat>/apidoc/v2/capsule_content.en.html
```
$ pytest tests/foreman/api/test_capsulecontent.py::TestCapsuleContentManagement::test_positive_remove_capsule_orphans
=================================================================== test session starts ===================================================================
...
collected 1 item                                                                                                                                          
tests/foreman/api/test_capsulecontent.py .                                                                                                          [100%] …
```
> [6.14.z] Add helper to delete LCE from capsule

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/935
Adds helper to disassociate lifecycle environment from a capsule
<sat>/apidoc/v2/capsule_content.en.html
```
$ pytest tests/foreman/api/test_capsulecontent.py::TestCapsuleContentManagement::test_positive_remove_capsule_orphans
=================================================================== test session starts ===================================================================
...
collected 1 item                                                                                                                                          
tests/foreman/api/test_capsulecontent.py .                                                                                                          [100%] …
```
> [6.13.z] Add helper to delete LCE from capsule

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/920
This PR adds Nailgun support for RHCloud Cloud Connector API.
This feature is tested with Robottelo test tests/foreman/api/test_rhc.py::test_positive_configure_cloud_connector,
see https://github.com/SatelliteQE/robottelo/pull/11395 PRT run.
```
result = module_target_sat.api.RHCloud().enable_connector(organization_id=module_rhc_org.id)
print(result)
{'id': 4, 'targeting_id': 4, 'job_category': 'Maintenance Operations', 'task_id': '97612455-60d8-45e4-904f-d7b067b9e74f', 'task_group_id': 16, 'triggering_id': 4, 'description': 'Configure Cloud Connector', 'concurrency_level': None, 'time_span': None, 'execution_timeout_interval': None, 'password': None, 'key_passphrase': None, 'remote_execution_feature_id': 17, …
```
> [6.13.z] Add support for RHCloud Cloud Connector

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
Added TablePreferences entity.
Shouldn't cause regression, this test uses search and hasn't changed:
```
$ pytest tests/foreman/api/test_contentview.py::test_positive_admin_user_actions
================================================================= test session starts =================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/lhellebr/git/robottelo/venv/bin/python
Mandatory Requirements Available: jinja2==3.1.2 broker[docker]==0.3.2 pytest-xdist==3.3.1 wrapanapi==3.5.15 requests==2.31.0 pytest-reportportal==5.1.8
Optional Requirements Available: pre-commit==3.3.2 redis==4.5.5 manage>=0.1.13 sphinx==7.0.1
cachedir: .pytest_cache
rootdir: …
```
> Add TablePreferences entity

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/928
Added TablePreferences entity.
Shouldn't cause regression, this test uses search and hasn't changed:
```
$ pytest tests/foreman/api/test_contentview.py::test_positive_admin_user_actions
================================================================= test session starts =================================================================
platform linux -- Python 3.9.16, pytest-7.3.1, pluggy-1.0.0 -- /home/lhellebr/git/robottelo/venv/bin/python
Mandatory Requirements Available: jinja2==3.1.2 broker[docker]==0.3.2 pytest-xdist==3.3.1 wrapanapi==3.5.15 requests==2.31.0 pytest-reportportal==5.1.8
Optional Requirements Available: pre-commit==3.3.2 redis==4.5.5 manage>=0.1.13 sphinx==7.0.1
cachedir: .pytest_cache
shared_function …
```
> [6.14.z] Add TablePreferences entity

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/930
Example:
```
```
> [6.14.z] fixed the cherry pick GHA

- nailgun/entities.py
- tests/test_entities.py
Add a method to play ansible roles on a host.
Example:
```
host = api.Host().search(query={'search': f'name={rex_contenthost.hostname}'})[0]
host.play_roles()
```
> Play ansible roles on host

- nailgun/entities.py
Subset of https://github.com/SatelliteQE/nailgun/pull/929/
> Adding entity mixins classes

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/949
null
> [6.14.z] remove g-chat notification for failed auto cherrypick, handled in slack

- .github/workflows/auto_cherry_pick.yml
> [6.13.z] - remove g-chat notification for failed auto-cherrypick, handled in slack

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/936
Add a method to play ansible roles on a host.
Example:
```
host = api.Host().search(query={'search': f'name={rex_contenthost.hostname}'})[0]
host.play_roles()
```
> [6.14.z] Play ansible roles on host

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of https://github.com/SatelliteQE/nailgun/pull/936
> [6.13] Play ansible roles on host

- .github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/961
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the specific branch workflow that updates the …
> [6.14.z] Trigger robottelo image update workflow on merge

- .github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/961
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the specific branch workflow that updates the …
> [6.11.z] Trigger robottelo image update workflow on merge

- .github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/961
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the specific branch workflow that updates the …
> [6.12.z] Trigger robottelo image update workflow on merge

- .github/workflows/trigger_robottelo_workflow.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/961
Problem statement: Currently, the Robottelo image is only updated when a Robottelo PR is merged, which means that it won't be updated if there are any changes merged in Airgun/Nailgun. This can cause issues when running automation as it might not have the latest code changes from these repositories.
Solution: We can add a new [workflow_dispatch](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#workflow_dispatch) trigger that [listens for any changes](https://docs.github.com/en/rest/actions/workflows?apiVersion=2022-11-28#create-a-workflow-dispatch-event) in the Airgun/Nailgun repositories. When any PR is merged in those repos, the trigger will run the specific branch workflow that updates the …
> [6.13.z] Trigger robottelo image update workflow on merge

- nailgun/entities.py
pxe_loader  option already exist for HG, but was missing for Host.
Dependant PR for https://github.com/SatelliteQE/robottelo/pull/11940
> Add pxe_loader to Host

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/967
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
> [6.14.z] Remove Python 3.9 support from nailgun

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/967
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
> [6.13.z] Remove Python 3.9 support from nailgun

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/967
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
> [6.12.z] Remove Python 3.9 support from nailgun

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/967
As discussed on slack, we are removing support for Python 3.9 from our frameworks.
> [6.11.z] Remove Python 3.9 support from nailgun

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/966
pxe_loader  option already exist for HG, but was missing for Host.
Dependant PR for https://github.com/SatelliteQE/robottelo/pull/11940
> [6.11.z] Add pxe_loader to Host

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/966
pxe_loader  option already exist for HG, but was missing for Host.
Dependant PR for https://github.com/SatelliteQE/robottelo/pull/11940
> [6.14.z] Add pxe_loader to Host

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/966
pxe_loader  option already exist for HG, but was missing for Host.
Dependant PR for https://github.com/SatelliteQE/robottelo/pull/11940
> [6.13.z] Add pxe_loader to Host

- nailgun/entities.py
I was facing ` TypeError: DiscoveryRule.__init__() got multiple values for argument 'server_config'` as I started using sat object in the test scenarios.
> Changing return value for Discovery create method

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/978
I was facing ` TypeError: DiscoveryRule.__init__() got multiple values for argument 'server_config'` as I started using sat object in the test scenarios.
> [6.12.z] Changing return value for Discovery create method

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/978
I was facing ` TypeError: DiscoveryRule.__init__() got multiple values for argument 'server_config'` as I started using sat object in the test scenarios.
> [6.14.z] Changing return value for Discovery create method

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/978
I was facing ` TypeError: DiscoveryRule.__init__() got multiple values for argument 'server_config'` as I started using sat object in the test scenarios.
> [6.13.z] Changing return value for Discovery create method

- .coveragerc
- .flake8
- .gitignore
- .pre-commit-config.yaml
- docs/conf.py
- docs/create_user_nailgun.py
- docs/create_user_plain.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- requirements-dev.txt
- setup.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
This change adds Ruff as the new linter and loosens Black's formatting as well.
Due to this change, we can drop flake8 and old pre-commit hooks.
> Introduce new project code standards

- .coveragerc
- .flake8
- .gitignore
- .pre-commit-config.yaml
- docs/conf.py
- docs/create_user_nailgun.py
- docs/create_user_plain.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- requirements-dev.txt
- setup.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/977
This change adds Ruff as the new linter and loosens Black's formatting as well.
Due to this change, we can drop flake8 and old pre-commit hooks.
> [6.14.z] Introduce new project code standards

- .coveragerc
- .flake8
- .gitignore
- .pre-commit-config.yaml
- docs/conf.py
- docs/create_user_nailgun.py
- docs/create_user_plain.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- requirements-dev.txt
- setup.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
This change adds Ruff as the new linter and loosens Black's formatting as well.
Due to this change, we can drop flake8 and old pre-commit hooks.
fixes #985
> [6.12.z] Introduce new project code standards (#977)

- .coveragerc
- .flake8
- .gitignore
- .pre-commit-config.yaml
- docs/conf.py
- docs/create_user_nailgun.py
- docs/create_user_plain.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- requirements-dev.txt
- setup.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
This change adds Ruff as the new linter and loosens Black's formatting as well.
Due to this change, we can drop flake8 and old pre-commit hooks.
fixes #984
> [6.13.z] Introduce new project code standards (#977)

- .github/workflows/pull_requests.yml
- .pre-commit-config.yaml
This PR removes [pre-commit/action](https://github.com/pre-commit/action) in favor of [pre-commit.ci](https://github.com/apps/pre-commit-ci) that was enabled on the nailgun repository by @JacobCallahan.
> Remove pre-commit GH action

- docs/create_user_plain.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Most rules are used, but a few are ignored for style.
> Introduce docstring standards for Ruff

- docs/create_user_plain.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/994
Most rules are used, but a few are ignored for style.
> [6.14.z] Introduce docstring standards for Ruff

- docs/create_user_plain.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- pyproject.toml
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Most rules are used, but a few are ignored for style.
fixes #1008
> [6.13.z] Introduce docstring standards for Ruff

- .github/workflows/pull_requests.yml
- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/997
This PR removes [pre-commit/action](https://github.com/pre-commit/action) in favor of [pre-commit.ci](https://github.com/apps/pre-commit-ci) that was enabled on the nailgun repository by @JacobCallahan.
> [6.14.z] Remove pre-commit GH action

- .github/workflows/pull_requests.yml
- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/997
This PR removes [pre-commit/action](https://github.com/pre-commit/action) in favor of [pre-commit.ci](https://github.com/apps/pre-commit-ci) that was enabled on the nailgun repository by @JacobCallahan.
> [6.13.z] Remove pre-commit GH action

- .github/workflows/pull_requests.yml
- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/997
This PR removes [pre-commit/action](https://github.com/pre-commit/action) in favor of [pre-commit.ci](https://github.com/apps/pre-commit-ci) that was enabled on the nailgun repository by @JacobCallahan.
> [6.12.z] Remove pre-commit GH action

- nailgun/entities.py
- tests/test_entities.py
This PR adds
1. support for capsule content count endpoints added in 6.15/stream
2. a few fields that appear useful to me and API returns them already
https://<<SAT_FQDN>>/apidoc/v2/capsule_content.en.html
```
In [1]: from robottelo.hosts import Satellite
In [2]: sat = Satellite('satellite.redhat.com')
In [3]: ngc = sat.api.Capsule().search(query={'search': f'name=capsule.redhat.com'})[0]
In [4]: ngc.content_counts()
Out[4]: 
{'content_view_versions': {'4': {'repositories': {'4': {'rpm': 58,
'erratum': 32,
'rpm.repo_metadata_file': 1},
'10': {'rpm': 32,
'erratum': 4,
'package_group': 2,
'rpm.packagecategory': 1}},
'cv_version_content_counts': {'rpm': 90,
'erratum': 36,
'package_group': 2,
'rpm.packagecategory': 1,
'rpm.repo_metadata_file': 1}}}}
In [5]: ngc.content_update_counts()
Out[5]: …
```
> Add support for capsule content counts

- nailgun/entities.py
`GET /katello/api/content_view_versions/:id` returns more fields than we collected. This PR just adds those content-counts related.
```
$ curl -sku admin:changeme https://satellite.redhat.com/katello/api/content_view_versions/34 | jq | grep count
"host_count": 0,
"activation_key_count": 0
"host_count": 0,
"activation_key_count": 1
"ansible_collection_count": 2,
"docker_manifest_count": 152,
"docker_manifest_list_count": 18,
"docker_tag_count": 24,
"file_count": 3,
"rpm_count": 36,
"modulemd_count": 7,
"erratum_count": 6,
"package_group_count": 2,
"srpm_count": 0,
"module_stream_count": 7,
"package_count": 36,
"component_view_count": 0,
"ansible_collection_repository_count": 1,
"docker_repository_count": 1,
"file_repository_count": 1,
"yum_repository_count": 1,
"errata_counts": {
```
``` …
```
> Add missing counts provided by CVV endpoint

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1019
`GET /katello/api/content_view_versions/:id` returns more fields than we collected. This PR just adds those content-counts related.
```
$ curl -sku admin:changeme https://satellite.redhat.com/katello/api/content_view_versions/34 | jq | grep count
"host_count": 0,
"activation_key_count": 0
"host_count": 0,
"activation_key_count": 1
"ansible_collection_count": 2,
"docker_manifest_count": 152,
"docker_manifest_list_count": 18,
"docker_tag_count": 24,
"file_count": 3,
"rpm_count": 36,
"modulemd_count": 7,
"erratum_count": 6,
"package_group_count": 2,
"srpm_count": 0,
"module_stream_count": 7,
"package_count": 36,
"component_view_count": 0,
"ansible_collection_repository_count": 1,
"docker_repository_count": 1, …
```
> [6.14.z] Add missing counts provided by CVV endpoint

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/996
**PR Description**
This PR addresses an issue related to out-of-memory errors during the execution of GitHub Actions workflows. To mitigate this problem, we're introducing a step to set up swap space.
- Added a new step to the workflow that sets up swap space with a size of 10GB.
In certain resource-intensive workflows, such as those involving large builds or data processing tasks, GitHub Actions runners may encounter out-of-memory errors. These errors can disrupt the workflow and cause it to fail.
To avoid such errors and ensure the smooth execution of workflows, we have introduced a step that configures a swap space of 10GB. Swap space provides additional virtual memory, which can be used when the physical memory is …
> [6.14.z] fixing the memory issue in auto-cherry-pick GHA

- nailgun/entities.py
Getting TypeError: Webhooks.__init__() got multiple values for argument 'server_config' after the move from entities.Webhook to target_sat.api.Webhook. 
(https://github.com/SatelliteQE/robottelo/pull/13060#issuecomment-1803465554)
https://github.com/SatelliteQE/robottelo/pull/13048
Removing the call to find the class indirectly and changing to direct call as other entities
> fixed the type error for some remaining entities

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1029
Getting TypeError: Webhooks.__init__() got multiple values for argument 'server_config' after the move from entities.Webhook to target_sat.api.Webhook. 
(https://github.com/SatelliteQE/robottelo/pull/13060#issuecomment-1803465554)
https://github.com/SatelliteQE/robottelo/pull/13048
Removing the call to find the class indirectly and changing to direct call as other entities
> [6.14.z] fixed the type error for some remaining entities

- .pre-commit-config.yaml
backport of #1037 
- [github.com/astral-sh/ruff-pre-commit: v0.1.6 → v0.1.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.1.6...v0.1.7)
> [6.15.z] [pre-commit.ci] pre-commit autoupdate 

- .pre-commit-config.yaml
This commit brings the 6.15.z branch in-line with master, resolving conflicts with cherry-picks.
fixes #1045
> [6.15.z] Updates to .pre-commit-config.yaml

- nailgun/entities.py
- tests/test_entities.py
- Support new API endpoint, ACS:`bulk/refresh_all` with method named `bulk_refresh_all()`
- This endpoint was added in 
https://github.com/Katello/katello/pull/10646
- We can still use `.bulk_refresh(data={'ids': acs_id_list})` to refresh only a specific set of ACSs
- The new option is intended to refresh all ACSs present without specific `ids` being passed.
``` 
[SETUP] Multiple ACSs created and refreshed once, then ...
[IN] (Pdb) module_target_sat.api.AlternateContentSource().bulk_refresh_all()
[OUT] {'id': '39c86797-e657-491a-aa8d-a5b3f4d38727', 'label': 'Actions::BulkAction', 'pending': False, 
'action': 'Refresh Alternate Content Source refresh alternate content source; ...', 'username': 'admin', 
'started_at': '2024-01-31 19:27:06 UTC', 'ended_at': '2024-01-31 19:27:38 UTC', …
```
> New API endpoint for bulk/refresh all ACSs

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1086
- Support new API endpoint, ACS:`bulk/refresh_all` with method named `bulk_refresh_all()`
- This endpoint was added in 
https://github.com/Katello/katello/pull/10646
- We can still use `.bulk_refresh(data={'ids': acs_id_list})` to refresh only a specific set of ACSs
- The new option is intended to refresh all ACSs present without specific `ids` being passed.
``` 
[SETUP] Multiple ACSs created and refreshed once, then ...
[IN] (Pdb) module_target_sat.api.AlternateContentSource().bulk_refresh_all()
[OUT] {'id': '39c86797-e657-491a-aa8d-a5b3f4d38727', 'label': 'Actions::BulkAction', 'pending': False, 
'action': 'Refresh Alternate Content Source refresh alternate content source; ...', 'username': 'admin', 
'started_at': …
```
> [6.15.z] New API endpoint for bulk/refresh all ACSs

- nailgun/entity_mixins.py
> update entity object with parametrized server_config rather default

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1106
```
```
> [6.15.z] update entity object with parametrized server_config rather default

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1106
```
```
> [6.13.z] update entity object with parametrized server_config rather default

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1106
```
```
> [6.14.z] update entity object with parametrized server_config rather default

- nailgun/entities.py
- tests/test_entities.py
Adds support for the Capsule `reclaim_space` endpoint.
See the apidoc for Capsule_content.
In robottelo [PR#14397](https://github.com/SatelliteQE/robottelo/pull/14397).
> Add support for the reclaim_space endpoint

- .codecov.yml
- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- Makefile
- pyproject.toml
- requirements-dev.txt
This continues a trend we've done with other projects. Codecov has some use in other types of projects, but really isn't a good fit for Nailgun since it is functionally exercised by Robottelo.
Without getting too deep into philosophy, CodeCov is a misleading metric for quality and minor changes are largely ignored in mature projects.
> Remove codecov

- .github/workflows/prt_labels.yml
- .github/workflows/prt_result.yml
1. Add the dispatch workflow that takes care of this thing from the Jenkins CI update the GitHub comment …
> adding the PRT result and labels on github comment

- nailgun/entities.py
- tests/test_entities.py
Added new entity `NotificationRecipients` for `/notification_recipients` endpoint.
This PR is required by https://github.com/SatelliteQE/robottelo/pull/14592
> new entity NotificationRecipients

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1118
Added new entity `NotificationRecipients` for `/notification_recipients` endpoint.
This PR is required by https://github.com/SatelliteQE/robottelo/pull/14592
> [6.15.z] new entity NotificationRecipients

- .github/workflows/prt_labels.yml
- .github/workflows/prt_result.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1089
1. Add the dispatch workflow that takes …
> [6.15.z] adding the PRT result and labels on github comment

- .github/workflows/prt_labels.yml
- .github/workflows/prt_result.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1089
1. Add the dispatch workflow that takes …
> [6.14.z] adding the PRT result and labels on github comment

- .github/workflows/prt_labels.yml
- .github/workflows/prt_result.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1089
1. Add the dispatch workflow that takes …
> [6.13.z] adding the PRT result and labels on github comment

- .github/workflows/prt_labels.yml
- .github/workflows/prt_result.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1089
1. Add the dispatch workflow that takes …
> [6.12.z] adding the PRT result and labels on github comment

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1106
```
```
> [6.12.z] update entity object with parametrized server_config rather default

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1118
Added new entity `NotificationRecipients` for `/notification_recipients` endpoint.
This PR is required by https://github.com/SatelliteQE/robottelo/pull/14592
> [6.14.z] new entity NotificationRecipients

- .codecov.yml
- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- Makefile
- pyproject.toml
- requirements-dev.txt
Codecov was removed from master as its no longer required in PR https://github.com/SatelliteQE/nailgun/pull/1102
We're missing this changes in zstream branches and codecov checks fails on zstream PRs, so removing this from all supported branches
Example: https://github.com/SatelliteQE/nailgun/pull/1124
> [6.15.z] Remove codecov

- .codecov.yml
- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- Makefile
- pyproject.toml
- requirements-dev.txt
**Description of changes**
Codecov was removed from master as its no longer required in PR https://github.com/SatelliteQE/nailgun/pull/1102
We're missing this changes in zstream branches and codecov checks fails on zstream PRs, so removing this from all supported branches
Example: https://github.com/SatelliteQE/nailgun/pull/1124
> [6.13.z]Remove codecov

- .codecov.yml
- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- Makefile
- pyproject.toml
- requirements-dev.txt
**Description of changes**
Codecov was removed from master as its no longer required in PR https://github.com/SatelliteQE/nailgun/pull/1102
We're missing this changes in zstream branches and codecov checks fails on zstream PRs, so removing this from all supported branches
Example: https://github.com/SatelliteQE/nailgun/pull/1124
> [6.12.z] Remove codecov

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
```
RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ.","errors":["Task c7fa616b-2f71-4476-b581-1cae65a9eafd: RuntimeError: The repository's publication is missing. Please run a 'complete …
```
> Add json response to entity creation error message

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1119
```
RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ.","errors":["Task c7fa616b-2f71-4476-b581-1cae65a9eafd: RuntimeError: …
```
> [6.15.z] Add json response to entity creation error message

- nailgun/entities.py
Missing outputs, rerun, cancel endpoints in JobInvocation entity
```
In [28]: result = sat.api.JobInvocation(id=20).outputs()
In [29]: [i for i in result['outputs'][0]['output'] if i['output'] == 'Exit status: 0']
Out[29]:
[{'output_type': 'stdout',
'output': 'Exit status: 0',
'timestamp': 1715268351.528926}]
```
> Add outputs, rerun, cancel endpoints in JobInvocation entity

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1139
Missing outputs, rerun, cancel endpoints in JobInvocation entity
```
In [28]: result = sat.api.JobInvocation(id=20).outputs()
In [29]: [i for i in result['outputs'][0]['output'] if i['output'] == 'Exit status: 0']
Out[29]:
[{'output_type': 'stdout',
'output': 'Exit status: 0',
'timestamp': 1715268351.528926}]
```
> [6.15.z] Add outputs, rerun, cancel endpoints in JobInvocation entity

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1139
Missing outputs, rerun, cancel endpoints in JobInvocation entity
```
In [28]: result = sat.api.JobInvocation(id=20).outputs()
In [29]: [i for i in result['outputs'][0]['output'] if i['output'] == 'Exit status: 0']
Out[29]:
[{'output_type': 'stdout',
'output': 'Exit status: 0',
'timestamp': 1715268351.528926}]
```
> [6.14.z] Add outputs, rerun, cancel endpoints in JobInvocation entity

- nailgun/entities.py
Before this PR, the entity classes that override the `EntityCreateMixin.create` method return a new instance of the `nailgun.entities.ENTITY` class. In robottelo, which wraps each entity class in  the `robottelo.hosts.DecClass` class, this causes test failures, because `satellite.api.ENTITY().create()` returns an instance of `robottelo.hosts.DecClass` for some classes and `nailgun.entities.ENTITY` instances for others.
This PR updates those `create` methods to return an instance of `type(self)` instead of explicitly naming the class, so that an the same subclass / decorated class is used.
No functionality changes.
> Use type(self) instead of entity class name in create methods

- docs/create_organization_nailgun.py
- docs/create_user_nailgun.py
- docs/index.rst
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
Update all entity initialization calls to pass `server_config` as a named kwarg instead of as a positional arg.
Fixes https://github.com/SatelliteQE/nailgun/issues/1038
```
pytest_fixtures/component/taxonomy.py:43: in module_org
return module_target_sat.api.Organization().create()
../../lib64/python3.12/site-packages/nailgun/entities.py:5803: in create
return type(self)(
E   TypeError: Organization.__init__() got multiple values for argument 'server_config'
```
nailgun tests:
```
............................................................................................................................................................................................................................................... …
```
> Use server_config as named argument only

- nailgun/entity_mixins.py
Update `Entity.__eq__` to check for class compatibility in both directions. This fixes robottelo test errors that occur when comparing a `nailgun.entities.User` instance against an instance of robottelo's wrapper class `robottelo.hosts.DecClass`:
```
14:46:30      @pytest.mark.tier2
14:46:30      def test_positive_create_and_update_with_user(
14:46:30          module_org, module_location, module_user, module_target_sat
14:46:30      ):
14:46:30          """Create and update host with user specified
14:46:30      
14:46:30          :id: 72e20f8f-17dc-4e38-8ac1-d08df8758f56
14:46:30      
14:46:30          :expectedresults: A host is created and updated with expected user assigned
14:46:30          """
14:46:30          host = module_target_sat.api.Host(
14:46:30 …
```
> Update Entity.__eq__ isinstance check to work in either direction

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1143
Before this PR, the entity classes that override the `EntityCreateMixin.create` method return a new instance of the `nailgun.entities.ENTITY` class. In robottelo, which wraps each entity class in  the `robottelo.hosts.DecClass` class, this causes test failures, because `satellite.api.ENTITY().create()` returns an instance of `robottelo.hosts.DecClass` for some classes and `nailgun.entities.ENTITY` instances for others.
This PR updates those `create` methods to return an instance of `type(self)` instead of explicitly naming the class, so that an the same subclass / decorated class is used.
No functionality changes.
> [6.14.z] Use type(self) instead of entity class name in create methods

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1143
Before this PR, the entity classes that override the `EntityCreateMixin.create` method return a new instance of the `nailgun.entities.ENTITY` class. In robottelo, which wraps each entity class in  the `robottelo.hosts.DecClass` class, this causes test failures, because `satellite.api.ENTITY().create()` returns an instance of `robottelo.hosts.DecClass` for some classes and `nailgun.entities.ENTITY` instances for others.
This PR updates those `create` methods to return an instance of `type(self)` instead of explicitly naming the class, so that an the same subclass / decorated class is used.
No functionality changes.
> [6.15.z] Use type(self) instead of entity class name in create methods

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1153
Update `Entity.__eq__` to check for class compatibility in both directions. This fixes robottelo test errors that occur when comparing a `nailgun.entities.User` instance against an instance of robottelo's wrapper class `robottelo.hosts.DecClass`:
```
14:46:30      @pytest.mark.tier2
14:46:30      def test_positive_create_and_update_with_user(
14:46:30          module_org, module_location, module_user, module_target_sat
14:46:30      ):
14:46:30          """Create and update host with user specified
14:46:30      
14:46:30          :id: 72e20f8f-17dc-4e38-8ac1-d08df8758f56
14:46:30      
14:46:30          :expectedresults: A host is created and updated with expected user assigned
14:46:30          """
14:46:30          host …
```
> [6.13.z] Update Entity.__eq__ isinstance check to work in either direction

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1153
Update `Entity.__eq__` to check for class compatibility in both directions. This fixes robottelo test errors that occur when comparing a `nailgun.entities.User` instance against an instance of robottelo's wrapper class `robottelo.hosts.DecClass`:
```
14:46:30      @pytest.mark.tier2
14:46:30      def test_positive_create_and_update_with_user(
14:46:30          module_org, module_location, module_user, module_target_sat
14:46:30      ):
14:46:30          """Create and update host with user specified
14:46:30      
14:46:30          :id: 72e20f8f-17dc-4e38-8ac1-d08df8758f56
14:46:30      
14:46:30          :expectedresults: A host is created and updated with expected user assigned
14:46:30          """
14:46:30          host …
```
> [6.14.z] Update Entity.__eq__ isinstance check to work in either direction

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1153
Update `Entity.__eq__` to check for class compatibility in both directions. This fixes robottelo test errors that occur when comparing a `nailgun.entities.User` instance against an instance of robottelo's wrapper class `robottelo.hosts.DecClass`:
```
14:46:30      @pytest.mark.tier2
14:46:30      def test_positive_create_and_update_with_user(
14:46:30          module_org, module_location, module_user, module_target_sat
14:46:30      ):
14:46:30          """Create and update host with user specified
14:46:30      
14:46:30          :id: 72e20f8f-17dc-4e38-8ac1-d08df8758f56
14:46:30      
14:46:30          :expectedresults: A host is created and updated with expected user assigned
14:46:30          """
14:46:30          host …
```
> [6.15.z] Update Entity.__eq__ isinstance check to work in either direction

- docs/create_organization_nailgun.py
- docs/create_user_nailgun.py
- docs/index.rst
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1152
Update all entity initialization calls to pass `server_config` as a named kwarg instead of as a positional arg.
Fixes https://github.com/SatelliteQE/nailgun/issues/1038
```
pytest_fixtures/component/taxonomy.py:43: in module_org
return module_target_sat.api.Organization().create()
../../lib64/python3.12/site-packages/nailgun/entities.py:5803: in create
return type(self)(
E   TypeError: Organization.__init__() got multiple values for argument 'server_config'
```
nailgun tests:
```
............................................................................................................................................................................ …
```
> [6.14.z] Use server_config as named argument only

- docs/create_organization_nailgun.py
- docs/create_user_nailgun.py
- docs/index.rst
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1152
Update all entity initialization calls to pass `server_config` as a named kwarg instead of as a positional arg.
Fixes https://github.com/SatelliteQE/nailgun/issues/1038
```
pytest_fixtures/component/taxonomy.py:43: in module_org
return module_target_sat.api.Organization().create()
../../lib64/python3.12/site-packages/nailgun/entities.py:5803: in create
return type(self)(
E   TypeError: Organization.__init__() got multiple values for argument 'server_config'
```
nailgun tests:
```
............................................................................................................................................................................ …
```
> [6.15.z] Use server_config as named argument only

- docs/create_organization_nailgun.py
- docs/create_user_nailgun.py
- docs/index.rst
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
Update all entity initialization calls to pass `server_config` as a named kwarg instead of as a positional arg.
Fixes https://github.com/SatelliteQE/nailgun/issues/1038
Fixes https://github.com/SatelliteQE/nailgun/issues/1155
```
pytest_fixtures/component/taxonomy.py:43: in module_org
return module_target_sat.api.Organization().create()
../../lib64/python3.12/site-packages/nailgun/entities.py:5803: in create
return type(self)(
E   TypeError: Organization.__init__() got multiple values for argument 'server_config'
```
nailgun tests:
```
...................................................................................................................................................................................... …
```
> [6.13.z] Fix entity create methods

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/automerge.yaml
- .github/workflows/merge_to_master.yml
There were a few failed cherry-picks that this commit resolves in one
go. Specific issues will be tagged and aligned in GitHub.
Fixes:
#1120 
#1166 
#1173 
#1175 
#1184
> [6.13.z] - Handle failed workflow cherry-picks

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1119
```
RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ.","errors":["Task c7fa616b-2f71-4476-b581-1cae65a9eafd: RuntimeError: …
```
> [6.14.z] Add json response to entity creation error message

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1119
```
RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ.","errors":["Task c7fa616b-2f71-4476-b581-1cae65a9eafd: RuntimeError: …
```
> [6.13.z] Add json response to entity creation error message

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1119
```
RuntimeError: The repository's publication is missing. Please run a 'complete sync' on MPvytWJ.","errors":["Task c7fa616b-2f71-4476-b581-1cae65a9eafd: RuntimeError: …
```
> [6.12.z] Add json response to entity creation error message

- .github/dependabot.yml
New 6.16.z downstream and master points to stream that is 6.17
- Dependabot.yaml cherrypicks to 6.16.z
> [master]: Changes for 6.16.z new branch

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
Currently PR checks are not running on Python 3.12. The PR just rectifies that.
> PR checks for python 3.12

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
Description of changes
Currently PR checks are not running on Python 3.12. The PR just rectifies that.
Closes #1197
> PR checks for python 3.12 (#1195)

- nailgun/entities.py
Added new field `reported_data` to the `Host` entity.
This field is optional and it is not present for all host instances,
only for those reporting real data, like bare metal hosts and so.
Example:
```
In [1]: from nailgun.entities import Host
In [2]: host = Host().search(query={'search': f'name=sat.instance.addr.com'})[0]
In [3]: host.reported_data
Out [3]:
{
"boot_time": "2024-06-21 16:44:18 +0200",
"cores": 6,
"sockets": 6,
"disks_total": 107374182400,
"kernel_version": "5.14.0-427.20.1.el9_4.x86_64",
"bios_vendor": "SeaBIOS",
"bios_release_date": "04/01/2014",
"bios_version": "1.16.1-1.el9"
}
```
> host: added field reported_data

- nailgun/entities.py
Add support for debian repository creation
All tests are green
I'm not sure if there should be explicit tests for debian repo creation?
> Add support for debian repository creation

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1202
Added new field `reported_data` to the `Host` entity.
This field is optional and it is not present for all host instances,
only for those reporting real data, like bare metal hosts and so.
Example:
```
In [1]: from nailgun.entities import Host
In [2]: host = Host().search(query={'search': f'name=sat.instance.addr.com'})[0]
In [3]: host.reported_data
Out [3]:
{
"boot_time": "2024-06-21 16:44:18 +0200",
"cores": 6,
"sockets": 6,
"disks_total": 107374182400,
"kernel_version": "5.14.0-427.20.1.el9_4.x86_64",
"bios_vendor": "SeaBIOS",
"bios_release_date": "04/01/2014",
"bios_version": "1.16.1-1.el9"
}
```
> [6.15.z] host: added field reported_data

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1203
Add support for debian repository creation
All tests are green
I'm not sure if there should be explicit tests for debian repo creation?
> [6.15.z] Add support for debian repository creation

- pyproject.toml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1212
> [!IMPORTANT]
> https://github.com/SatelliteQE/nailgun/pull/1083 needs to go in first
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
> [6.14.z] Fix ruff deprecation warnings

- pyproject.toml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1212
> [!IMPORTANT]
> https://github.com/SatelliteQE/nailgun/pull/1083 needs to go in first
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
> [6.15.z] Fix ruff deprecation warnings

- pyproject.toml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1212
> [!IMPORTANT]
> https://github.com/SatelliteQE/nailgun/pull/1083 needs to go in first
Fixing:
```
$ ruff check .
warning: The top-level linter settings are deprecated in favour of their counterparts in the `lint` section. Please update the following options in `pyproject.toml`:
- 'fixable' -> 'lint.fixable'
- 'ignore' -> 'lint.ignore'
- 'select' -> 'lint.select'
- 'flake8-pytest-style' -> 'lint.flake8-pytest-style'
- 'isort' -> 'lint.isort'
- 'mccabe' -> 'lint.mccabe'
- 'per-file-ignores' -> 'lint.per-file-ignores'
warning: `PGH001` has been remapped to `S307`.
warning: `TRY200` has been remapped to `B904`.
```
I removed `PGH001` as `S307` is in the `select` section already
> [6.13.z] Fix ruff deprecation warnings

- .github/workflows/automerge.yaml
This PR backports changes from #1226
- **Changes for new 6.16.z branch (#1218)**
- **[pre-commit.ci] pre-commit autoupdate (#1216)**
> [6.16.z] Bump pascalgn/automerge-action from 0.16.3 to 0.16.4

- nailgun/entity_mixins.py
The output of raise_for_status is not really descriptive for since the actual error message is not part of the exception.
This commit exapnds on 95b3ce10125cfbc8d9a6d8a8e2b38a5007dd1b16
Adds existing solution to all raise_for_status calls.
Example:
```
requests.exceptions.HTTPError: ('500 Server Error: Internal Server Error for url: https://robo-main-orcharhino-alma8.infra.dev.atix/katello/api/v2/repositories/42', {'displayMessage': 'Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this repository before attempting to delete it or use --remove-from-content-view-versions flag to automatically remove the repository from all published versions.', 'errors': ['Repository cannot be deleted since it …
```
> Abstract adding json respone to error message

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1224
The output of raise_for_status is not really descriptive for since the actual error message is not part of the exception.
This commit exapnds on 95b3ce10125cfbc8d9a6d8a8e2b38a5007dd1b16
Adds existing solution to all raise_for_status calls.
Example:
```
requests.exceptions.HTTPError: ('500 Server Error: Internal Server Error for url: https://robo-main-orcharhino-alma8.infra.dev.atix/katello/api/v2/repositories/42', {'displayMessage': 'Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this repository before attempting to delete it or use --remove-from-content-view-versions flag to automatically remove the repository from all …
```
> [6.14.z] Abstract adding json respone to error message

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1224
The output of raise_for_status is not really descriptive for since the actual error message is not part of the exception.
This commit exapnds on 95b3ce10125cfbc8d9a6d8a8e2b38a5007dd1b16
Adds existing solution to all raise_for_status calls.
Example:
```
requests.exceptions.HTTPError: ('500 Server Error: Internal Server Error for url: https://robo-main-orcharhino-alma8.infra.dev.atix/katello/api/v2/repositories/42', {'displayMessage': 'Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this repository before attempting to delete it or use --remove-from-content-view-versions flag to automatically remove the repository from all …
```
> [6.15.z] Abstract adding json respone to error message

- nailgun/entities.py
Add possibility to query deb packages for host
There is no up to date foreman documentation online but the api is listed [here](https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host-debs.factory.js)
```
ipdb> host.debs({"per_page": 20})
{'total': 385, 'subtotal': 385, 'selectable': 385, 'page': 1, 'per_page': 20, 'error': None, 'search': None, 'sort': {'by': 'name', 'order': 'asc'}, 'results':  ...
```
possible PRT test `tests/foreman/api/test_errata.py`
> Add possibility to query deb packages for host

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1233
Add possibility to query deb packages for host
There is no up to date foreman documentation online but the api is listed [here](https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host-debs.factory.js)
```
ipdb> host.debs({"per_page": 20})
{'total': 385, 'subtotal': 385, 'selectable': 385, 'page': 1, 'per_page': 20, 'error': None, 'search': None, 'sort': {'by': 'name', 'order': 'asc'}, 'results':  ...
```
possible PRT test `tests/foreman/api/test_errata.py`
> [6.16.z] Add possibility to query deb packages for host

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1233
Add possibility to query deb packages for host
There is no up to date foreman documentation online but the api is listed [here](https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host-debs.factory.js)
```
ipdb> host.debs({"per_page": 20})
{'total': 385, 'subtotal': 385, 'selectable': 385, 'page': 1, 'per_page': 20, 'error': None, 'search': None, 'sort': {'by': 'name', 'order': 'asc'}, 'results':  ...
```
possible PRT test `tests/foreman/api/test_errata.py`
> [6.15.z] Add possibility to query deb packages for host

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1233
Add possibility to query deb packages for host
There is no up to date foreman documentation online but the api is listed [here](https://github.com/Katello/katello/blob/master/engines/bastion_katello/app/assets/javascripts/bastion_katello/hosts/host-debs.factory.js)
```
ipdb> host.debs({"per_page": 20})
{'total': 385, 'subtotal': 385, 'selectable': 385, 'page': 1, 'per_page': 20, 'error': None, 'search': None, 'sort': {'by': 'name', 'order': 'asc'}, 'results':  ...
```
possible PRT test `tests/foreman/api/test_errata.py`
> [6.14.z] Add possibility to query deb packages for host

- nailgun/entities.py
it is a space separated string not a list
https://apidocs.theforeman.org/foreman/latest/apidoc/v2/registration_commands/create.html
> Fix for registration command packages

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1225
it is a space separated string not a list
https://apidocs.theforeman.org/foreman/latest/apidoc/v2/registration_commands/create.html
> [6.16.z] Fix for registration command packages

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1225
it is a space separated string not a list
https://apidocs.theforeman.org/foreman/latest/apidoc/v2/registration_commands/create.html
> [6.15.z] Fix for registration command packages

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1225
it is a space separated string not a list
https://apidocs.theforeman.org/foreman/latest/apidoc/v2/registration_commands/create.html
> [6.14.z] Fix for registration command packages

- nailgun/entities.py
Add repo_data option to host registration command
The foreman upstream api is not up to date so I can only link the PR
https://github.com/theforeman/foreman/pull/10162
I am executing it via robottelo I do not know how to extract the raw api call.
None
> Add repo_data option to host registration command

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1210
Add repo_data option to host registration command
The foreman upstream api is not up to date so I can only link the PR
https://github.com/theforeman/foreman/pull/10162
I am executing it via robottelo I do not know how to extract the raw api call.
None
> [6.16.z] Add repo_data option to host registration command

- nailgun/entities.py
- purpose_addons is removed from katello https://github.com/Katello/katello/pull/11196 causing robottelo tests to fail and blocking stream snap templatization pipeline.
- remove purpose_addons
- https://github.com/Katello/katello/pull/11196
- Can't the change is not available in downstream snap so can't test it yet.
> Remove Purpose addons from Nailgun

- nailgun/entities.py
We have decided not-to return the auth tokens at all.
https://issues.redhat.com/browse/SAT-30106
https://github.com/Katello/katello/pull/11261
Same as https://github.com/SatelliteQE/nailgun/pull/1255 - token is not returned.
> Remove the token field from flatpak remote

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Python 3.13 was released on October 7, 2024, and we're not covering this in the PR checks in GHA yet
Add Python 3.13 for PR checks in GHA
> Add Python 3.13 for PR checks in GHA

- nailgun/entities.py
- tests/test_entities.py
Add AnsibleVariable to entities
I would like to reference to api doc but the latest version I can find is 3.4 ...
Example:
```
module_target_sat.api.AnsibleVariable(
variable="foreman_cloud_connector_user",
default_value="foo",
ansible_role_id=ansible_role_id,
).create()
robottelo.hosts.DecClass(variable='foreman_cloud_connector_user', ansible_role_id=24, default_value='foo', id=54)
```
> Add AnsibleVariable to entities

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1220
Add AnsibleVariable to entities
I would like to reference to api doc but the latest version I can find is 3.4 ...
Example:
```
module_target_sat.api.AnsibleVariable(
variable="foreman_cloud_connector_user",
default_value="foo",
ansible_role_id=ansible_role_id,
).create()
robottelo.hosts.DecClass(variable='foreman_cloud_connector_user', ansible_role_id=24, default_value='foo', id=54)
```
> [6.16.z] Add AnsibleVariable to entities

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1220
Add AnsibleVariable to entities
I would like to reference to api doc but the latest version I can find is 3.4 ...
Example:
```
module_target_sat.api.AnsibleVariable(
variable="foreman_cloud_connector_user",
default_value="foo",
ansible_role_id=ansible_role_id,
).create()
robottelo.hosts.DecClass(variable='foreman_cloud_connector_user', ansible_role_id=24, default_value='foo', id=54)
```
> [6.14.z] Add AnsibleVariable to entities

- nailgun/entities.py
Add download_utility property to RegistrationCommand
Option was added to foreman recently https://github.com/theforeman/foreman/blob/develop/app/controllers/api/v2/registration_commands_controller.rb#L28
> Enable download utility selection

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1261
Python 3.13 was released on October 7, 2024, and we're not covering this in the PR checks in GHA yet
Add Python 3.13 for PR checks in GHA
> [6.16.z] Add Python 3.13 for PR checks in GHA

- .github/workflows/merge_to_master.yml
This GHA update was missed in PR: https://github.com/SatelliteQE/nailgun/pull/1261
Already fixed in the cherrypick of mentioned PR
> Using Py3.13 for build/publish to PyPI GHA

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1271
Updating Hostgroup and host class with subnet6 needed for IPv6 subnet creation via api
> [6.16.z] Update Hostgroup and host class with subnet6 for IPv6

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1271
Updating Hostgroup and host class with subnet6 needed for IPv6 subnet creation via api
> [6.15.z] Update Hostgroup and host class with subnet6 for IPv6

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1271
Updating Hostgroup and host class with subnet6 needed for IPv6 subnet creation via api
> [6.14.z] Update Hostgroup and host class with subnet6 for IPv6

- nailgun/entities.py
Change introduced in https://github.com/Katello/katello/pull/11183 and https://github.com/Katello/katello/pull/11266
> Add boolean field for content_default_http_proxy in HTTProxy entity

- nailgun/entities.py
- tests/test_entities.py
Add `advisor_engine_config` method to the `RHCloud` entity, to call and return the response from the new API method introduced in https://github.com/theforeman/foreman_rh_cloud/pull/932
https://github.com/theforeman/foreman_rh_cloud/pull/932
Needed for robottelo tests:
SAT-30174
https://github.com/SatelliteQE/robottelo/pull/17342
Example:
```
>>> from robottelo.hosts import Satellite
>>> sat = Satellite(hostname='XXX')
>>> sat.api.RHCloud().advisor_engine_config()
{'use_local_advisor_engine': False}
```
> Add RHCloud.advisor_engine_config API

- .github/dependabot.yml
New 6.17.z downstream and master points to stream that is 6.18
- Dependabot.yaml cherrypicks to 6.17.z
> [master]: Changes for 6.17.z new branch

- nailgun/entities.py
- tests/test_entities.py
Add donwload cuncurrency for repository
https://apidocs.theforeman.org/katello/latest/apidoc/v2/repositories/create.html
log output:
```
2025-02-11 09:34:21 - nailgun.client - DEBUG - Making HTTP POST request to https://...katello/api/v2/repositories with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and data {"name": "test-uln", "content_type": "yum", "download_policy": "on_demand", "url": "uln://ovm2_2.1.1_i386_patch", "upstream_username": "***", "upstream_password": "***", "download_concurrency": 1, "organization_id": 8, "product_id": 304}
```
> Add donwload cuncurrency for repository

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1272
Add donwload cuncurrency for repository
https://apidocs.theforeman.org/katello/latest/apidoc/v2/repositories/create.html
log output:
```
2025-02-11 09:34:21 - nailgun.client - DEBUG - Making HTTP POST request to https://...katello/api/v2/repositories with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and data {"name": "test-uln", "content_type": "yum", "download_policy": "on_demand", "url": "uln://ovm2_2.1.1_i386_patch", "upstream_username": "***", "upstream_password": "***", "download_concurrency": 1, "organization_id": 8, "product_id": 304}
```
> [6.16.z] Add donwload cuncurrency for repository

- nailgun/entities.py
Adding ip6 for host class required for IPv6 host to report the IPv6 address
Dependent robottelo PR: https://github.com/SatelliteQE/robottelo/pull/17340
> Add ip6 for host class

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1282
Adding ip6 for host class required for IPv6 host to report the IPv6 address
Dependent robottelo PR: https://github.com/SatelliteQE/robottelo/pull/17340
> [6.17.z] Add ip6 for host class

- nailgun/entities.py
Adds one new API endpoint that supports bootc
Supports: https://github.com/SatelliteQE/robottelo/pull/17634
PRT runs over there.
> Add view/entity for booted container images page

- requirements-dev.txt
> Add setuptools to dev dependencies

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1286
```
```
> [6.17.z] Add setuptools to dev dependencies

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1286
```
```
> [6.16.z] Add setuptools to dev dependencies

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1286
```
```
> [6.15.z] Add setuptools to dev dependencies

- requirements-dev.txt
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1286
```
```
> [6.14.z] Add setuptools to dev dependencies

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
We can not update the Sphinx library without dropping Python 3.10 - SatelliteQE/robottelo#17638.
Drop Python 3.10 suport.
SatelliteQE/robottelo#17638
SatelliteQE/robottelo#17666
SatelliteQE/robottelo#17557
> Remove Python 3.10 support

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
- setup.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1285
We can not update the Sphinx library without dropping Python 3.10 - SatelliteQE/robottelo#17638.
Drop Python 3.10 suport.
SatelliteQE/robottelo#17638
SatelliteQE/robottelo#17666
SatelliteQE/robottelo#17557
> [6.16.z] Remove Python 3.10 support

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1277
Adds one new API endpoint that supports bootc
Supports: https://github.com/SatelliteQE/robottelo/pull/17634
PRT runs over there.
> [6.17.z] Add view/entity for booted container images page

- nailgun/entities.py
- tests/test_entities.py
Add two missing options to snapshot api
https://github.com/ATIX-AG/foreman_snapshot_management/blob/master/app/models/foreman_snapshot_management/proxmox_extensions.rb#L13
```
nailgun.client - DEBUG - Making HTTP POST request to https://.../api/v2/hosts/11/snapshots with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and data {"name": "snap1_alma_9_False_True", "include_ram": true, "quiesce": false, "host_id": 11}.
2025-03-31 11:55:30 - nailgun.client - DEBUG - Received HTTP 201 response: {"description":null,"id":null,"name":"snap1_alma_9_False_True","formatted_created_at":null,"created_at":null,"parent_id":null,"children_ids":null}
```
> Add quiesce and ram option to snapshot api

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1298
Add two missing options to snapshot api
https://github.com/ATIX-AG/foreman_snapshot_management/blob/master/app/models/foreman_snapshot_management/proxmox_extensions.rb#L13
```
nailgun.client - DEBUG - Making HTTP POST request to https://.../api/v2/hosts/11/snapshots with options {'auth': None, 'verify': None, 'headers': {'content-type': 'application/json'}}, no params and data {"name": "snap1_alma_9_False_True", "include_ram": true, "quiesce": false, "host_id": 11}.
2025-03-31 11:55:30 - nailgun.client - DEBUG - Received HTTP 201 response: {"description":null,"id":null,"name":"snap1_alma_9_False_True","formatted_created_at":null,"created_at":null,"parent_id":null,"children_ids":null}
```
> [6.17.z] Add quiesce and ram option to snapshot api

- nailgun/entities.py
- tests/test_entities.py
Rolling Content Views are heading into 6.18.0, see https://issues.redhat.com/browse/SAT-28495 
<sat_fqdn>/apidoc/v2/content_views/create.en.html
```
from robottelo.hosts import Satellite
>>> sat = Satellite('satellite.redhat.com')
>>> sat.api.ContentView(rolling=True, organization=1).create()
robottelo.hosts.DecClass(auto_publish=False, component=[], composite=False, content_host_count=0, description=None, environment=[nailgun.entities.LifecycleEnvironment(id=1)], label='avlqrtv', last_published='2025-05-07 15:29:15 UTC', name='avlqrtv', needs_publish=False, next_version='2.0', organization=nailgun.entities.Organization(id=1), repository=[], rolling=True, solve_dependencies=False, version=[nailgun.entities.ContentViewVersion(id=11)], id=12)
>>> sat.api.ContentView(id=12).read() …
```
> Add rolling key for CVs

- nailgun/entities.py
**_1:_** Currently, we cannot api DELETE a `ContentViewVersion` if it is published to any LCE, including Library, ISE 500.
**_2:_** There is no api method to remove/delete a `ContentViewVersion` from the `ContentView` , only for removing a single environment by :id
***_3:_*** We do not currently have an api method that calls the same endpoint, as the UI ContentViewVersion Delete wizard. 
See solution.
- We must first remove the Version from any published/promoted environments, including library, before attempting to Delete.
- `ContentViewVersion.delete()` calls the Katello Destroy api, performs no checks or steps before 
attempting bulk Destroy. `DELETE , "/content_view_versions/:id", ("Remove content view version")`
^ on any published CVV, yields:  
```
E  requests.exceptions.HTTPError: …
```
> ContentView::RemoveVersion (from the CV and any ENVs)

- nailgun/entities.py
- nailgun/entity_mixins.py
I found this issue while working on a Robottelo upgrade scenario refactor. I found that a test syncing the RHEL 7 server RPMs repo was consistently timing out after 300 seconds, though the `enable_sync_redhat_repo` API factory method uses a timeout of 1500 seconds by default. Eventually, I found that
`nailgun.entity_mixins.call_entity_with_timeout()` was invoking the entity callable without specifically passing the timeout. After the repo sync was initiated, `nailgun.entity_mixins._poll_task()` was being called with no timeout value specified, causing the `timeout` variable to be set to the `TASK_TIMEOUT` constant defined in the entity_mixins module, which has a value of 300 seconds. My repo sync was completing in ~360 seconds, so the test was consistently failing.
This PR adds a …
> Add explicit timeout to `entity_callable()` invocation in `call_entity_with_timeout()`

- nailgun/entities.py
- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1311
I found this issue while working on a Robottelo upgrade scenario refactor. I found that a test syncing the RHEL 7 server RPMs repo was consistently timing out after 300 seconds, though the `enable_sync_redhat_repo` API factory method uses a timeout of 1500 seconds by default. Eventually, I found that
`nailgun.entity_mixins.call_entity_with_timeout()` was invoking the entity callable without specifically passing the timeout. After the repo sync was initiated, `nailgun.entity_mixins._poll_task()` was being called with no timeout value specified, causing the `timeout` variable to be set to the `TASK_TIMEOUT` constant defined in the entity_mixins module, which has a value of 300 seconds. My repo sync was completing in ~360 …
> [6.17.z] Add explicit timeout to `entity_callable()` invocation in `call_entity_with_timeout()`

- nailgun/entities.py
- tests/test_entities.py
We can set ACS HTP proxy on any Capsule since long ago. This has never been added to the nailgun as it was never used and the endpoint doesn't return it on read. But now I can see a use case suitable for IPv6 testing.
This PR also updates the download policies to more recent values.
Robottelo PR will follow.
https://satellite.redhat.com/apidoc/v2/smart_proxies/update.en.html
```
sat = Satellite('satellite.redhat.com')
proxy = sat.enable_satellite_http_proxy()
caps = sat.nailgun_smart_proxy
caps.http_proxy = proxy
caps.update(['http_proxy'])
robottelo.hosts.DecClass(name='satellite.redhat.com', url='https://satellite.redhat.com:9090', location=[nailgun.entities.Location(id=2)], organization=[nailgun.entities.Organization(id=1), nailgun.entities.Organization(id=3)], id=1)
-> go to …
```
> Add http_proxy to the SmartProxy entity

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1314
We can set ACS HTP proxy on any Capsule since long ago. This has never been added to the nailgun as it was never used and the endpoint doesn't return it on read. But now I can see a use case suitable for IPv6 testing.
This PR also updates the download policies to more recent values.
Robottelo PR will follow.
https://satellite.redhat.com/apidoc/v2/smart_proxies/update.en.html
```
sat = Satellite('satellite.redhat.com')
proxy = sat.enable_satellite_http_proxy()
caps = sat.nailgun_smart_proxy
caps.http_proxy = proxy
caps.update(['http_proxy'])
robottelo.hosts.DecClass(name='satellite.redhat.com', url='https://satellite.redhat.com:9090', location=[nailgun.entities.Location(id=2)], …
```
> [6.17.z] Add http_proxy to the SmartProxy entity

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1324
Adding description key to _fields dictionary to incorporate description feature for job-template 
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/19093
> [6.17.z] Add description key to _fields dictionary

- tests/test_config.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1316
This PR addresses a security best practice issue by replacing the hardcoded temporary file path `/tmp/bogus.json` with Python's standard `tempfile` module.
- Added `import tempfile` to the imports
- Replaced `FILE_PATH = '/tmp/bogus.json'  # noqa: S108` with `FILE_PATH = tempfile.NamedTemporaryFile(suffix='.json', delete=False).name`
- Removed the `# noqa: S108` comment since the hardcoded temp file issue is now resolved
The original code used a hardcoded path `/tmp/bogus.json` which violates security best practices (ruff rule S108 - hardcoded-temp-file). While the tests use mocked file operations and don't actually access the filesystem, using proper temporary file generation is the recommended approach.
- All existing …
> [6.17.z] Replace hardcoded temp file path with tempfile in tests/test_config.py

- tests/test_config.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1316
This PR addresses a security best practice issue by replacing the hardcoded temporary file path `/tmp/bogus.json` with Python's standard `tempfile` module.
- Added `import tempfile` to the imports
- Replaced `FILE_PATH = '/tmp/bogus.json'  # noqa: S108` with `FILE_PATH = tempfile.NamedTemporaryFile(suffix='.json', delete=False).name`
- Removed the `# noqa: S108` comment since the hardcoded temp file issue is now resolved
The original code used a hardcoded path `/tmp/bogus.json` which violates security best practices (ruff rule S108 - hardcoded-temp-file). While the tests use mocked file operations and don't actually access the filesystem, using proper temporary file generation is the recommended approach.
- All existing …
> [6.16.z] Replace hardcoded temp file path with tempfile in tests/test_config.py

- .pre-commit-config.yaml
- tests/test_config.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1253
updates:
- [github.com/psf/black: 24.10.0 → 25.1.0](https://github.com/psf/black/compare/24.10.0...25.1.0)
- [github.com/astral-sh/ruff-pre-commit: v0.7.3 → v0.12.8](https://github.com/astral-sh/ruff-pre-commit/compare/v0.7.3...v0.12.8)
- [github.com/pre-commit/pre-commit-hooks: v5.0.0 → v6.0.0](https://github.com/pre-commit/pre-commit-hooks/compare/v5.0.0...v6.0.0)
> [6.17.z] [pre-commit.ci] pre-commit autoupdate

- nailgun/entities.py
Recently the `application_name` has been added to the flatpak remote repository to help users pick the correct app name for REX. However, we could use that information too. We just need to add it to the known fields.
```
>>> from robottelo.hosts import Satellite
>>> sat = Satellite('SAT_FQDN')
>>> sat.api.FlatpakRemoteRepository(id=9).read()
robottelo.hosts.DecClass(flatpak_remote_id=3, name='rhel10/firefox-flatpak', application_name='org.mozilla.firefox', label='8ec304a4-3e65-46da-ba89-2f2fd1256fda', id=9)
```
> Add application_name field to FlatpakRemoteRepository

- .github/dependabot.yml
New 6.18.z downstream and master points to stream that is 6.19
- Dependabot.yaml cherrypicks to 6.18.z
> [master]: Changes for 6.18.z new branch

- nailgun/entities.py
Added export function to ReportTemplate class and also accomodate in  path.
<SAT>/apidoc/v2/report_templates.en.html#description-export
```
In [1]: from robottelo.config import settings
In [2]: from robottelo.hosts import Satellite
In [3]: target_sat = Satellite('sat-ip-addr')
In [4]: rt = target_sat.api.ReportTemplate()
In [5]: print('Available methods:', [method for method in dir(rt) if not method.startswith('_')])
In [6]: print('Has export method:', hasattr(rt, 'export'))
```
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/19367
> Add Export function to ReportTemplate class

- nailgun/entities.py
This PR adds an entity class for the content view environments endpoint. This is required for automating SAT-34301.
https://apidocs.theforeman.org/katello/4.18/apidoc/v2/content_view_environments/index.html
PRT run in https://github.com/SatelliteQE/robottelo/pull/19581.
> Add entity for content view environments endpoint

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1349
Added export function to ReportTemplate class and also accomodate in  path.
<SAT>/apidoc/v2/report_templates.en.html#description-export
```
In [1]: from robottelo.config import settings
In [2]: from robottelo.hosts import Satellite
In [3]: target_sat = Satellite('sat-ip-addr')
In [4]: rt = target_sat.api.ReportTemplate()
In [5]: print('Available methods:', [method for method in dir(rt) if not method.startswith('_')])
In [6]: print('Has export method:', hasattr(rt, 'export'))
```
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/19367
> [6.16.z] Add Export function to ReportTemplate class

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1349
Added export function to ReportTemplate class and also accomodate in  path.
<SAT>/apidoc/v2/report_templates.en.html#description-export
```
In [1]: from robottelo.config import settings
In [2]: from robottelo.hosts import Satellite
In [3]: target_sat = Satellite('sat-ip-addr')
In [4]: rt = target_sat.api.ReportTemplate()
In [5]: print('Available methods:', [method for method in dir(rt) if not method.startswith('_')])
In [6]: print('Has export method:', hasattr(rt, 'export'))
```
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/19367
> [6.17.z] Add Export function to ReportTemplate class

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1357
This PR adds an entity class for the content view environments endpoint. This is required for automating SAT-34301.
https://apidocs.theforeman.org/katello/4.18/apidoc/v2/content_view_environments/index.html
PRT run in https://github.com/SatelliteQE/robottelo/pull/19581.
> [6.18.z] Add entity for content view environments endpoint
