- nailgun/entities.py
Imported classes of entity_mixins for create, delete and fetch data for puppet-classes in entites puppet-classes in entites.py file.
> Imported classes of entity_mixins for create, delete and fetch data for puppet-classes in entites.

- nailgun/entities.py
- nailgun/entity_mixins.py
These two changes are logically separate, but I'm bundling them together for the sake of expediency. I have a matching pull request ready to go on Robottelo, and if this is merged, then I can release 0.12.0 and unblock that PR.
For full details on the changes in this PR, please see the individual commit messages. Summary of changes:
* Do not automatically create missing values on entities. The default assumption among users (especially new users) is likely that if a value is missing, then it will not be created, and this change makes NailGun more accessible to a wide audience by catering to that assumption.
* Refactor out some common response handling code. This makes the existing code base slightly smaller, common response handling code makes silly mistakes harder to commit, and this …
> Fix #4, #46

- nailgun/client.py
From comments in the code itself:
> The urllib3 module (which requests uses) refuses to make insecure HTTPS
> connections. You can override this behaviour by passing `verify=False` to any
> of its methods. For example:
>
>     requests.get('https://insecure.example.com', verify=False)
>
> However, urllib3 will still raise an InsecureRequestWarning if this is done.
> This is problematic. If a user has explicitly stated that they want HTTPS
> connections to be made and we are pestering the user with warnings about that
> fact, then we are effectively training the user to ignore warnings. The
> statement below filters out that warning.
Example of NailGun usage with this patch:
```python
>>> org = …
```
> Silence spurious insecure connection warnings

- nailgun/entities.py
According to the current unit test results, `Host.create` frequently fails.
Attempt to fix this. Manual tests shows that the following works on both
upstream and downstream systems:
>>> entities.Host().create(create_missing=True)
For more information on the bugs that had to be worked around to make this work,
see:
* https://bugzilla.redhat.com/show_bug.cgi?id=1219653
* https://bugzilla.redhat.com/show_bug.cgi?id=1219654
> Make `Host.create` work

- tests/test_entities.py
Certain entities have different fields based on which software version the
server is running. Add unit tests for this type of logic.
Also, drop outdated pylint directives. Pylint apparently now knows to not
complain about the naming of unittest's `setUp` and `setUpClass` methods.
> Test version-related logic to unit test suite

- nailgun/entities.py
- nailgun/entity_mixins.py
Field names on an entity do not always match what the server expects to receive
in a request or what the server returns in a response. Class attribute
`Meta.api_names` is an attempt to address these mis-matches. It is a dict of
local-remote name mappings. For example, from class `ContentViewFilter`:
```python
class Meta(object):
"""Non-field information about this entity."""
api_names = {'filter_type': 'type'}
```
Unfortunately, `Meta.api_names` is both complex and limited. It is complex
because cause and effect are distant. The presence of name mappings on
individual classes in module `nailgun.entities` causes logic in several methods
in `nailgun.entity_mixins` to execute — that's not obvious! It is limited
because it cannot handle certain use cases, such as the fact that a name mapping …
> Drop `Meta.api_names`

- nailgun/entities.py
Introduced few fixes, so functionality works properly for different amount of input attributes
> Fix ContentViewFilter and ContentViewFilterRule classes

- .travis.yml
- Makefile
- README.rst
- requirements-dev.txt
Add coveralls to the project in order to check for code coverage.
Closes #73
> Add code coverage checking

- nailgun/entities.py
- tests/test_entities.py
Fix #76:
> Create a new LibvirtComputeResource entity
>
> I believe it is time to revisit the idea of abstracting
> `entities.ComputeResource` so that we can create specific entities to handle
> different types of compute resources. To get things started I'd like to
> request the creation of a `entities.LibvirtComputeResource` […]
Remove the `ComputeResource` entity class and create the following three classes
in its stead:
* `AbstractComputeResource`
* `DockerComputeResource`
* `LibvirtComputeResource`
Example of usage:
```python
>>> dcr = entities.DockerComputeResource().create(True)
>>> lcr = entities.LibvirtComputeResource().create(True)
>>> dcr.read()
nailgun.entities.DockerComputeResource(
nailgun.config.ServerConfig(
auth=('admin', 'changeme'), …
```
> Break apart the `ComputeResource` entity class

- nailgun/entities.py
I have doubts in current implementation style and appreciate any improvement feedbacks
> Fixed few issues for HostGroup Entity

- tests/test_entities.py
This is a follow-up to #84. I wrote the following as a comment:
> ACK pending Travis. Don't worry about any drops in coverage percentage -
> @oshtaier is working super late, and I'll file a follow-up PR that adds any
> needed tests.
> Add unit tests for the `HostGroup` entity

- nailgun/entities.py
Turns out that `DockerHubContainer` class was not properly inheriting
fields from its parent (see `AbstractComputeResource` for an example). I
have also fixed the issue where the server was not returning a full set
of attributes after a `POST`.
This fixes #95.
> `DockerHubContainer` now properly inherited fields

- nailgun/entities.py
Some entities in Host.create_missing() were created without required
connections through organization and location.
API tests which are using create_missing() are passing without this fix, as
API doesn't check for requirements to be satisfied (so API allows to
associate entities from different locs and orgs, which is not good).
But UI tests are failing as corresponding entities aren't present in
drop-downs and can't be selected.
The fix is required for SatelliteQE/robottelo#748.
> Updated missing dependencies in Host.create_missing()

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
Add the `EntityUpdateMixin` to several entities. Add methods to those entities
as needed in order to make the `update*` methods work correctly.
Add fields to entities:
* `ContentView.puppet_module`
* `ContentView.version`
* `ContentViewVersion.environment`
* `ContentViewVersion.puppet_module`
* `Location.realm` (Fix #52)
* `Organization.compute_resource`
* `Organization.config_template`
* `Organization.domain`
* `Organization.environment`
* `Organization.hostgroup`
* `Organization.media`
* `Organization.realm`
* `Organization.smart_proxy`
* `Organization.subnet`
* `Organization.subnet`
* `Organization.user`
* `Product.repository`
* `Realm.location`
* `Realm.organization`
* `Realm.realm_proxy` (Fix #36)
* `Subnet.discovery` (Fix #56, Fix #75)
* `Subscription.product`
Change how the …
> Use EntityUpdateMixin, update entity fields

- tests/test_config.py
> Make unit tests compatible with Python 2.7.5

- nailgun/entities.py
- tests/test_entities.py
These bugs are all related to #115. I'm not done filing and linking to bugs, but this is a start.
> Reference bugs

- nailgun/entities.py
- tests/test_entities.py
NailGun has several bug workaround that are not documented. File bugs for many of those workaround and link to the relevant bugs. Add unit tests for the workarounds. Of note:
* In the process of documenting existing workarounds, I've discovered more bugs and written a few new workarounds.
* I've changed the fields on the HostGroup and Host entities.
> Document and test bug workarounds

- nailgun/entities.py
- tests/test_entities.py
Fix #115. File a bug for every workaround (I think). Each commit corresponds to one workaround. See the commit messages for more details.
> File bugs for all workarounds

- nailgun/entities.py
- tests/test_entities.py
*) Added a new section under docs for Jumpstart Nailgun.
> Updated the missing fields for AuthSourceLDAP class for sat61.

- docs/conf.py
- nailgun/config.py
- nailgun/entities.py
- setup.py
- tests/test_config.py
Fix #144. Drop "setuptools" as a dependency and use "packaging" instead.
> Change dependencies

- nailgun/entities.py
- tests/test_entities.py
For Product, added ability to sync all repos associated with it.
For SyncPlan, added ability to use `update()`.
(Need both changes for upcoming robottelo tests)
> Small improvements for Product and SyncPlan entities

- nailgun/entities.py
- tests/test_entities.py
This reverts commit f0198c184d3efdd4f5179e2b13b2f1bc85031642.
The `POST /katello/api/v2/sync_plan` path is not available. As a result, setting
`self._meta['api_path']` to such makes it impossible to create sync plans via
the API.
> Revert "Update SyncPlan entity"

- nailgun/entities.py
- nailgun/entity_fields.py
Closes #135
```
git grep null
docs/Makefile:ifeq ($(shell which $(SPHINXBUILD) >/dev/null 2>&1; echo $$?), 1)
```
Executed random test from api to make sure that all fields populated properly and no exception raised:
```
nosetests tests/foreman/api/test_location.py -m test_create_location_with_description
.
Ran 1 test in 2.844s
OK
```
> Remove redundant 'null' parameter from fields and entities

- nailgun/entities.py
- tests/test_entities.py
Created corresponding BZ 1250922
> Add update functionality for ComputeResource class

- nailgun/entity_mixins.py
Split up the given code sample and insert prose explanations in to the code.
> Update docstring for `search_payload`

- nailgun/entities.py
- tests/test_entities.py
Method `Subscription.search_raw` lays out the problem and chosen solution:
> The ``GET /katello/api/v2/subscriptions`` API call is not available.
> Instead, one of the following must be used:
>
> * ``GET /katello/api/v2/activation_keys/<id>/subscriptions``
> * ``GET /katello/api/v2/organizations/<id>/subscriptions``
> * ``GET /katello/api/v2/systems/<id>/subscriptions``
>
> Use the activation key path if ``self.activation_key`` is set, use the
> organization path if ``self.organization`` is set, use the system path
> if ``self.system`` is set, or raise an exception otherwise.
In order to make this work, several new paths and unit tests were also added.
> Make `Subscription.search` function

- nailgun/entities.py
- tests/test_entities.py
Entities are named in the singular, not the plural.
> Rename class DiscoveredHosts → DiscoveredHost

- nailgun/entities.py
Provided information should help people to get familiar with the code more quickly.
> Added more details to Docker container creation procedure

- nailgun/entities.py
- Updated 'ComputeAttribute' entity with 'create' and 'read' mixin
- Updated Operatingsystem entity to support search mixin
> Updated OS and ComputeAttribute entities

- nailgun/entities.py
- Added location for config template entity
- Updated OS entity with update mixin
> Updated OS and config template entities

- nailgun/entities.py
Added few extra fields for ContentView and Repository entities, which will be used in upcoming robottelo PR.
> Added few extra fields for ContentView and Repository entities

- nailgun/entities.py
- tests/test_entities.py
Added two new params for hostgroup entity. `puppet_proxy` and `puppet_ca_proxy`
> Added new fields in hostgroup entity

- nailgun/entities.py
- tests/test_entities.py
Do the following:
* Add `EntitySearchMixin` as a parent class.
* Add a `summary` method.
* Add several fields.
* Update the `path` method.
* Update unit tests.
Manual test results:
```python
>>> foreman_tasks = entities.ForemanTask().search()
>>> type(foreman_tasks), len(foreman_tasks)
(<class 'list'>, 20)
>>> for i in range(5):
...     foreman_tasks[i].id
...
'4b749daf-1099-4a3b-ba27-1344252b1ea9'
'43dc1a1b-db54-4bdb-980e-0a84d8581651'
'1911f386-3809-4741-a15d-9bf88d5670d6'
'dcbb2a71-a2a5-42ff-ac60-a690bb6dc3a4'
'be4e9578-c07d-4656-8c6c-14a6d71801b3'
>>> foreman_task = foreman_tasks[0].read()
>>> foreman_task.get_values().keys()
dict_keys(['state', 'ended_at', 'id', 'output', 'label', 'pending', 'progress', 'cli_example', 'input', 'result', 'username', …
```
> Update the ForemanTask entity

- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
Fix #222:
> Several of our automated tests have show that synchronization and publishing
> tasks are being polled only once and immediately failing with a
> `TaskFailedError` exception.
>
> […]
>
> Turns out that we have some tasks triggered by the automation that sit on the
> `planned` state for a while and since `'planned' != 'running'` we get out of
> the loop and stop polling right after the first check.
`_poll_task` aborts polling if a task is anything other than the "running"
state. This is bad logic, as a task may proceed through the following states:
* paused
* pending
* planned
* planning
* running
* scheduled
* stopped
Fiddle with `_poll_task`:
* Abort polling if a task enters the "paused" or "stopped" state.
* Continue polling if a task is in any other state, such as …
> Make `_poll_task` more robust

- nailgun/entities.py
- tests/test_entities.py
Adding one more helper for organization entity debug certificate and also put verification for response content type as we can receive different contents from server
> Add support for organization debug certificate

- nailgun/entities.py
- tests/test_entities.py
Example:
```
def test_positive_update_different_names(self):
lc_env = entities.LifecycleEnvironment(organization=self.org).create()
for new_name in valid_data_list():
with self.subTest(new_name):
lc_env = entities.LifecycleEnvironment(
id=lc_env.id, name=new_name).update(['name'])
self.assertEqual(lc_env.name, new_name)
```
```
nosetests tests/foreman/api/test_lifecycleenvironment.py -m test_positive_update_different_names
.
Ran 1 test in 21.941s
OK
```
> Add update functionality for Lifecycle Environment entity

- nailgun/entities.py
> Fixed typo in OS list

- nailgun/entities.py
- tests/test_entities.py
```
>>>profile = entities.ComputeProfile(name='test01').create()
>>>updated_profile = entities.ComputeProfile(id=profile.id, name='test_02').update(['name'])
>>>updated_profile
nailgun.entities.ComputeProfile(nailgun.config.ServerConfig(url=u'https://my_best_server_in_the_world.redhat.com', verify=False, auth=(u'admin', u'changeme')), id=22, name=u'test_02')
```
> Add update mixin for Compute Profile entity

- nailgun/entities.py
- included mixins to support CRUDS operations
> Updated Bookmark class:

- nailgun/entities.py
- tests/test_entities.py
As rules for determining what attributes are requred for host creation are complex and depend on attributes passed and their values, nailgun currently allows to create a bogus managed host only in case no host attributes were passed. 
This is problematic when, for example, user wants to create a host with a custom name, or for already existing organization. For custom name user is forced to do the following trick:
```python
host = entities.Host()
host.create_missing()
host.name = name
host = host.create(create_missing=False)
```
However, for already existing organization (or domain, architecture, etc.) there's no easy workaround as all the dependecies, created inside `create_missing()` will still use a new organization even if we change the host's organization.
The purpose of PR is to …
> Accept instance attributes in Host.create_missing()

- nailgun/entities.py
- tests/test_entities.py
See #261 for more details.
Closes #261
> Support reading of product with sync plan assigned

- nailgun/entities.py
- tests/test_entities.py
`owner` field for Host entity is defined as `'owner': entity_fields.OneToOneField(User)`,
But  `owner` depends on `owner_type` field, which can be one of 'User' or 'Usergroup'.
In case `owner_type == 'Usergroup'`, the host couldn't be read/created, as nailgun was searching for User, not for Usergroup. PR resolves this issue.
Closes #258
> Support Usergroup as a value for entities.Host.owner field

- nailgun/entities.py
```
>>> entities.Registry(name='mytest', url='https://registry.access.redhat.com').create()
nailgun.entities.Registry(nailgun.config.ServerConfig(url=u'https://qe-sat6-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), username=None, url=u'https://registry.access.redhat.com', description=None, password=None, id=45, name=u'mytest')
>>> registry = entities.Registry(name='mytest').search()[0]
>>> registry
nailgun.entities.Registry(nailgun.config.ServerConfig(url=u'https://qe-sat6-rhel7.satqe.lab.eng.rdu2.redhat.com', verify=False, auth=(u'admin', u'changeme')), username=None, url=u'https://registry.access.redhat.com', name=u'mytest', id=45, description=None)
>>> registry.delete()
{u'username': None, u'description': None, u'url': …
```
> Add SearchMixin for Registry entity

- nailgun/entities.py
- The default names will be used only when the caller did not provide the entity
name
- Fixes #290, https://github.com/SatelliteQE/robottelo/issues/2521
> Introduces standard default english names for entities

- nailgun/entities.py
As per [this discussion](https://github.com/SatelliteQE/robottelo/pull/3483#issuecomment-221566076) and [BZ1339696](https://bugzilla.redhat.com/show_bug.cgi?id=1339696), manifest upload duration increases depending on number of organizations and activation keys present in system. And in the end of automation run, according to @rplevka's investigation, it takes up to 11 minutes to upload a manifest.
Updating timeout for manifest upload operation to 15 mins so we can successfully receive the results.
Closes #293
> Increase timeout for manifest upload

- nailgun/entities.py
- Add EntitySearchMixin to Host Entity
- Some import order and styling fixes
> Add EntitySearchMixin to Host

- nailgun/entities.py
2016-08-10 18:41:40 - nailgun.client - DEBUG - Making HTTP GET request to https://server/katello/api/v2/content_view_versions/54 with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and no data.
2016-08-10 18:41:41 - nailgun.client - DEBUG - Received HTTP 200 response:   {"version":"1.0","major":1,"minor":0,"composite_content_view_ids":[],"content_view_id":53,"default":false,"description":null,"package_count":0,"puppet_module_count":0,"docker_manifest_count":0,"docker_tag_count":0,"ostree_branch_count":0,"id":54,"name":"wVFdzWKgog 1.0","created_at":"2016-08-10 15:41:13 UTC","updated_at":"2016-08-10 15:41:13 UTC","content_view":{"id":53,"name":"wVFdzWKgog","label":"wVFdzWKgog"},"katello_content_views":[],"environments":[{"id":48,"nam …
> Add few more attributes for ContentViewVersion entity

- nailgun/entities.py
- tests/test_entities.py
* Added 13 new fields for Errata entity
* Added following helpers: `Errata().compare()`, `Host().errata()`,
`Host().errata_apply()`, `Host().install_content()`,
`Repository().errata()`.
* Added unit tests for new helpers
> Updated Errata entity and added heplers for errata/packages installation

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
close #333
```python
import sys; print('Python %s on %s' % (sys.version, sys.platform))
sys.path.extend(['/home/renzo/PycharmProjects/nailgun'])
>>> cfg=ServerConfig('https://foo.bar',('bar','baz'), verify=False)
>>> env=entities.Environment(cfg, name='env2').create()
>>> hostgroup=entities.HostGroup(cfg, name='hgroup2').create()
>>> combination=entities.TemplateCombination(cfg, hostgroup=hostgroup,
environment=env)
>>> cfg_template=entities.ConfigTemplate(cfg, name='cfg2',
snippet=False,
template='cat',
template_kind=8,
template_combinations=[combination])
>>> cfg_template.create()
ConfigTemplate( ServerConfig(url='https://foo.bar', verify=False, auth=('bar', 'baz')), snippet=False, locked=False, template_kind= …
```
> Fixed ConfigTemplate create and update with TemplateCombination

- nailgun/entities.py
- tests/test_entities.py
Error is expected because of bug.
```python
proxy = entities.SmartProxy(url=url).create()
Making HTTP POST request to https://sat6.com/api/v2/smart_proxies with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}} and data {"url": "https://sat6.com:10734", "name": "rhAuFYh"}.
Received HTTP 201 response: {"created_at":"2016-12-16 15:46:40 UTC","updated_at":"2016-12-16 15:46:40 UTC","name":"rhAuFYh","id":44,"url":"https://sat6.com:10734","features":[{"name":"Pulp","id":2},{"name":"TFTP","id":4},{"name":"DNS","id":5},{"name":"DHCP","id":6},{"name":"Puppet","id":7},{"name":"Puppet CA","id":8},{"name":"Logs","id":12},{"name":"Dynflow","id":13},{"name":"SSH","id":14},{"name":"Discovery","id":15},{"name":"Openscap","id":17}],"locations":[{"id": …
```
> Add Create and Delete mixins to Smart Proxy

- .travis.yml
> [6.2.z] Cherry-pick - Update travis config

- nailgun/entities.py
- tests/test_entities.py
> [6.2.z] - Cherrypick - add Smart Proxy/Smart Variables helpers

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
(cherry picked from commit ecf91be)
> [6.2.z] Implemented Entity __eq__ method comparing all fields (#350)

- .travis.yml
- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
(cherry picked from commit ecf91be)
(cherry picked from commit f231e8c)
> Implemented Entity __eq__ method comparing all fields (#350)

- nailgun/entities.py
```python
In [15]: tk = nailgun.entities.TemplateKind(config).search(query={'search': 'name=PXELinux'})
In [16]: tk
Out[16]: [nailgun.entities.TemplateKind(nailgun.config.ServerConfig(url='https://sat6.com', verify=False, auth=('admin', 'changeme')), id=2, name=u'PXELinux')]
In [18]: tk[0].name
Out[18]: u'PXELinux'
```
> Update TemplateKind entity

- nailgun/entities.py
- tests/test_entities.py
* Implemented Interface entity (as before it was basically a stub with
no available operations and even wrong path)
* Added all possible fields variations
* Implemented unit tests
Key features:
* Interface requires a host id in its path, so some additional logic
was required for initialization, `read()` and `search()`
* Set of available Interface fields depends on Interface's ``type``
(some fields are only returned for specific type), extra logic was
required here too
> [6.2.z] [Cherry-pick] Implemented Interface entity with all its fields and basic operations (#373)

- nailgun/entities.py
- tests/test_entities.py
Cherry-picked from cherry-pick #356 :D
But seriously, I've found that Image implementation was wrong while cherry-picking it to 6.2.z. Time to have those changes in master.
> Update Image and Host entities

- nailgun/entities.py
- tests/test_entities.py
Cherrypick from #315 and #317 with tiny change, specific for 6.2, in separate commit.
> [6.2.z] Cherrypick SCP/SV related changes

- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- tests/test_entity_mixins.py
> Unique fields ignored on __eq__

- nailgun/entity_fields.py
Fix for SatelliteQE/robottelo#4543.
> Generate unicast MAC for MACAddressField.

- nailgun/entities.py
```python
In [5]: from nailgun import entities
In [6]: repo = entities.Repository(mirr
...: or_on_sync=True).create(True)
In [7]: repo.mirror_on_sync
Out[7]: True
```
> Added 'mirror_on_sync' field to Repository entity

- nailgun/entities.py
```
In [6]: entities.CommonParameter(server_config).create(create_missing=True)
Out[6]: nailgun.entities.CommonParameter(id=39, value=u'\ud1da\U00026556\u421e\u971f\U000276b9\u4bb7\u65e3\U00013128\U00021728\U0002b298\U00025db9\U000132be\u677e\uc984\u1d6b', name=u'\u780e\u3d73')
In [7]: entities.CommonParameter(server_config, id=39).read()
Out[7]: nailgun.entities.CommonParameter(id=39, value=u'\ud1da\U00026556\u421e\u971f\U000276b9\u4bb7\u65e3\U00013128\U00021728\U0002b298\U00025db9\U000132be\u677e\uc984\u1d6b', name=u'\u780e\u3d73')
In [12]: a = entities.CommonParameter(server_config, name='qwerty', value='123').create(create_missing=True)
In [13]: a.name = 'ytrewq'
In [14]: a.update(['name'])
Out[14]: nailgun.entities.CommonParameter(id=40, value=u'123', name=u'ytrewq')
In [16]: …
```
> Update CommonParameter entity.

- nailgun/client.py
> [6.2.z][Cherry-pick] location of urllib3 changed in requests module (#415)

- nailgun/entities.py
- tests/test_entities.py
```python
host = Host(id=2).read()
host.power(data={"power_action": "state"})
host.power(data={"power_action": "on"})
host.power(data={"power_action": "off"})
```
> Allow host power off/on

- nailgun/entities.py
Helps when automating tasks that need information about nested Locations.
> Adding parent_name to Location entity

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
this allows uploading big files that cannot be uploaded in one go
> add support for chunked content uploads

- nailgun/entities.py
```
In [1]: sub = entities.Subnet().create()
2017-09-18 07:14:20 - nailgun.client - DEBUG - Making HTTP POST request to https://server/api/v2/subnets with options {'verify': False, 'auth': ('admin', 'changeme'), 'headers': {'content-type': 'application/json'}}, no params and data {"subnet": {"mask": "255.252.0.0", "network": "252.82.67.77", "name": "KpatyikFQJCf"}}.
2017-09-18 07:14:21 - nailgun.client - DEBUG - Received HTTP 201 response: {"network":"252.82.67.77","network_type":"IPv4","cidr":14,"mask":"255.252.0.0","priority":null,"vlanid":null,"gateway":null,"dns_primary":null,"dns_secondary":null,"from":null,"to":null,"created_at":"2017-09-18 14:14:21 UTC","updated_at":"2017-09-18 14:14:21 UTC","ipam":"None","boot_mode":"DHCP","id":9,"name":"KpatyikFQJCf","network_address":"252.82.67.7 …
```
> Add subnet network prefix field

- nailgun/entities.py
- tests/test_entities.py
Changes:
1. Existing Subnet entity class updated for parameters
2. New SubnetParameter class added for parameters
> Entity class addtion for Subnet Parameters and Subnet class updated for parameters

- nailgun/entities.py
- tests/test_entities.py
Below two classes has been updated to automate 6.3 feature Canned Role:
1. Filter
2. Role
> Entity classes updated to automate 6.3 Canned Role feature

- nailgun/entities.py
- tests/test_entities.py
This backports https://github.com/SatelliteQE/nailgun/pull/419 to the 6.2.z branch.
> Allow getting and deleting AK subscriptions

- nailgun/entities.py
```console
In[2]: from nailgun import entities, config
In[3]: conf = config.ServerConfig('https://XXXXXXXXXXX', auth=('XXXX', 'XXXXXX'), verify=False)
In[4]: org = entities.Organization(conf).create(create_missing=True)
In[5]: host = entities.Host(conf, organization=org).create(create_missing=True)
In[6]: host.uuid
In[7]: import uuid
In[8]: host.uuid = str(uuid.uuid4())
In[9]: host.uuid
Out[9]: '55d680d9-1a96-4df3-ac4b-74b165b6412e'
In[10]: host.update(['uuid'])
Out[10]: nailgun.entities.Host(comment=None, domain=nailgun.entities.Domain(id=3), managed=True, ip=None, image=None, provision_method=u'build', hostgroup=None, owner=nailgun.entities.User(id=3), operatingsystem=nailgun.entities.OperatingSystem(id=4), subnet=None, realm=None, uuid=u'55d680d9-1a96-4df3-ac4b-74b165b6412e', …
```
> Add Host uuid field

- nailgun/entities.py
```console
In[2]: from nailgun import entities, config
In[3]: conf = config.ServerConfig('https://XXXXXXXXXX', auth=('XXXX', 'XXXX'), verify=False)
In[4]: org = entities.Organization(conf).create(create_missing=True)
In[5]: product = entities.Product(conf, organization=org).create(create_missing=True)
In[6]: repo = entities.Repository(conf, product=product).create(create_missing=True)
In[7]: repo.full_path
Out[7]: u'http://XXXXXXXXXX/pulp/repos/SKKxBWF/Library/custom/SNNpnpKWV/PiPSwVCWZW/'
In[8]: repo.unprotected = False
In[9]: repo.update(['unprotected'])
Out[9]: nailgun.entities.Repository(product=nailgun.entities.Product(id=322), gpg_key=None, mirror_on_sync=True, content_counts={u'puppet_module': 0, u'erratum': 0, u'package': 0, u'docker_manifest': 0, u'ostree_branch': 0, …
```
> Add Repository full_path field

- nailgun/entities.py
- tests/test_entities.py
> Fixed Subscriptions.read due to host id name mismatch

- nailgun/entities.py
- tests/test_entities.py
form https://github.com/SatelliteQE/nailgun/pull/461
ping @renzon
> Remove org from sync_plan api_path

- nailgun/entities.py
- tests/test_entities.py
> [6.3 Feature] SSH Key helpers added in User entity

- nailgun/entities.py
> SSL verification option in Repository entity

- nailgun/entities.py
> added ignorable_content for Repository

- nailgun/entities.py
Reverts SatelliteQE/nailgun#498
> Revert "added ignorable_content for Repository"

- nailgun/entities.py
- tests/test_entities.py
> New Entities TemplateImport and TemplateExport

- nailgun/entities.py
Change pretty nothing from functionality perspective, but that will make testing for UI much easier as special characters are not treated very well at that moment in Chrome
> Change password type for better support for UI tests

- nailgun/entities.py
- tests/test_entities.py
Fixes : https://github.com/SatelliteQE/robottelo/issues/6087
> Fix Override Value data syntax for smart class parameter and smart variable

- nailgun/entities.py
This change requries https://github.com/theforeman/foreman/pull/5741
> Adding locked state to ptable

- nailgun/entities.py
This change was affecting 6.4 automation. Soon we are planning to do 6.4 branching and then we can accommodate this change.
> reverted locked state to ptable

- nailgun/entities.py
> Locked field in PTable

- nailgun/entities.py
This commit add repositories & description fields to ContentViewVersion.
It also fixes an issue with a CVV environment as it should have been LifecycleEnvironment
> Add more attrs to ContentViewVersion

- nailgun/entities.py
- tests/test_entities.py
Adding JobTemplate and Template input class. They are already working in the [foreman-ansible-modules](https://github.com/theforeman/foreman-ansible-modules/pull/125).
> Add JobTemplate and TemplateInput entities

- .flake8
- nailgun/entities.py
- tests/test_entities.py
> Added VirtWhoConfig entity to test the virt-who configure plugin

- nailgun/entities.py
- tests/test_entities.py
Reverts SatelliteQE/nailgun#532
Sorry, but we cannot merge PR without two ACKs due any reason
> Revert "Don't require content_view_version_id kwargs to CVV incremental_update()"

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
```
>>> config = ServerConfig(url="https://centos7-katello-nightly.sean.example.com", auth=( 'admin', 'changeme'), verify=False)
>>> ForemanStatus(config).search_json()
{u'status': 200, u'version': u'1.20.0-develop', u'result': u'ok', u'api_version': 2}
> add Foreman Status entity

- nailgun/entities.py
- tests/test_entities.py
Added fields and actually made it call the right method.
> Fix VirtWhoConfig.update_payload

- nailgun/entities.py
Reads the pool_id (cp_id) of subscription.
> Read Pool ID of Subscription

- nailgun/entities.py
- tests/test_entities.py
$subject
Use:
```
entities.HostSubscription(host=host.id).add_subscriptions(
data={
'subscriptions':{
'id': sub.id,
'quantity' :1}
}
)
```
> Add Support for adding subscriptions to host

- nailgun/entities.py
- tests/test_entities.py
> Fix search of Product added in Syncplan asks for organization

- nailgun/entities.py
- tests/test_entities.py
Cherry-pick from https://github.com/SatelliteQE/nailgun/pull/562
> Add File entity

- nailgun/entities.py
Cherry-picks from:
- https://github.com/SatelliteQE/nailgun/pull/566
- https://github.com/SatelliteQE/nailgun/pull/567
I wouldn't normally do 2 in a single PR but these 2 commits are closely linked.
>  Add more attrs to ContentViewVersion 

- nailgun/entities.py
- tests/test_entities.py
* add Composite Content View Support
* rename content_view_components to content_view_component
Cherry-pick from https://github.com/SatelliteQE/nailgun/pull/558
> add Composite Content View Support (#558)

- nailgun/entities.py
- tests/test_entities.py
> [6.3.z] Fix search of Product added in Syncplan asks for organization

- nailgun/entities.py
- tests/test_entities.py
> [6.3.z] [CherryPicked] Add Support for adding subscriptions to host and Read PoolId of subscription

- nailgun/entities.py
(cherry picked from commit ffce8d8d039384bbf5af491b25c10171862498c7)
> authSourceLDAP Search support (#644)

- nailgun/entities.py
> [cherry-pick] uuid for ContentViewPuppetModule now deprecated

- nailgun/entities.py
> Add Compute Resource to Hostgroup support added

- nailgun/entities.py
- tests/test_entities.py
Fixes #652
Test Results:
```
$ pytest tests/test_entities.py 
=================================================================================== test session starts ===================================================================================
platform linux -- Python 3.6.6, pytest-5.1.1, py-1.8.0, pluggy-0.12.0
rootdir: /home/jpathan/projects/nailgun
collected 160 items                                                                                                                                                                       
tests/test_entities.py ............................................................................................................................................................ [ 97%]
.... …
```
> Add support for scap-content

- nailgun/entities.py
Create user_data/cloud_init Image support added from Nailgun.
> User data image support added

- nailgun/entities.py
- tests/test_entities.py
> Fixes #654 - Update CompliancePolicies entity

- nailgun/entities.py
- tests/test_entities.py
> fixes #658 - Add scap_content_profiles field in ScapContents.

- nailgun/client.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
Fix minor typos in docstrings.
> Fix minor typos

- nailgun/entities.py
Add ignorable_content field to Repository entity.
> Add ignorable_content field to Repository entity

- nailgun/entities.py
> [Cherry-pick] User data image support added

- nailgun/entities.py
> [Cherry-pick] Add Compute Resource to Hostgroup support added

- nailgun/entities.py
- tests/test_entities.py
- Cherry-pick of https://github.com/SatelliteQE/nailgun/pull/667
> [Cherry-pick] Added support for group_parameters_attributes

- nailgun/entities.py
- tests/test_entities.py
Adding the support for module stream content filters Upstream PR https://github.com/Katello/katello/pull/8295
Satellite 6.7 
Please take a look at https://github.com/SatelliteQE/robottelo/pull/7339
> adding support for module stream filter support

- nailgun/entities.py
- tests/test_entities.py
- Added support for `Content_type`.
- Added `Srpms` entities with respective test.
> Added/extented entities of SRPMs and content_type

- nailgun/entities.py
- tests/test_entities.py
> Cherry-pick of PR #662

- nailgun/entities.py
- tests/test_entities.py
Cherry-pick commits from PR #655, which apparently never made it to stable-satellite branch.
> [cherry-pick] adding support for module stream filter support

- nailgun/entities.py
- tests/test_entities.py
Fixes #683 
Test result:
```
In [3]: entities.HTTPProxy(id=1).read()                                                                                                                                                    
Out[3]: nailgun.entities.HTTPProxy(name='example.com', url='http://example.com:3128', username='admin', id=1)
```
```
In [3]: entities.HTTPProxy().search()                                                                                                                                                      
Out[3]: 
[nailgun.entities.HTTPProxy(name='example.com', url='http:/example:3128', username='admin', id=1),
nailgun.entities.HTTPProxy(name='qLgEoIxsqUcpvFI', url='https://mcrLQzBqrHRIkPN', username='vEqyfYattWhKMKL', id=2),
nailgun.entities.HTTPProxy(name='bMIigaXrGmWvoef', …
```
> Fixes #683 - Added support for http_proxy entity.

- nailgun/entities.py
- tests/test_entities.py
Support is added:
- Discover host search
- Discover Host Provision
> Add Discovery Host search and Provision support from API

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of https://github.com/SatelliteQE/nailgun/pull/681
> Add Host disassociate operation (#681)

- nailgun/entities.py
- tests/test_entities.py
> Add Discovery Provision support from API

- nailgun/entities.py
- tests/test_entities.py
> GCE CR Support

- nailgun/entities.py
- tests/test_entities.py
> Additional functions to Host and Compute Resource

- nailgun/entities.py
- tests/test_entities.py
Helper functions created to schedule a report using the API
> Report template fix for scheduling

- nailgun/entities.py
- tests/test_entities.py
* Report Template scheduling
* doc string fix
* Fixed flake8 failure
* test cases for helper functions
* fixed flake8 travis failure
> Report template fix for scheduling (#706)

- nailgun/entities.py
* fix organization&location read error
* remove config_template in Organization and Location
> [cherry-pick] Remove `config_template` in Organization and Location entities (#715)

- nailgun/entities.py
> subnet fix mt to mtu

- nailgun/entities.py
Now to 6.7.z
master #717 
stable #718
> [cherry-pick] subnet fix mt to mtu

- nailgun/entities.py
- tests/test_entities.py
remove all occurences of `config_template` and `ConfigTemplate`
> [cherry-pick] deleting other occurencies of config template

- nailgun/entities.py
Need this field in PR: https://github.com/SatelliteQE/robottelo/pull/7858
> adding the field name auth_source_name

- nailgun/entities.py
- tests/data/ssg-rhel7-ds-tailoring.xml
- tests/test_entities.py
Cherry-pick PR: https://github.com/SatelliteQE/nailgun/pull/722
> [Cherry-pick] Fixes #721 - Added support for Tailoring file entity

- nailgun/entities.py
> removed resource-type parameter from Permission entity

- nailgun/entities.py
Cherry-picking #727 into `stable-satellite`
> [cherry-pick] Host creation fix.

- nailgun/entities.py
Hello
this is used here: https://github.com/SatelliteQE/robottelo/pull/7982
It implements:
https://theforeman.org/plugins/katello/3.15/api/apidoc/v2/hosts_bulk_actions.html#description-remove_subscriptions
> Add bulk_remove_subscriptions support

- nailgun/entities.py
Cherry-picking https://github.com/SatelliteQE/nailgun/pull/734 into `stable-satellite`
> [cherry-pick] Add bulk_add_subscriptions (#733)

- nailgun/entities.py
Cherry-pick #754 into `stable-satellite` branch.
> [cherry-pick] Add support for reading subscriptions

- nailgun/entities.py
Hello
this is for new test, so test results will be at:
https://github.com/SatelliteQE/robottelo/pull/8024
> Add support for bulk available incremental updates

- nailgun/entities.py
Cherry-picking https://github.com/SatelliteQE/nailgun/pull/735 into `stable-satellite`
> [cherry-pick] adding the field name auth_source_name (#735)

- nailgun/entities.py
master commit #761 and cherry pick to stable #763
> [cherry-pick 6.8.z] traces status ignored

- nailgun/entities.py
> [cherry-pick to stable] traces status ignored

- nailgun/entities.py
- tests/test_entities.py
We need an entity for the docker type content view filter
Signed-off-by: David Vallee Delisle <dvd@redhat.com>
> Adding DockerContentViewFilter

- nailgun/entities.py
- nailgun/entity_mixins.py
I was right :) , https://github.com/SatelliteQE/nailgun/pull/757 really had potential to break something. Thanks @vsedmik for catching it! Before we start the review, please, confirm that this indeed fixes the issue.
> Rename to _updatable_fields and do not return it in get_values

- nailgun/entities.py
- nailgun/entity_mixins.py
> [cherry-pick 6.8.z] Rename to _updatable_fields and do not return it in get_values

- nailgun/entities.py
Hello
looks like a reformat failure due to Black.
Thank you
> Fix whitespace in API path

- nailgun/entities.py
- nailgun/entity_mixins.py
- tests/test_entities.py
- tests/test_entity_mixins.py
It might be interesting to tweak the timeout parameter on a per-function
level. This adds it to all functions that have a synchronous option.
> Adding timeout to synchronous functions

- .github/PULL_REQUEST_TEMPLATE.md
Fixes #578
**Point to the API documentation/Plugin/feature? Please describe.**
A clear and concise description of the plugin you have added or the entity you have updated
**Presentation that this code works**
An Example that the code works. You can exercise the code as raw API calls or using any other method
`Eg: # Read Snapshot
Snapshot(host=<host_id>, id=<snapshot_id>).read()`
~~~~~~~~
**Additional Information**
> Create the Pull request template

- nailgun/entities.py
adding missing properties to activation key based on sat 6.9 apidoc
> adding properties to activation key

- nailgun/entities.py
Added the simple content access entity field into the organization entity
```entities.Organization(id=111).read().simple_content_access = {bool} True```
> added SCA entity field

- nailgun/entities.py
This adds the abilit to enable/disable and check eligibility
of SCA for an organization.
> Add SCA functionality to the Organization entitiy

- nailgun/entities.py
- nailgun/entity_mixins.py
Fixes issue related to puppet or any other disabled feature
Refer for more info:
- https://github.com/SatelliteQE/nailgun/pull/804
- https://github.com/SatelliteQE/nailgun/pull/799
- https://github.com/SatelliteQE/nailgun/pull/802
> Fixes issue related to disabled puppet feature

- nailgun/entities.py
- tests/test_entities.py
Smart variables were removed from Satellite long time ago (in 6.8).
Now the time has come to remove it's support from Nailgun.
https://projects.theforeman.org/issues/28278
> Remove smart variables

- nailgun/entities.py
Ran this locally and it seems to pass.
> mirroring_policy on 6.10.z

- setup.py
Extending https://github.com/SatelliteQE/nailgun/pull/816
> More py36 removal and python base version in setup

- nailgun/entities.py
There was more OS added to list in 6.11.
> Add more OS to list for 6.11

- nailgun/entities.py
SSIA
new param is needed for the test
> adding new param to interface entity

- nailgun/entities.py
> Nailgun Image entity failing with multiple server config

- nailgun/entity_mixins.py
Moved a helper method which updates the timeout to nailgun
robottelo.api.utils --> nailgun.nailgun_entities
> Moved helper method

- nailgun/entities.py
Added support for Ansible playbooks entity for Fetch and Sync.
> Added support for Ansible playbooks entity

- .github/workflows/auto_assignment.yaml
- .github/workflows/auto_cherry_pick.yml
- .github/workflows/stale.yml
- .pre-commit-config.yaml
This will copy the PRT comment from the Parent PR to cherrypick PR.
https://github.com/SatelliteQE/robottelo/pull/10308
> updating the github actions across the nailgun

- .github/workflows/auto_assignment.yaml
- .github/workflows/auto_cherry_pick.yml
- .github/workflows/stale.yml
- .pre-commit-config.yaml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/858
This will copy the PRT comment from the Parent PR to cherrypick PR.
https://github.com/SatelliteQE/robottelo/pull/10308
> [6.11.z] updating the github actions across the nailgun

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/860
Auto cherrypicking to zStream branches based on the zStream labels added to the parent PR.
> [6.13.z] Cherrypicking based on branch labels added to the parent PR

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/860
Auto cherrypicking to zStream branches based on the zStream labels added to the parent PR.
> [6.12.z] Cherrypicking based on branch labels added to the parent PR

- .github/workflows/auto_cherry_pick.yml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/860
Auto cherrypicking to zStream branches based on the zStream labels added to the parent PR.
> [6.11.z] Cherrypicking based on branch labels added to the parent PR

- nailgun/entities.py
Add new fields to RegistrationCommand entity, related to https://github.com/SatelliteQE/robottelo/pull/10458
> Add new fields to RegistrationCommand entity

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/865
Add new fields to RegistrationCommand entity, related to https://github.com/SatelliteQE/robottelo/pull/10458
> [6.13.z] Add new fields to RegistrationCommand entity

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/865
Add new fields to RegistrationCommand entity, related to https://github.com/SatelliteQE/robottelo/pull/10458
> [6.12.z] Add new fields to RegistrationCommand entity

- nailgun/entities.py
- tests/test_entities.py
Cherry-picking #841 and #881 into 6.12
> Cherrypick Ansible Role work to 6.12.z

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/automerge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/878
Added support for automerge in the Nailgun repo
> [6.12.z] added support for auto-merge in nailgun repo

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/automerge.yaml
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/878
Added support for automerge in the Nailgun repo
> [6.11.z] added support for auto-merge in nailgun repo

- nailgun/entities.py
Cherrypick of https://github.com/SatelliteQE/nailgun/pull/898
> [6.12.z]Add read template support 6.12.z

- nailgun/entities.py
Cherrypick of https://github.com/SatelliteQE/nailgun/pull/898
> [6.11.z]Add read template support 6.11.z

- nailgun/entities.py
- tests/test_entities.py
Adding add and remove ansible_role to host and hostgroup endpoints.
https://github.com/theforeman/foreman_ansible/pull/597
https://github.com/theforeman/foreman_ansible/pull/626
> Add and remove ansible_role to host/hostgroup

- nailgun/entities.py
- tests/test_entities.py
> Add and remove ansible_role to host/hostgroup (#927)

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/922
Simple PR, adds a new flag for the content-view publish audit feature.
> [6.14.z] Nailgun Updates for Needs_publish feature

- .github/workflows/auto_cherry_pick.yml
> [6.12.z] - remove g-chat notification for failed auto-cherrypick, handled in slack

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/954
Subset of https://github.com/SatelliteQE/nailgun/pull/929/
> [6.12.z] Adding entity mixins classes

- .github/workflows/auto_cherry_pick.yml
> [6.11.z] - remove g-chat notification for failed auto-cherrypick, handled in slack

- nailgun/entities.py
- tests/test_entities.py
Cherry-pick of https://github.com/SatelliteQE/nailgun/pull/936
> [6.12] Play ansible roles on host

- nailgun/entities.py
- tests/test_entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/992
null
> [6.14.z] AK update must contain org id, it is a required field

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1139
Missing outputs, rerun, cancel endpoints in JobInvocation entity
```
In [28]: result = sat.api.JobInvocation(id=20).outputs()
In [29]: [i for i in result['outputs'][0]['output'] if i['output'] == 'Exit status: 0']
Out[29]:
[{'output_type': 'stdout',
'output': 'Exit status: 0',
'timestamp': 1715268351.528926}]
```
> [6.13.z] Add outputs, rerun, cancel endpoints in JobInvocation entity

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/automerge.yaml
- .github/workflows/merge_to_master.yml
There were a few failed cherry-picks that this commit resolves in one go. Specific issues will be tagged and aligned in GitHub.
Fixes: 
#1168
#1171 
#1176 
#1181
> [6.15.z] - Handle failed workflow cherry-picks

- .github/workflows/auto_cherry_pick.yml
- .github/workflows/automerge.yaml
- .github/workflows/merge_to_master.yml
There were a few failed cherry-picks that this commit resolves in one
go. Specific issues will be tagged and aligned in GitHub.
Fixes:
#1121
#1169
#1170 
#1182
> [6.14.z] - Handle failed workflow cherry-picks

- nailgun/entities.py
Adding support for OS parameter attributes
> Add support for OS Parameters

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1191
Adding support for OS parameter attributes
> [6.15.z] Add support for OS Parameters

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1191
Adding support for OS parameter attributes
> [6.14.z] Add support for OS Parameters

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1191
Adding support for OS parameter attributes
> [6.13.z] Add support for OS Parameters

- nailgun/entities.py
Adding password field for CR image creation
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15733
> Add password field for CR image creation

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1204
Adding password field for CR image creation
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15733
> [6.15.z] Add password field for CR image creation

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1204
Adding password field for CR image creation
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15733
> [6.14.z] Add password field for CR image creation

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1204
Adding password field for CR image creation
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/15733
> [6.13.z] Add password field for CR image creation

- .pre-commit-config.yaml
- docs/conf.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1083
updates:
- [github.com/psf/black: 23.12.1 → 24.8.0](https://github.com/psf/black/compare/23.12.1...24.8.0)
- [github.com/astral-sh/ruff-pre-commit: v0.1.13 → v0.5.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.1.13...v0.5.7)
- [github.com/pre-commit/pre-commit-hooks: v4.5.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.5.0...v4.6.0)
> [6.15.z] [pre-commit.ci] pre-commit autoupdate

- .pre-commit-config.yaml
- docs/conf.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1083
updates:
- [github.com/psf/black: 23.12.1 → 24.8.0](https://github.com/psf/black/compare/23.12.1...24.8.0)
- [github.com/astral-sh/ruff-pre-commit: v0.1.13 → v0.5.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.1.13...v0.5.7)
- [github.com/pre-commit/pre-commit-hooks: v4.5.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.5.0...v4.6.0)
> [6.14.z] [pre-commit.ci] pre-commit autoupdate

- .pre-commit-config.yaml
- docs/conf.py
- nailgun/__init__.py
- nailgun/client.py
- nailgun/config.py
- nailgun/entities.py
- nailgun/entity_fields.py
- nailgun/entity_mixins.py
- tests/test_client.py
- tests/test_config.py
- tests/test_entities.py
- tests/test_entity_fields.py
- tests/test_entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1083
updates:
- [github.com/psf/black: 23.12.1 → 24.8.0](https://github.com/psf/black/compare/23.12.1...24.8.0)
- [github.com/astral-sh/ruff-pre-commit: v0.1.13 → v0.5.7](https://github.com/astral-sh/ruff-pre-commit/compare/v0.1.13...v0.5.7)
- [github.com/pre-commit/pre-commit-hooks: v4.5.0 → v4.6.0](https://github.com/pre-commit/pre-commit-hooks/compare/v4.5.0...v4.6.0)
> [6.13.z] [pre-commit.ci] pre-commit autoupdate

- nailgun/entity_mixins.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1224
The output of raise_for_status is not really descriptive for since the actual error message is not part of the exception.
This commit exapnds on 95b3ce10125cfbc8d9a6d8a8e2b38a5007dd1b16
Adds existing solution to all raise_for_status calls.
Example:
```
requests.exceptions.HTTPError: ('500 Server Error: Internal Server Error for url: https://robo-main-orcharhino-alma8.infra.dev.atix/katello/api/v2/repositories/42', {'displayMessage': 'Repository cannot be deleted since it has already been included in a published Content View. Please delete all Content View versions containing this repository before attempting to delete it or use --remove-from-content-view-versions flag to automatically remove the repository from all …
```
> [6.16.z] Abstract adding json respone to error message

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
(cherry picked from commit 8753c80a8be4857a779dbe293eb0a0c723a10ea2)
Manual Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1261
Fixes https://github.com/SatelliteQE/nailgun/issues/1264
> [6.14.z] Add Python 3.13 for PR checks in GHA

- .github/workflows/merge_to_master.yml
- .github/workflows/pull_requests.yml
Manual Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1261
Fixes https://github.com/SatelliteQE/nailgun/issues/1263
> [6.15.z] Add Python 3.13 for PR checks in GHA

- nailgun/entities.py
Added  a couple of API endpoints to address comments from here =>
https://github.com/SatelliteQE/robottelo/pull/18292#discussion_r2063519459
```
This module wraps hammer commands only. All direct API calls should come from Nailgun. This needs to be a separate PR in the nailgun project, and the API endpoint should be called from the test/test helper through nailgun.
```
> Added rh_cloud last report and upload logs

- nailgun/entities.py
> Add JobTemplate.clone API

- nailgun/entities.py
Cherrypick of PR: https://github.com/SatelliteQE/nailgun/pull/1304
**_1:_** Currently, we cannot api DELETE a `ContentViewVersion` if it is published to any LCE, including Library, ISE 500.
**_2:_** There is no api method to remove/delete a `ContentViewVersion` from the `ContentView` , only for removing a single environment by :id
***_3:_*** We do not currently have an api method that calls the same endpoint, as the UI ContentViewVersion Delete wizard. 
See solution.
- We must first remove the Version from any published/promoted environments, including library, before attempting to Delete.
- `ContentViewVersion.delete()` calls the Katello Destroy api, performs no checks or steps before 
attempting bulk Destroy. `DELETE , "/content_view_versions/:id", ("Remove content view version")`
^ on …
> [6.17.z] ContentView::RemoveVersion (from the CV and any ENVs)

- nailgun/entities.py
- tests/test_entities.py
Adding description key to _fields dictionary to incorporate description feature for job-template 
Dependent PR: https://github.com/SatelliteQE/robottelo/pull/19093
> Add description key to _fields dictionary
